load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "authentik": "goauthentik/authentik:~>2025.12.0",
        "random": "hashicorp/random:~>3.7.0",
        "vault": "hashicorp/vault:~>5.7.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "harbor",
    providers = [
        "authentik",
        "random",
        "vault",
    ],
    providers_versions = ":providers",
)
