apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: forgejo
  namespace: seaweedfs
spec:
  seaweedRef:
    name: seaweedfs
  reclaimPolicy: Retain
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: forgejo
  namespace: seaweedfs
spec:
  seaweedRef:
    name: seaweedfs
  identityRef:
    name: forgejo
  secretRef:
    name: s3-identity-forgejo
  reclaimPolicy: Retain
