load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "vars",
    srcs = ["vars.py"],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
)

py_library(
    name = "setup",
    srcs = ["setup.py"],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        ":vars",
        "//devinfra/claude:errors",
        "//devinfra/claude:settings",
        "//util/bazel:runfiles",
        "//util/bazel:subprocess",
        "@pypi//cryptography",
        "@pypi//opentelemetry_api",
    ],
)
