load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "vars",
    srcs = ["vars.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "credentials",
    srcs = ["credentials.py"],
    visibility = ["//visibility:public"],
    deps = ["@pypi//pyjwt"],
)

py_library(
    name = "setup",
    srcs = ["setup.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":proxy",
        ":vars",
        "//devinfra/claude:errors",
        "//devinfra/claude:session_paths",
        "//devinfra/claude:settings",
        "//util:net",
        "//util/bazel:runfiles",
        "@pypi//cryptography",
        "@pypi//opentelemetry_api",
    ],
)

py_library(
    name = "proxy",
    srcs = ["proxy.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "test_vars",
    srcs = ["test_vars.py"],
    deps = [
        ":vars",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
