load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "tana",
    srcs = glob(
        ["**/*.py"],
        exclude = ["tests/**"],
    ),
    data = glob([
        "export/references/**/*",
        "export/headless_autoexport/**/*",
        "export/assets/**/*",
        "export/*.md",
        "export/*.txt",
    ]),
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//playwright",
        "@pypi//pydantic",
    ],
)

py_binary(
    name = "tana-export",
    srcs = ["export/cli.py"],
    imports = [".."],
    main = "export/cli.py",
    deps = [":tana"],
)

py_binary(
    name = "tana-export-convert",
    srcs = ["export/convert.py"],
    imports = [".."],
    main = "export/convert.py",
    deps = [":tana"],
)

py_binary(
    name = "tana-export-searches",
    srcs = ["export/materialize_searches.py"],
    imports = [".."],
    main = "export/materialize_searches.py",
    deps = [":tana"],
)

py_binary(
    name = "tana-export-issues",
    srcs = ["export/tana_issues_to_tanapaste.py"],
    imports = [".."],
    main = "export/tana_issues_to_tanapaste.py",
    deps = [":tana"],
)

py_test(
    name = "test_tana",
    srcs = glob(["tests/**/*.py"]),
    imports = [".."],
    main = "tests/test_convert.py",
    deps = [
        ":tana",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":tana"],
)
