# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ~/.zshrc
. /etc/profile

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Uncomment to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Disable command auto-correction.
DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Disable marking untracked files under VCS as dirty.
# This makes repository status check for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Change the command execution time stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# interesting plugins: 'z'

# For alias-finder - automatically search for aliases for any commands I'm running
ZSH_ALIAS_FINDER_AUTOMATIC=true
# aliases: acs, acs <keyword> - list aliases
# git: gst, gca, gp, ...
# python: py alias
#
# isodate: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/isodate
#
# interesting plugins not enabled:
#   magic-enter https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/magic-enter
#   colored-man-pages
#   colorize (ccat)
#   per-directory-history
#   gitfast (alternative to git)
#   systemd
#   pip
#   tig
#   tmux
#   ubuntu
#   vscode
#   web-search
#   z
#   zbell
#   zsh-interactive-cd
#   dirpersist
#   dnote
#
# removed but I had them on:
#   ag
# 2025-01-28: disabling gcloud, seems slow
plugins=(alias-finder bazel aliases colored-man-pages command-not-found docker git gpg-agent isodate lein python rust screen)

# Agnoster is a ZSH theme assuming Solarized and Powerline-patched fonts.
# Right prompt: current time
RPROMPT='%*'
DEFAULT_USER='agentydragon'
# ZSH_THEME='agnoster'
ZSH_THEME='powerlevel10k/powerlevel10k'

source $ZSH/oh-my-zsh.sh

# Nechci completion automaticky kdyz je to ambiguous
unsetopt menu_complete
unsetopt auto_menu

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' group-name ''
#zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list ''

#autoload -Uz compinit
#compinit

HISTFILE=~/.histfile
# https://github.com/bamos/zsh-history-analysis#increasing-the-history-file-size
HISTSIZE=10000000
SAVEHIST=10000000
setopt EXTENDED_HISTORY

setopt autocd

# vi mode
#bindkey -v

# emacs mode
bindkey -e

# Record keystrokes
# alias vim='vim -w ~/.vim-keylog "$@"'

ZSH_THEME_TERM_TITLE_IDLE="%n: %~ $"

unsetopt share_history # Don't share command history between zsh's

#eval `dircolors ~/.dir_colors/dircolors`
export MC_SKIN=~/.config/mc/solarized.ini

# for enca/enconv
export DEFAULT_CHARSET=utf8

alias gs='git status --short --branch'
source $HOME/.aliases

# The next line updates PATH for the Google Cloud SDK.
#if [ -f '/home/agentydragon/bin/google-cloud-sdk/path.zsh.inc' ]; then source '/home/agentydragon/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
#if [ -f '/home/agentydragon/bin/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/agentydragon/bin/google-cloud-sdk/completion.zsh.inc'; fi

# Do not paginate if less than 1 page.
export LESS="-F -X $LESS"

# SDK for Remarkable
#. /usr/local/oecore-x86_64/environment-setup-cortexa9hf-neon-oe-linux-gnueabi

# Start Python with some imports already loaded (like NumPy, Tensorflow)
export PYTHONSTARTUP=$HOME/.config/pythonstartup.py

# MuJoCo
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/agentydragon/.mujoco/mujoco210/bin

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set Aider OpenAI API key from OPENAI_API_KEY, if set.
if [ -n "$OPENAI_API_KEY" ]; then
    export AIDER_OPENAI_API_KEY=$OPENAI_API_KEY
fi

export AIDER_MODEL=o1
