# ~/.zshrc - Zsh interactive shell configuration
# For: oh-my-zsh, zsh-specific settings, prompt. Sources ~/.shellrc for common config
# See: ~/code/ducktape/dotfiles/docs/shell-configuration.md

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source shell-agnostic interactive configuration (includes profile)
. $HOME/.shellrc

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Uncomment to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Disable command auto-correction.
DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="%F{yellow}...%f"

# Disable marking untracked files under VCS as dirty.
# This makes repository status check for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Change the command execution time stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# interesting plugins: 'z'

# For alias-finder - automatically search for aliases for any commands I'm running
ZSH_ALIAS_FINDER_AUTOMATIC=true
# aliases: acs, acs <keyword> - list aliases
# git: gst, gca, gp, ...
# python: py alias
#
# isodate: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/isodate
#
# interesting plugins not enabled:
#   magic-enter https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/magic-enter
#   colorize (ccat)
#   per-directory-history
#   gitfast (alternative to git)
#   systemd
#   pip
#   tig
#   tmux
#   ubuntu
#   vscode
#   web-search
#   z
#   zbell
#   zsh-interactive-cd
#   dirpersist
#   dnote
#
# removed but I had them on:
#   ag
# 2025-01-28: disabling gcloud, seems slow
plugins=(
    alias-finder bazel aliases colored-man-pages command-not-found docker git gpg-agent isodate lein python rust screen

    # pyenv plugin removed - causes console output that breaks Powerlevel10k instant prompt
    # We handle pyenv setup properly in ~/.profile (PATH and init)
)

# Agnoster ZSH theme assumes Solarized and Powerline-patched fonts.
# Right prompt: current time
RPROMPT='%*'
DEFAULT_USER='agentydragon'
# ZSH_THEME='agnoster'
ZSH_THEME='powerlevel10k/powerlevel10k'

source $ZSH/oh-my-zsh.sh

# Nechci completion automaticky kdyz je to ambiguous
unsetopt menu_complete
unsetopt auto_menu

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' group-name ''
#zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list ''

#autoload -Uz compinit
#compinit

# https://github.com/bamos/zsh-history-analysis#increasing-the-history-file-size
HISTSIZE=10000000
SAVEHIST=10000000

setopt SHARE_HISTORY      # Combine history between sessions
setopt INC_APPEND_HISTORY # Append to history immediately, not only at session end
setopt EXTENDED_HISTORY   # Timestamps in history
setopt HIST_REDUCE_BLANKS # Trim whitespace

setopt autocd

# vi mode
#bindkey -v

# emacs mode
bindkey -e


ZSH_THEME_TERM_TITLE_IDLE="%n: %~ $"

# Powerlevel10k customization (run `p10k configure` to reconfigure)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Initialize atuin for better shell history
eval "$(atuin init zsh --disable-up-arrow)"
