apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: headscale-config
  namespace: flux-system
spec:
  interval: 15m
  approvePlan: "auto"
  path: ./cluster/terraform/gitops/headscale-config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  serviceAccountName: tf-runner

  backendConfig:
    customConfiguration: |
      backend "kubernetes" {
        secret_suffix    = "headscale-config"
        namespace        = "flux-system"
      }

  vars:
    - name: vault_address
      value: "http://instance.vault.svc.cluster.local:8200"
    - name: headscale_url
      value: "https://headscale.allegedly.works"
  varsFrom:
    - kind: Secret
      name: vault-token
      varsKeys:
        - vault_token
      optional: false
    - kind: Secret
      name: headscale-api-key
      varsKeys:
        - headscale_api_key
      optional: false
