apiVersion: v1
kind: Secret
metadata:
    name: authentik-admin-password
    namespace: authentik
stringData:
    admin_password: ENC[AES256_GCM,data:RDfEu1P9kMDoHcp6BsazLZtKt9vmIN/pHNDemQM0ayY=,iv:z4ZxtFUEPg8CZxz72OI7VZgj6eDY/Dj6XEjzdUGpZE4=,tag:CSw3fybyw8hS0roSikh1wA==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VmRHcE5KamdQc1hLYWVT
            NFpJanRneE9JMHNMSmd6Vnl4YTN1cnJLNlhVCkhmeUZwQjE3cmdGeGh0ODAzUnIr
            R2pxTDUwZGtRQlVsMU9NUGJiTHkrc1EKLS0tIEQ1ajg3OFM1NmJlZ3gwSmxiaFpq
            Tmt0RzlxV20xQ05sM3E3ampIcmwrTWMK0rpsVR5h307POlQgY5YKO5B4S+7eOBsR
            PVki7nDr6du1ov5MosEYQY8yy0teR6Lh+jgD5RO503peuEAXT8jpCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR2Y5OFl2TzljT2REOTNZ
            ck1YMXVFQlBsbnB1ZnpQbEFMcHZDOHRnQXhBCi9VOUMwcHU3b3JkL0hNTnZYd0Vn
            N3Bpdzc1MDJGems5aTFlUWdtZklyMU0KLS0tIG9CNEVNOTJhRXlNVzh5aFFCRWR5
            YWJjUGIvRWdoQnk0RFl3QlZKZWxpYVUKBQph77e6dBsQ7q/vFkTzH+0mF0fbnekm
            YaYIcBPuFysEIvagtdDV2LTo7RhEkIw/AHqxCn5S91P0JG36nXanUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T08:49:11Z"
    mac: ENC[AES256_GCM,data:6vm/4+rlfEUIv3rGfrj2V9hCtJ+6l9ZFOanqP0GE7Y3ZsWvAGfcpHWViGpGJpBwtSLXysm2DGaExVag0AaNyu8lDQq8O7VIa2hKrblD399Z4YAkvF0fHeXgk+xreJU4eGk352Z3pZjwUZ6alHcRZe7tmKdDF5o8Bt9BfCZubOtA=,iv:eeykVMccGTUbm1sNSydzBghF4BnF26K+dYEBU+iC4hU=,tag:sn2BkCQZkM/Qz2F/e31X5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
