load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "proxmox": "bpg/proxmox:~>0.91.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "k8s-worker-proxmox",
    providers = [
        "proxmox",
    ],
    providers_versions = ":providers",
    deps = [
        "//terraform/modules/nixos-image",
        "//terraform/modules/proxmox-vm",
    ],
)
