apiVersion: v1
kind: Secret
metadata:
  name: haku-mail-token
  namespace: flux-system
  annotations:
    description: Authentik JWT minted by authentik-jwt-rotation (rotated ~biweekly).
type: Opaque
stringData:
  jwt: ENC[AES256_GCM,data:O/FNrmgDE4EtjDlgE1mmGBcyw/4x/PAjw1IaJpzCJeb5f/l91+Cjj2+O7y9Mm6iUFz/mJfp2Wl600obzyCg99dV5hXF7nCDPgf/tmc55VB7Njs2rdeqj8e1hipyEYPq2LMvXqmNNQI4fXqYUu5txbU0HkSzWIxojTkcY2PdQxsuv5W6X7jISDwFu7rfdwuxkZXD8PVwFXwHqVPI5xjpjRq5a3HvvE35Xa8EcCo8FHQqHWVIS8TwcrJQCSYalG2mFH330Af5vaQrzGw1v+jRQra1QKws4aTqlcwPBKpnf+d2utbFR+AKQ+2UmRGqeY3JdlzRtfRmN4pAcPjq+XXTX7iZW8YVkcRQ1RUfREVYorvj0UyLA6LF1qgPGQH46YZliDm5GzRk5ZbMH0hK1t2k4C3+2iqLGmMMVVkeb/bw0sGAQ4/V9rA6Z4MVFMBUzon9YKeIilIhABgyxz9+TeY5x9BQ+Gy4Y8EaSKzsP3PBTy+wGukrXxEsRet9BvM8jmoXnugKN8hB/YAStS9EcAJTrYNdidnUJcDYkh4aNJDv0aEN9m25d03f+0Ql+jjDyUpAzkzljsVOdXnUAPhm+Hm3QeD0HcewlcALz5sUOncd5ROpALbebg55tPcAc9fBHOcZNqKhxRK1YY2PcPiEuweFL2bmh3TwD9xQK7AXmUqXlhkUgbs3tfx+c7WRijDzk/TJL9S3vCnQkEsnEzlQ0+rXteFSXlcQJUbSAbVPpCKugTYCfuSELLMMCZD+1A0kkHwh49WJtuP3wdv8A2pWDWUCmXlHpPEjVXTUfTQeGbPOTjskTt2RpOr8W/M1dnzBPc74NlpJX1L7tj9E/gt27fCfoqbW8Bm0cOKMMqU+movvxi1kLnSiUGEEb5iHWEZ7ZzUUaPd9JS65DfWTdv/Mt+pNygRGveF6iJzdIJz7Oe0hh9b6ZoFl0ZCgB8iU2AUyL5PKDKQVs9hyedYRhIxj+H0iyg3iR9JC/WpN+wVqUdRey7ryPc6PuuBQtzstbUyqGVCl21RTC11xUTq+rj+h5u75pNSt6G2ot125j5KlHCmYkzwR5GoOtEyE+tejmQw3MHbNI7oCKCO/EUaqQ6fvMHWhuVMljzXRPRUEVQC5CkJAkCm2QpHV7Wge05GgsqKasUgaUSWMaBoQPLV7MVARbQSML4LiDAuiLDAuqcjAVGT4B1tCFUOXgcnJsnEG+4L+xoIwRQ7Y01Y2/hlyGl7Xpb/sPMQCIwyvAuM4vnzWRXxSRcEFCDjJYfUBnuCvnrFYAbGS2RAs27qgtKaxcCz7hjhogCJqj0iaGaNx/+UmcxIRMWfdIRTeFhXmNyuCn/ucnwMl4GmiLtWyaG6/EmJEmJPns/WxPnPRbbMEFbUdmqEmJSKJ5nrJ+osdAp+/7mys7I31Dfh1/Y3CCPGZg5OqEZRdnMzdIrQp14slcSJL/3pjoV/wVG1a/jIzxkIWE4Jh5T/gMS+pkRJdNiGXyrlN/qtGsBECa7C0PCe7TWBAnSgCYi7aHhgglEYePsAGiTzPwAjNUaewJpnWi5C6U3f8/XMKkb4+y5mjrlRI7PgjbnnjPP73upQ91W9tPZR5OH3uJOYqIJehPhr1wSPcwg3YkJwVsH/C+GO977oWC25kNb6dIcMv8HtyIBmzrkwg+EKgtGF+nsK7+ocZwCWiZvRwvUyAqO+1KzI2TB6gjfaT+7RyT1ggwGhka856xC5+RuN/T9twNJImYgp76n2yO7vh8u+b0S31XcmmXDGozUiXL8bk70gj3fp2rinegzd/zYPEU5O44MqGIKOLSfNNuyp5fjtnIIhpftKBulO/zVSCamuNhdltCkEuDAFsfkGoe9AvFCOKb1qeDR3h0xfnkl4NZeMUUYkXTco6R68KXCFcQYILqHmWT1e9ZqfkzM427XxsVitLPb70LJrpFwhBXq3d5SA7X6iai+3YevxOl94JVUUxlr14XwYzktuqrV7UUTBYjQ4A4lbu42vwyHyFBQdyRIwafs+jpXj9g22Tm87COU4rwFiVrbi0i/RKsQQkasXHl1nnwOyp69K6l6Dq5CTFly9EhYYLljI4P37N4c8xGjTgFwJ10niZEo+RWPoSt+VXGQjQMmbUA+2LyuSx6cB2VSwcy7bBm120iJV4h3SI5PZk1SwKIGlnuxVvpSo5VJA3mmryH/zqiUwQosRz4Y1YX9UPrQSTc3H1kjaOOi7RvPjGsBgIvQyHiz396xS2wd1k435FOGghWuxQb,iv:boD4apbQpyEckDy2cuHrUeaskKztA1KKr3CM+WyO/uI=,tag:elsxD5tk2+T76Z31CJOO2A==,type:str]
  token-exp: ENC[AES256_GCM,data:m3NOcebPiCdSlw==,iv:UOaUvK6W+w0KvZFgw/shx7zrhoO/6m5i+xcs/3Prvms=,tag:LXhDk5uuPX//pRp/DVE4RA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwKzFtZldLRjFBTnc0YmtE
        NThWeDJkZkNZSUVLdmxuaDg4cnMydWRUYWdJCjI5Z0NvaWF2bTQ3d1JFdEl3ZzVQ
        dEhQR2pCNmhpQmJGd1RmUTExbXc3YnMKLS0tIFBWVlRmNHM4czBXOWx5Q2E3YURl
        S09MZWhqT2VSREVsMGV3cENOci9HM0kK7PsHZYh82gFR688OjNIQGmaD2UkWD4N8
        QvndFgzE1C57tSEj5yHQN2gdlkMYVN+kqUlqmdCeQ5gFXSxc9YouIQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRkZ0Z2ZubEt3Q0ZsKzIv
        QmZ5OXZlRkFSRkJZRjRDV01MbFZVNUhBS0JnCm5ocDE2K1dTRjQyb1o5dlhHNE4y
        ditneGxjY2lhUTJ6Z1ZSWFYrdVN1a1kKLS0tIG1ubk5tMFRZQlFjMWExN2lKTVBi
        UUl0MTZncjNVNzV6T2hhMm00U1RQZjQK6+VdvAa9PNJh4D0jys5TTnDfxwpDAgHm
        O8cAVzW3Xd4HDVZc8o91zNJofd0BTArobiuIKI1TASlDfRkH/3m6aQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-13T01:15:11Z"
  mac: ENC[AES256_GCM,data:a2Zdq3nk0UItjBsWIg/ePBGmbcJSZz3tae14AL7gXrfnxlJG60DoDgganXGCkvKG6uI87864h/q6rcN+gGmOupL1VV6ol8OmOA7YW49WPW9nBsDUbFlIQQHFYF+N/34AeU4hLYMSxwxJYg8klWWy0kEQpFSYVacccJy3oWvKQOA=,iv:xIkw6xoZ1CIRvXxT7VpaDmrdKPrcAHuXNmr/3vaqrSw=,tag:tgDuA0mJVJsdkZfZGWriHQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
