apiVersion: v1
kind: Secret
metadata:
    name: public-coder-devbox-ssh
    namespace: public-coder-agent
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:C4ndmasgPNWa5zO5rHd4ojD4Tl/uq7yZIs3miHHafpqjOdCox9mjfRMRj7Q3TBA76Ut/rS0wXDL2L3bF/8Z5XFqAJQWcaB+WvfU7BOHHBse/gvfcSlMrwpgag1i3Rp5C79YFAAKBFiAskYh/dp3xEvJ0Kju8sPilYwUi6TPhf0ONU6276yHNcLFuxGy3wOvp3BXn8rB1b7DdUu3Cq1fj9Em3osJHhCMOgOZGauU/aDdhtcclH2D0crf0AW05RI4k0FePq6RjLATEvXpyoY0M8u9B5m7CgT1QzDCOZEf/wyKm/6BlGyCZcwfHMk4oWVy8xK4Ax77r2Po96tOAJu2USyVdowc3J3V2UbJgeRFn3pqBOx2r2oyew4qtQ4nc2EaDLKp3/4ipTAU107iNs278eI1oJzRe5AurEzTtFv1AOramgTp+YMIHy30VxgnuN2a/APC3LkEDOl/qdOERvQtzfFsWaPPVoD6kKpeNwAT54iNTqxrLkno/WqcPfDGrZG9RB1zp9Nli3aMZCdNKY+yt0kcnXJxD6p27jgtTiW6DgCQJOpuncAFHDmv4VX3QhwmFz72Q4A3b3NcUDFfA,iv:tEOiqgLMMUvWYA93lg1FlMMtDWIjwXwHW+ki6PtX8AM=,tag:aSQPFEJtRfLbTkTWUxOVCA==,type:str]
    known_hosts: ENC[AES256_GCM,data:qgHJc6Yt77gENF7K1vPocgcAajXSlozyJrKVjljqbXRAXXHttyS7Wk93rpkbQ6c7AtULfQD3QkU4METMaf1U5Fo50jSzZMaPIIqDofqhW99kSJikh+uPgXsqQLN+vJG6On/i8s4jgL0gYd7/xmbANuBags2Pub16j5HbYIVasakRNGKBkyGwlpsjjc1GIM6s+lJC8twbVdjAEMlA/JFDTGj84atXhd4=,iv:1pWbIzxUT8n0GtquGNqgONB5M9290Ktkspq31kB7Btg=,tag:b47nOVAKWWY6BekX3+E6cg==,type:str]
    config: ENC[AES256_GCM,data:RYRlvQM6VfcOBZSErVXwnHVZ42SIc5kH+Zc+WNJPG5FyjbPCCxrIYIAijspCrpGeLiBOan+nwg311PY48vwbSBtkZogjX7g+7ZHfo69je8741Tjpe6MXjOgLCyXc5+Wz3YsQQmERuJ7yAPUBtW8IKgMwnsfxaPycCYTawHHSxELTCOuE4O4Y2HmAeCFAq2a6/7UVYO792wKxaTEezaFRvMQbgm5qfWPY/r2kPI7+X3/igsRcSRxhfwp21O8Lg27hOycp8uxUBlXjqTut7tjxn1rIIohgEG1BKYIaCaxXGN1t2M9NtpfHaMVR1QCRlqYMuvVjJmkVheQ036Eft6ey3FJtQEmLy3n56g4=,iv:Oj6iTciCeQNb2g8Lgc2qdawyjwCrR/2oUtFiuMJng+M=,tag:n3eq4fWjj73NHxFUlCiyEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTUF0VkMxWGRBMHhONEVn
            aHQyaGtOR05tV0wzTDV0WmcvKzVZVG5DTVJnCmwxc3FJZDRMNGx4VUF6ak9NcUI1
            cFpqbGpmbVhHRk1aaTc3QW5za0tDMFEKLS0tIDJoa0NrRGVFS01Xa2ZRcm5CMzBF
            amZyMlJUMVVhZ3JEYU1lNS9Mc1hoMWsKlrzyWxXbTpbnXL6xl9XF/GdE37ih03pv
            c8kIQ9v06vtj82J/r5f7irz9VuCdGpN0SQnzA6TJfrpHBooCgzhIUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eU1lYXN5QUVSdkFzeWlE
            L0p3a1Q3R2tuNDk2NnhuVnhPZnlxS1UxVlg4Ci96Z0xwajZxVEtWZWZMcVFNOEVt
            NjJDWVdPVkF4NmtIeDkwOC9ZUE8xV1kKLS0tIDFVZEozck1IWmgwQ01ua1JDSzZv
            NEpiRDhOYXdrWEtBdHNKWWN5eG9wMVEKZ1KybqsWQdUnzyarCbXJjocyBroeKPj+
            F7HjZATVUhdVXVceOolPyOR/rQVZA1px+5PcxrPVoDVBzpLKxBXbEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T07:51:36Z"
    mac: ENC[AES256_GCM,data:3z4/BcnDekFPSBGok+xHwrJcCo4dqVYMRKa2biMHPPzyhWVbhrdhGQMqhbq1eOAvZlQ0qT1yIQNVyq+Dt0dCeBmw7VHyjblrPhZzoFI4cpdsYqi0zl8+Kb34R8AVy6yXeKu4BA5hR9UA2QvegF7kHJCMjMXKaJEjbZzszzfcFYo=,iv:iydEjhIbOZyhODG6JeAfukPPATyumoPYqc4NnVrY3ik=,tag:H5HgTQ6UUKsYCzdCqRM6lA==,type:str]
    version: 3.13.3
