version: 1
metadata:
  name: SSO - Gatus
  labels:
    blueprints.goauthentik.io/description: "Gatus proxy provider, application, and outpost"

entries:
  - model: authentik_providers_proxy.proxyprovider
    id: gatus-provider
    state: present
    identifiers:
      name: gatus
    attrs:
      external_host: "https://status.allegedly.works"
      internal_host: "http://gatus.gatus.svc.cluster.local:80"
      mode: proxy
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      access_token_validity: "hours=1"

  - model: authentik_core.application
    id: gatus-app
    state: present
    identifiers:
      slug: gatus
    attrs:
      name: Gatus
      provider: !KeyOf gatus-provider
      meta_description: "Gatus Health Monitoring"
      meta_icon: "https://cdn.simpleicons.org/statuspage"
      meta_launch_url: "https://status.allegedly.works"
      open_in_new_tab: true

  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf gatus-app
      group: !Find [authentik_core.group, [name, authentik Admins]]
      order: 0

  - model: authentik_outposts.outpost
    state: present
    identifiers:
      name: gatus-outpost
    attrs:
      type: proxy
      providers:
        - !KeyOf gatus-provider
      service_connection: !Find [authentik_outposts.kubernetesserviceconnection, [name, Local Kubernetes Cluster]]
      config:
        authentik_host: "http://authentik-server.authentik:80"
        authentik_host_browser: "https://auth.allegedly.works"
        kubernetes_json_patches:
          deployment:
            - op: add
              path: /spec/template/spec/nodeSelector
              value:
                topology.kubernetes.io/region: hetzner
