apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth-broker-secrets
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/k8s/oauth-broker-secrets
  prune: true
  wait: true
  dependsOn:
    - name: oauth-broker-namespace
    - name: sealed-secrets
    - name: external-secrets-config
