---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plaid-client-credentials
  namespace: oauth-broker
  annotations:
    description: Plaid API client credentials
spec:
  encryptedData:
    client_id: AgCYzxdTEHZOSx5WODPVCJQbvKQzwjeT6U5WUopaX3eFBvxUIuGOGZEBZC3bN4YgLUpf3qDlTD96sNkXjH0yb7OnZy+vWY99htf/a1ukZlKFlJ3hEXMt0W7d77wHJwgKrUe8PaCjRntw1DQun3I3UkNMdfYnAybb3fV9rLBzUrGnPFb8SlCzBhFyf5RroYqI8MJML9GzB+alvtjKYKxL9Io0QhOl7grA127w/BcUV+TH+hvlZL3flp61ZvJyPU3u8NRzv9zudD9hdySNsUnm5p/Y0fS93flmJnPjXpCqYMTIyMOp4yLrvgNhV+WUcIpiBnlItxY7rGg4DMiwb1V8p84s60Q74X2AZrAsOE5MJdaYhv5IOQHSuKsDb+iRCfWN+f7upOulpkH/Kxfzu6DO69yclaiaPWLqO9o8QQ/TyVRAsd6XeiT4My5TT2zREiGx6JfWUuzWSyJO/isiShYzuEsYYGf2VvAkwWJ/FSneCrqoqkreneEQPTx/IKijqBFMLtXJTwp8Yi5qnq/k+MlIBcONAk3R0iFKFLwoYmmCXP/Gyvbh+qW/N4ajjrjuzpCuQmJBc12+mO81hBl1h5nZNnYymAt9r+xcDikS2y882bTMz5UoEyQ7WBrr4+u7qtszRMWhLIP+h8MReS8b4WrES7Dmcz+uXG/JTkzOkJBKtrcoDNG79rtkkRvZ+mu13B7Dw0qBnwR4wQA7GF1Rfjc7q4qH7/6t/dzyfsg=
    client_secret: AgDEtwWhSK6297dvA8nn/OHNirPArUeFWQECQYCq2ycUpSChWAgbAEjltkWIXzHdMmmVkKMB9Eb2cuOt40SGpwrPCxKyjRuuJ8yviuZ2Fk7as1Uj691g2yiKSfGZXIw3bp3xh8PLJZM5eXVRvUoL3XUvVKCbK6H5cmlKCL0vBVJWkMjBB7jGidEvr9vbvvIS8YACxTMP5BP9O7en0ChPDpWTgOU5rvhdP0hSq+/W6Z3+VuMyjYDzYtuA7C0S8dD8RNFqC2PbXopXb070GS9OIQmmC7zJsYkZDrzu/qQtbIRbtemZrNeSju0KrBMsziaBQpcPOf913JGK5YgKG14v5FTG8ONipRJ9DRy5cNsF+FeOb5PoY9Hf/2qGflv+RV1FVo6JZ+Jxs8914yPcscbRMqOGHggcBavHN5RRNL0QA401uDvjYidXWw/BmZLd1Ay9LJbJPLxGaPEsot702sbsw4bdhzigGJbmopZGoB53J61T0/O2hluHeZLgy+jpgku3r9NrSB2sEUAc6uZk4KpR+f+UouY8LUlF/OICxCpqwJsBGEkQP8jkaoauxBR0M44gMDv8DgYu0Pz0/e7GevCFGY3Bis+VVJN4iXAjvgDBj6C39E6Q0bRsovxMjJqHSjvaW7NUpH+dFf7RMhX88+q7+1J86qUZzB6wJkD/v8t8g6HceWmvFvD0Y9rYtfBmwBYbi9ngXyM8PxxOqpTgOJymz3p0WIjtVGbUfGIVs2TStSw=
  template:
    metadata:
      name: plaid-client-credentials
      namespace: oauth-broker
