apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatus-secrets
  namespace: flux-system
spec:
  retryInterval: 1m
  interval: 10m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/gatus-secrets"
  prune: true
  wait: true
  dependsOn:
    - name: gatus-namespace
    - name: external-secrets-operator
    - name: external-secrets-config
    - name: authentik-blueprint-sso-secrets # gatus OIDC secret written to Vault by sso-secrets terraform
