apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: gitea-admin
  namespace: flux-system
spec:
  interval: 15m
  approvePlan: "auto"
  path: ./cluster/terraform/gitops/gitea-admin
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  serviceAccountName: tf-runner
  backendConfig:
    customConfiguration: |
      backend "kubernetes" {
        secret_suffix    = "gitea-admin"
        namespace        = "flux-system"
      }
  vars:
    - name: vault_address
      value: "http://instance.vault.svc.cluster.local:8200"
