apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    goldilocks.fairwinds.com/vpa-update-mode: "initial"
    rbac.ducktape.io/agent-namespace-diagnostics-reader: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
