apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-harbor-oauth
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: authentik-harbor-oauth
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      key: kv/data/harbor
      property: client-secret