apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc-secret
  namespace: harbor
  labels:
    app.kubernetes.io/name: harbor-oidc
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/component: oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: harbor-oidc-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        OIDC_CLIENT_SECRET: "{{ `{{ .clientSecret }}` }}"
        HARBOR_ADMIN_PASSWORD: "{{ `{{ .adminPassword }}` }}"
  data:
  - secretKey: clientSecret
    remoteRef:
      key: kv/data/harbor
      property: client-secret
  - secretKey: adminPassword
    remoteRef:
      key: kv/data/harbor
      property: admin-password