---
- name: Check if tankshare is mounted
  ansible.builtin.stat:
    path: /mnt/tankshare
  register: tankshare_mount_local
  tags: [storage, docker]

- name: Ensure tankshare is mounted
  ansible.builtin.assert:
    that:
      - tankshare_mount_local.stat.exists
      - tankshare_mount_local.stat.isdir
    fail_msg: "/mnt/tankshare is not mounted; aborting."
  tags: [storage, docker]

- name: Expose tankshare mount fact
  ansible.builtin.set_fact:
    tankshare_mount: "{{ tankshare_mount_local }}"
  tags: [storage, docker]
