apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: gatus-sso
  namespace: flux-system
spec:
  interval: 15m
  approvePlan: "auto"
  path: ./cluster/terraform/gitops/gatus-sso
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  serviceAccountName: tf-runner
  backendConfig:
    customConfiguration: |
      backend "kubernetes" {
        secret_suffix    = "gatus-sso"
        namespace        = "flux-system"
      }
  vars: []
