# Generated by cluster/cdk8s/litellm/keys.py into the litellm-keys Terraform CR.
variable "model_lanes" {
  description = <<-EOT
    Policies keyed by client-lane identifier (not model ID or provider). allowed_models
    contains exposed LiteLLM route IDs that keys consuming the lane may request; a key
    may combine several lanes. fallback_models is the ordered target list for the
    lane's team-level wildcard router rule. Fallbacks must already be allowed: they
    do not grant access. An empty list means no configured fallback for that lane.
  EOT
  type = map(object({
    allowed_models  = list(string)
    fallback_models = list(string)
  }))
}
