load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//cluster/kubespand:upstream.bzl", "TALOS_CONTROLLERS_KUBESPAN", "talos_copy")

talos_copy(
    name = "peer_spec",
    src = TALOS_CONTROLLERS_KUBESPAN + "peer_spec.go",
    out = "peer_spec.go",
)

talos_copy(
    name = "endpoint",
    src = TALOS_CONTROLLERS_KUBESPAN + "endpoint.go",
    out = "endpoint.go",
)

talos_copy(
    name = "routing_rules",
    src = TALOS_CONTROLLERS_KUBESPAN + "routing_rules.go",
    out = "routing_rules.go",
)

go_library(
    name = "kubespan",
    srcs = [
        "peer_spec_filters.go",
        ":endpoint",
        ":peer_spec",
        ":routing_rules",
    ],
    importpath = "github.com/siderolabs/talos/internal/app/machined/pkg/controllers/kubespan",
    visibility = ["//cluster/kubespand:__subpackages__"],
    deps = [
        "@com_github_cosi_project_runtime//pkg/controller",
        "@com_github_cosi_project_runtime//pkg/resource",
        "@com_github_cosi_project_runtime//pkg/safe",
        "@com_github_cosi_project_runtime//pkg/state",
        "@com_github_hashicorp_go_multierror//:go-multierror",
        "@com_github_jsimonetti_rtnetlink_v2//:rtnetlink",
        "@com_github_siderolabs_gen//optional",
        "@com_github_siderolabs_gen//value",
        "@com_github_siderolabs_go_pointer//:go-pointer",
        "@com_github_siderolabs_talos_pkg_machinery//constants",
        "@com_github_siderolabs_talos_pkg_machinery//resources/cluster",
        "@com_github_siderolabs_talos_pkg_machinery//resources/config",
        "@com_github_siderolabs_talos_pkg_machinery//resources/kubespan",
        "@org_go4_netipx//:netipx",
        "@org_golang_x_sys//unix",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "kubespan_test",
    srcs = ["peer_spec_filters_test.go"],
    embed = [":kubespan"],
)
