cargo-features = ["edition2024"]

[package]
name = "ducktape"
version = "0.0.1"
authors = ["Rai <agentydragon@gmail.com>"]
edition = "2024"

[dependencies]
log = "*"
env_logger = "*"
rust_decimal = "*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"], default-features=false} #, features = ["full", "time"] }
serde_path_to_error = "*"
# native-tls makes trouble
reqwest = {version="*", features=["json", "rustls-tls"], default-features=false} #, features=["json"]} # , "serde_json", "tokio-rustls"]}
serde = {version="*", features=["derive"]}
url = {version="*", features=["serde"]}

serde_json = "*"
toml = "*"

# worthy
chrono = {features=["serde"], version="*"}
petgraph = "*"
chrono-tz = {features=["serde"], version="*"}
#tokio = { version = "*", features = ["full", "time"] }
warp = "*"
futures = "*"
rand = "*"
base64 = "*"
openssl = "*"
jwt = {version="*", features=["openssl"]}
sophia = "*"
sophia_term = "*"
rusty-money = "*"
serde_yaml = "*"
structopt = "*"
xdg = "*"
alphavantage = "*"
shellexpand = "*"
coinbase-rs = {git="https://github.com/agentydragon/coinbase-rs", rev="01cabaa6fdd0fed87b44b38f218b1068f4914b39"}
bigdecimal = "=0.3.1" # must match coinbase-rs dependency
currency_layer = "0.2.0"
serde-xml-rs = "*"
async-trait = "*"
rust_decimal_macros = "*"
regex = "*"
term-table = "*"
uuid = { version="*", features=["v4"] }
glob = "*"
csv = "*"
oauth2 = "*"
biscuit = "*"
ftx = "*"
headless_chrome = "*"
scraper = "*"

[[bin]]
name = "ducktape_fake"
path = "main.rs"

# Only generate BUILD files for Linux.
targets = ["x86_64-unknown-linux-gnu"]
