apiVersion: v1
kind: Secret
metadata:
  name: haku-forgejo-tea
  namespace: haku-sandbox
  annotations:
    description: Forgejo API token + tea config minted by forgejo-token-rotation.
type: Opaque
stringData:
  config.yml: ENC[AES256_GCM,data:ain/EjbPklrxo61hpvGgsz5HrzEHhCEA1Nh2OjVIEitsjv3hFFDIhYT9yCmBeks+OZaFZDcACUVAXhG9qFa5prsUv3FJ7Mwth47F842Mvyg0BOE+Co2llSjq9d6Vtp+HV6Ps9S2RLe8NVWc8qu2IJLHHim8eYB91VAGc70WvNdAToKImp0bGMOqsEqCgsyyeEI9UiRkt9SvzszxQ5M4/FvY=,iv:ICg19djX31YVGA9v139FJ7fmPvajYQ/LvBU5E1ybRDQ=,tag:MaZqCMTMxYVhteNrWuBAGQ==,type:str]
  token: ENC[AES256_GCM,data:rCNklOcBE3bhb5MRgykE6Z1aDTCd71157yJ0YAtJEEmUHZu5BtK9rQ==,iv:OFbdJNkeiSGBTR5xwnU9FoNUhOAxuNSZOtXq74Q8F0g=,tag:bacWNATl1UHlhmq4iR44FA==,type:str]
  username: ENC[AES256_GCM,data:/Hvr9w==,iv:zgASBBZYY8rAb5x7zsUY74l+MGOKlJg0lyOoPEM7vYk=,tag:yUO9EQ/xAfwhkmaaVUuJhg==,type:str]
  url: ENC[AES256_GCM,data:6/2hhwWmB+jylFQCcWEJq7Bm3P8sjHc569p8,iv:ogmyVx7P+OiQbEOuZD9uY3UB5/3+uasbnOJj07bg9fs=,tag:xIYTtku/HDnWWSQK1vcmxw==,type:str]
  token-name: ENC[AES256_GCM,data:T9oF8OZoY4AvvRgj05bOtlEZtq7iXNFDkNd65+bvQfEFGMZYAQ==,iv:2shQFrIp3whUtpAMKc1ZYOlJIY3pDaoLqtcn3yEB6cU=,tag:KeO67SqU3t+ZSYu0suee8g==,type:str]
  token-last-eight: ENC[AES256_GCM,data:3Bm9TYGe3Lc=,iv:vShY9xLvQzACsmNawQhr02apVHoHxoJ+2aOcVO4HfkQ=,tag:RWUq/y5qTxugs+j3O0qebA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK2JHdVphNWNLazEzYmF0
        NDNjWGIwL2tLMGt0dGc3Z1JNY2FXejJTSW1VCkRZMzJlQnRtTFRMejhnV1BNdHFk
        c1R6akNtaEVBbWRTVHZUeVA0WG0wZzQKLS0tIFhnMTFSV2VwWkxRNGFzKzkyRGc4
        TXM3N2RudWpiQloxWm1CSC9hOG1Pd2cK52GBbQ4bHuO9q2+Mi/8PleqsA5RRGpMN
        axjSMH9z1rQpbYuppWWMwtZgKBINdfw3+EfV6flBuMILq9fb+XViBg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1d2o2Qjh2eE9XUUhMYVBr
        eldVdUE1NUYzTDFOYXJsdU52OWtpUmg1RFMwClh1Z1JraVovZWxGU1d1U2FPS21K
        VkY3dmZUTFJYMTlhN20vMVBtaVFaUEEKLS0tIEdpcU8xL01tUWNEQk1kR0lIaUZt
        MkJaa1E5L2kySE9vNzAxNTl3a0JDeU0Kk6AdgY+M7ek8z0IfJIdifGwI3jtGrTbk
        7OkP8uhq1Mk5oRtvswdSgEa7PquUtoeAPzQPAUIoUIQ8oDA3VB/cNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-04T02:35:08Z"
  mac: ENC[AES256_GCM,data:oyCOJbty8pAmXpLb+YEOK9sVXP4y6H8WUZvIH67wtNV2Lxenhe8iR3n7/STiyJ6dwdgAso3wJPZCMkZJgXRmAwgxhr/WpEp0dxB/Ls5W4ZNp81uvqYqQMtOekyEHvRRf86z3nqu2NoKmmdwVjUR3KL882WncWkpqMdRcToxyr2c=,iv:gvUynzB7i1eDzVif3vY+WPGve0g+MGVpa9CIw9A0AM8=,tag:DkPGYNhuakmd+1KxHKBAXg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
