load("//devinfra/python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "capture",
    srcs = glob(
        ["**/*.py"],
        exclude = ["tests/**"],
    ),
)

py_binary(
    name = "live_capture",
    main_module = "x.agentplane.capture.main",
    deps = [":capture"],
)

py_test(
    name = "test_records",
    srcs = ["tests/test_records.py"],
    deps = [
        ":capture",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_replay",
    srcs = ["tests/test_replay.py"],
    data = ["//x/agentplane:native_capture_examples"],
    deps = [
        ":capture",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "test_proxy",
    srcs = ["tests/test_proxy.py"],
    deps = [
        ":capture",
        "@pypi//pytest_bazel",
    ],
)

test_suite(
    name = "tests",
    tests = [
        ":test_proxy",
        ":test_records",
        ":test_replay",
    ],
)
