load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//cluster/kubespand:upstream.bzl", "TALOS_CONTROLLERS_NETWORK", "talos_copy")

talos_copy(
    name = "nftables_chain",
    src = TALOS_CONTROLLERS_NETWORK + "nftables_chain.go",
    out = "nftables_chain.go",
)

talos_copy(
    name = "address_spec",
    src = TALOS_CONTROLLERS_NETWORK + "address_spec.go",
    out = "address_spec.go",
)

talos_copy(
    name = "route_spec",
    src = TALOS_CONTROLLERS_NETWORK + "route_spec.go",
    out = "route_spec.go",
)

go_library(
    name = "network",
    srcs = [
        ":address_spec",
        ":nftables_chain",
        ":route_spec",
    ],
    importpath = "github.com/siderolabs/talos/internal/app/machined/pkg/controllers/network",
    visibility = ["//cluster/kubespand:__subpackages__"],
    deps = [
        "//cluster/kubespand/talos/adapters/network",
        "//cluster/kubespand/talos/controllers/network/addressutil",
        "//cluster/kubespand/talos/controllers/network/watch",
        "@com_github_cosi_project_runtime//pkg/controller",
        "@com_github_cosi_project_runtime//pkg/resource",
        "@com_github_cosi_project_runtime//pkg/safe",
        "@com_github_google_nftables//:nftables",
        "@com_github_google_nftables//expr",
        "@com_github_hashicorp_go_multierror//:go-multierror",
        "@com_github_jsimonetti_rtnetlink_v2//:rtnetlink",
        "@com_github_mdlayher_arp//:arp",
        "@com_github_siderolabs_gen//value",
        "@com_github_siderolabs_go_pointer//:go-pointer",
        "@com_github_siderolabs_talos_pkg_machinery//constants",
        "@com_github_siderolabs_talos_pkg_machinery//nethelpers",
        "@com_github_siderolabs_talos_pkg_machinery//resources/network",
        "@org_golang_x_sys//unix",
        "@org_uber_go_zap//:zap",
    ],
)
