load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//tools/lint:linters.bzl", "ruff_test")

exports_files(["pyproject.toml"])
py_library(
    name = "rspcache",
    srcs = glob(["src/rspcache/**/*.py"]),
    imports = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "//openai_utils",
        "@pypi//asyncpg",
        "@pypi//canonicaljson",
        "@pypi//fastapi",
        "@pypi//httpx",
        "@pypi//openai",
        "@pypi//pydantic",
        "@pypi//pyyaml",
        "@pypi//sqlalchemy",
        "@pypi//typer",
        "@pypi//uvicorn",
    ],
)

py_binary(
    name = "rspcache_cli",
    srcs = ["src/rspcache/cli.py"],
    main = "src/rspcache/cli.py",
    deps = [":rspcache"],
)

ruff_test(
    name = "ruff",
    srcs = [":rspcache"],
)
