---
- name: "Apply profile {{ profile_name }}"
  ansible.builtin.script: >
    apply.py
    apply '{{ profile_name }}' "{{ dir }}"
    --font "{{ font }}"
    {% if debug | default(False) %}--debug{% endif %}
  register: apply_result
  failed_when: apply_result.rc != 0
  changed_when: (apply_result.stdout | from_json).changed

- name: Debug stdout
  debug:
    var: apply_result.stdout_lines
  when: debug | default(False)

- name: Debug stderr
  debug:
    var: apply_result.stderr_lines
  when: debug | default(False)

