---
- name: Set default variables
  set_fact:
    font: "{{ font_family }} {{ font_size }}"

### One way to run this without requiring root -- but with slow fact-collecting:
# - name: Collect installed package facts
#   ansible.builtin.package_facts:
#     manager: apt
#
# - name: Determine missing packages
#   set_fact:
#     missing_deps: >-
#       {{ desired_deps | reject('in', ansible_facts.packages.keys()) | list }}
#   vars:
#     desired_deps:
#       - python3-gi
#       - gir1.2-glib-2.0
#       - git  # for cloning the theme; TODO: use a submodule or something
#
# - name: Install missing dependencies
#   become: true
#   ansible.builtin.apt:
#     name: "{{ missing_deps }}"
#     state: present
#   when: missing_deps | length > 0

### A bit annoying but does not need full package state so faster
- name: Check for required packages
  register: pkg_check_results
  changed_when: false
  failed_when: false
  loop:
    - python3-gi
    - gir1.2-glib-2.0
    - git  # for cloning the theme; TODO: use a submodule or something
  loop_control:
    label: "{{ item }}"
  shell: "dpkg -s {{ item }}"
  ignore_errors: true

- name: Install missing dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ item.item }}"
    state: present
  loop: "{{ pkg_check_results.results | rejectattr('rc', 'eq', 0) | list }}"


# TODO: fontconfig is needed for fc-list
# fonts-ubuntu

- name: Check {{ font_family }} is installed
  ansible.builtin.shell: fc-list | grep -i '{{ font_family }}'
  register: font_check
  failed_when: font_check.rc != 0
  changed_when: false

- name: Create temp directory for gnome-terminal-solarized
  ansible.builtin.tempfile:
    state: directory
    suffix: gnome-terminal-solarized
  register: temp_dir
  changed_when: false

- name: Clone gnome-terminal-colors-solarized
  ansible.builtin.git:
    repo: https://github.com/aruhier/gnome-terminal-colors-solarized
    dest: "{{ temp_dir.path }}"
    depth: 1
    version: master
  changed_when: false

- name: Apply Solarized profiles
  include_tasks: apply_profile.yaml
  vars:
    profile_name: "{{ item.profile_name }}"
    dir: "{{ temp_dir.path }}/colors/{{ item.variant }}"
  loop:
    - { profile_name: 'Solarized Light', variant: 'light' }
    - { profile_name: 'Solarized Dark',  variant: 'dark' }

- name: Set Solarized Light as the default profile
  ansible.builtin.script: >
    apply.py
    set-default 'Solarized Light'
    {% if ansible_verbosity >= 1 | default(False) %}--debug{% endif %}
  register: set_default
  changed_when: (set_default.stdout | from_json).changed

- block:
  - debug:
      msg: "stdout: {{ set_default.stdout }}"
  - debug:
      msg: "stderr: {{ set_default.stderr_lines }}"
  when: ansible_verbosity >= 1

