# Expects:
#   visible_name
#   profile_name_to_uuid
- name: "Ensure shell profile {{ visible_name }} exists"
  when: "visible_name not in profile_name_to_uuid"
  block:
    - name: Make sure Python is set up for Gnome Terminal theme setup
      become: true
      ansible.builtin.apt:
        pkg:
        - python3
    - name: Make UUID
      ansible.builtin.command: >
        python3 -c 'import uuid; print(uuid.uuid4())'
      register: uuid_out
      changed_when: false
    - name: Bind returned UUID
      ansible.builtin.set_fact:
        uuid: "{{ uuid_out.stdout }}"
    - name: 'Set name {{ visible_name }} for new profile'
      ansible.builtin.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:{{ uuid }}/visible-name"
        value: "'{{ visible_name }}'"
    - name: Append to profile_name_to_uuid
      ansible.builtin.set_fact:
        profile_name_to_uuid: "{{ profile_name_to_uuid | combine({visible_name: uuid}) }}"
