apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
  annotations:
    description: Proxmox VE API token for CSI driver (kubernetes-csi@pve!csi)
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:mlpg5sb8BbNk8TCXxCiG09Tx0d8Qk4dIj5geUoBuKUF9e6DioyFWfvGg/yvOck5EAEBC+RpF//OF/V7WWsgtI9sT+Fyw85/PPeU1LcoBgZG5VYYwc4X352KnnD8uVwqZ5ou4xij0Hpvm75vVIVEVfB+htr1bc1f1vqVv,iv:oPG/4vMs3HFxIDxpnyMD1lxCSZwzchHdRdJQdIkROBY=,tag:HbbAonYKl3UFJEj9mdTNYA==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUDR0bmdjVUc1UlIxdmtq
        YVRtSHZJZ1NKTVd2V0VCVERJbW1aRnNtbkdZCmIvTHhUaWFrS1h5RGZuRHRtcVg2
        TkpMSVZnaHkzeGliRldaY2MzNVljMUkKLS0tIC9CT0JyTWNCK21Vb2pjVTZGeDRH
        aVJlSzA5L2t4MkZRendTUHlGNU9rYlkK3pJ8rsehzMLQ3jvWLenJgeMljqAoN2rW
        OZCxr2+thbdajeqKu4BvBA19SccbjhtY4Bef5WNYMPbFpoMbh1477g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTFBVWDFOVVNPYVBWcDZ6
        MlFidjRTNEllRVJ2U3RZb0ZFUGhhRlM4Rkg0CktpWkw5VHg1a0I0cjZJakNKWHl0
        aDRKS0J3S2lwZWp5NzFpK2hVL29DTDAKLS0tIEVHWlRrVnYrVUw4WmxPcnk4NUhO
        RDZtenpRa0FpcEFPaDhjcDVGY3U4Z0EKoNJ1+Yci7iZgv8G2vSFLPXazYZD7tGcG
        sUW3rs2X/B+3meC3vOzgEGaq7fKDzCHpytV6/khOvn737eoQHX/ryQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:19Z"
  mac: ENC[AES256_GCM,data:kQxpKQM2N5xVB/JLLzjRSpzt5kBVlfPtqTGcbGWD4RRB4gvMhkGnWXgtuOqiWnkF52fvM++n+snQdcQPecZiRCyKmR/ZC6eGh5VH+ajczFPpvMeGrs5RjrcF2yxgz+snTrwQImpy9wIfWc1JkGwCTLpvfuVO8wyciClsx3AOsC4=,iv:ky/5A2ve5kB6qMPWxzkvpQwTTz5rk4Ze4ze1NuqNmlg=,tag:QEMCZ9sriLjqUbB1IEbilA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
