apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-gateway-token
  namespace: openclaw-sandbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-openclaw-secret-store
    kind: ClusterSecretStore
  target:
    name: openclaw-gateway-token
  data:
    - secretKey: token
      remoteRef:
        key: openclaw-gateway-token
        property: token
