apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-runner-serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - docker-storage-pvc.yaml
  - node-runner-deployment.yaml
  - node-runner-service.yaml
  - cnp-openclaw-ingress.yaml
