apiVersion: v1
kind: Secret
metadata:
  name: tempo-minio-credentials
  namespace: monitoring
  annotations:
    description: MinIO credentials for Tempo trace storage
type: Opaque
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:6FuaamRtGy7fvQ==,iv:HxH7NFoo/W5fzcOjMqQD3YxSU2rME3RsIL4BdELhwEg=,tag:DVDlaoxffGHQX3rEjEEAdA==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:6vgJd8DkN1Tg0/qbvIBcCpYh/midXsM5BiKAhganoUEheZgi3zWnGTx5zQ==,iv:kvzbLHHj1AZbd8cV6mIaxWJgfG/w7JWk2/AEcIrgvf4=,tag:lROf/HkTbEPRxh/q0XvX/A==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3THhXUDhFZGFsWkkza0VQ
        bG9XSzZMdWhRZGRVMmN2Zkd5NGJOazNHVkNjCndXa2ZZdTVzb29TLzNtWmxCeURI
        STNsb3VJYlBvNGdmSlRvYXA3VTM5cWcKLS0tIGVFMGE5Y1FNTklnSVNSY2tHYmVw
        UXYyb1pHaUZxN0tTOG8xNUk0aWhHdFUKESx2HZYK0phVXDna9C4dhP9h/+sC1uOh
        9MwBaDwEBgtnVraKSFVF48EqOHR17QPtM6FceXxXwCm3Rer/7/M/tA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQjAxZ2xJS2toWElSTnFB
        NHJ4d0J3TENkdGRMb0Q3bXZSSVpweEo1M2lnCmtOSEdsRkdGdzhkQVYvdGRIb3By
        YTVVVzZMb2F1VEx6M1c2OE0xZjRxSGMKLS0tIGJGNXd4c1lpTTRCYW0zbFo5d05n
        RkYvOVd4TFpDUFpRU2xoSWYrTzNHRncKDZ85BfUqMCIlMr/ZMyjMXKQGRoAwLHOJ
        Dco627vKBXQ0WCJ5nv/tpM3Pp4hiXh8jY323h4DMIe5a4jgMo8D90g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T00:05:38Z"
  mac: ENC[AES256_GCM,data:CcL60E1Vx913g+R49HfYEZZst0yjX1983cUv6idmBEM258bGvBMO2ry4s4LTpMt7CPifCXjbz5ayecMpPw6RQXrFhvHZhbmUfqL1RhkkMqjlTjrF084h4J0p2xZIgmSmScFxvafASMfMoaam2sMYBIpXLacpnuFiQp2r4iavn/E=,iv:AKHlbsfLywGMpXFnNGCpmis6TK2eDaz9PzC5dnzniKs=,tag:AZaWX2nj8HVY8nV2aGT3Bw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
