load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "ghcr_push_lib",
    srcs = ["ghcr_push_lib.py"],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//util:crane",
        "//util:env",
        "//util:oci",
        "//util/bazel:workspace",
    ],
)
