load("//devinfra/python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "client",
    srcs = ["client.py"],
    imports = ["../.."],
    deps = [
        "//airlock/oauth:provider",
        "@pypi//httpx",
        "@pypi//pyyaml",
    ],
)

py_library(
    name = "sandbox_smoke_lib",
    srcs = ["sandbox_smoke.py"],
    imports = ["../.."],
    deps = [
        ":client",
        "//airlock/oauth:provider",
    ],
)

py_binary(
    name = "sandbox_smoke",
    imports = ["../.."],
    main_module = "x.plaid.sandbox_smoke",
    deps = [":sandbox_smoke_lib"],
)
