---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgBOHL2j692tPuErot6Im3AMK1hGvNO807ED3ojq5e2xVTlJ+gW699fR4PG5PuU5M40Gty3oJbVvdrgfCOsyGw43RmPH33RAxYIV5piipE6IJtwBaroyV2IbqR26c/yLbk+ZU47vLemK4SmTG+jkuCg6h9ICl6RBrdmU6XQD4Fwt6Lib2BQwHOWOyD6fxBl0D1cWAZzYHlFpTDga44yzIWuQZus3sYhWc0fKkzcMeNPmR1AYawiPJpC2WH/frjQ5FZuKO+YlxxbP9dKBX87mJWIrPNQSb2Y2MAijKqyu4ksaeBxd+vahhOjnkVVgJr4OzDQQghweFqu0Cu7dUmYfBibSCafasoiut8YEAsDPMcI1g1N5m2N2ZPlOp/pGUJEYsr2VlT7sBcKYsqf4bhrxuyiNSJ9kv/NrJJt3pwgKrlHBcMOaFGSfMgLsZoaaTsQj8o3XJRcRpI4CTUyUZGMCCpKPadOsfnknC/wrJ9m9gGFQGg8+Uc+IoCdFcNDRyjBSpAHIfyd126LJYRKvMwEWGqnxns3xfLxqHrUdDuQpIfA5LBQKSeQLmgQzSN2jmWW2zYGP+IcJ0jqBIhj3ATN7/LIw5B/whhH4yk6594LC+iWzOQQDBn559k5Nl3StTpIKICAa69AZX4USDwbUdevjTUYhAhYwi7zwvQyiWKoZRSUwYNg0XeFid2CWew/2sKAzeHOIoXQ95WJ1Hyfe/SVlj3SIuXU+HHRg9xgMHm5Qz+DJNkag5b4GNvfAUPEbrpIkPfV/blS0K09gVSWvVxmEq+GfvVtpKj8hzeiLLzcCpVb5b2u528U7HayzOt/b6aR8hLCRqPM8GHOTFu2DbGCh3qjKrz30zl6pncb1mU6Uo2e8t2JI0X5UtvbHn5pW+6k9WIfBoLLudqE4uc22u/gkQMLQ91/y66FsWOoCazWAYrZulqi35tMOeCgKi4EAGJmJy64=
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
    type: Opaque
