---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCViROsxHLRTMPJVq0CQtt7b52jNEehxeuemmJ78Df7VAqWZITnar4qVGsg3Ox5x9uPQKxiy8A1M1gVdB1Z89eAGCrfTwp3YZPyk0NLKnXAwK2JEKF3Mn828z4L1FbYqdfWYiwdXP5o4U3/jo4FRpcskGIHiHSt4P2ONmPG4+BTpPH5Ks3LDu8uMpwV//1DY5WmjCRNTCq6ZSF7uzsszjK7JALcN9AtyvsQ6zW5yCqAL/1PQ/5M4H22EAmD3U/6lo3g8nVbV+7B8amK76mwssDdm0oJoZaXbj9FhChs5YjnsZyChH+/ksbL5syRe3QAmGABBE78uAxmyRnCK7K45xJwlD3wflYHO6z/MMzF0efuqSF4dhk3y0fTaVVRMnJ3Xz0GsGfh/AjzDHkLQ892z57krwW+2Rv+lWE/n0zxx88ClwSEHBx+IcSDSiDCobFfqNr7c6YfwDqwdZMQJf1tPoqUHsLUDlcYlLHo7xeVSZWRew7jp99nasBvqMGrcF5N1nFGWaZLuFiEh5tVrn1GnC3WiQpPUnPAJemMTbulWJ30oYnSOQCKn3nCKAmtgyxBJnePzOcueqqBJvHW0LMFDpPJUgbjI+XTa0aaTXUPjzThQASWi4FQLXX9kWKNzV8pNrgtNVp28N5xlJfJ3Hnted+4go3FdVxJat3wgeN08+QC0x8GYmpo/6/2U9kjhK5WUK1tA6Jtfn3OAU0ew7HTGYkR+qMrI3pZlXkISb9pFmSZtjO9ehg0oqJyUR7HCLScdrCGTzQ7xMQnxdzLlit2i2jF+Cp9fZSnsDtkBgFcgxYt2wqhme85NMerf+Rz2zmhih+GMiykr5YIU27cB+hqZLHMvEdOoA37qwJSPvzfgrt7hlGXGr26/3YMWFvJIPEaGGdk8eREDgzw4hT+NHE=
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
    type: Opaque
