---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCRKa7/bUbXA3ims3kbiXNf5vsb+xuFieTKmbfoWN4u3XEiOQ7U3hJCNlg3RgIMokTYh6HXbuqsS0w7FAbHsbD9Kt57D2n0NxaF9II2TqE4APDkI1qAYmkakxunHstDVFKsMqidxHUXiNx1WX4YzzsTnYHytpywuMq22UGko3k2so3sVhTmio3JDcg0gIB30gkQsmq8DcQ2tlCvj+aVjdVo6MWuB+BWfdwbs6Zrqi+IPkfWfjKkxjwTq/rqp6f6isINk9szSfe16bjg+2esjw1Y6Nc49U9KOSLLonTgZEcJTzJU1o8cSjgGM8QcBAirU/VXRpZChePX4BmEqZS5uulPbeivWvaxPN5X62DyPK6eQH05rffM3yqJnQCXtvM/JQN2s0pMB6GxqlBDD6gKHBkKwOaZ1fBFpRyR6Cq09A1W+WgVYkUKmhws8C2v6Tntgyjxrv9n9XCP8RPowEb38c2D5/zC2rKnf6pdKN7lACmC9iTukee45XdnsJLtHeNagI+RmCO997GMm9V5LOqKM5b7eC0/ihR94U2BOT4Bbx5Sn9yUapCznZoWXgQoWkWOu+cCfLmxQerwUSdGez59Hjr7pNgzQNzEZMbXgVJPVqoMA5Kv+2P0lECAtZG4MTRawQ201aGYCTPKaDE60CK/pddWbNTDtxrkqk5tcB+yHFmXjc05N4I7NmbPbYLMFqOe+tHYjS/K+kQsKOxPgXF8ZImEiedmwuGHsIKjVg5NUUEqSmGTSOjkH5AOaCJIMUOo6OWTF44EmtTgsthX2fFmljr/4I6DulAlaLzHBpHAG9Fd22n0FdF39gTBWEUW7y5w1ODIlmbFpQAqYcQtc4GmY3J7v2FqG8ltRoojYPUzQBWMIossnHi7Hc636dgc4axqmaCiXZ0eO7xTCQWHjCsDr5TlG2W7R2KHvjPzy9a3cfVcOJVt7334rIQ=
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
    type: Opaque
