"""Network utilities package."""

load("@rules_python//python:defs.bzl", "py_library")
load("//tools/lint:linters.bzl", "ruff_test")

exports_files(["pyproject.toml"])

py_library(
    name = "net_util",
    srcs = glob(["src/net_util/**/*.py"]),
    imports = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//aiodocker",
        "@pypi//tenacity",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":net_util"],
)
