"""Network utilities package."""

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "net_util",
    srcs = glob(["src/net_util/**/*.py"]),
    imports = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//aiodocker",
        "@pypi//tenacity",
    ],
)
