- name: Ensure GNOME Shell extensions are disabled
  block:
    - name: Remove extensions from enabled list
      dconf_array_edit:
        key: /org/gnome/shell/enabled-extensions
        remove: "{{ gnome_shell_disable_extensions }}"
      notify: Restart GNOME Shell

    - name: Add extensions to disabled list
      dconf_array_edit:
        key: /org/gnome/shell/disabled-extensions
        add: "{{ gnome_shell_disable_extensions }}"
      notify: Restart GNOME Shell
