- name: install packages
  become: yes
  apt:
    pkg:
    - cinnamon-desktop-environment
    - curl
    - diffutils
    - fonts-powerline
    - geeqie
    - gimp
    - git
    - htop
    - iotop
    - iputils-ping
    - libreoffice
    - mc
    - mmv
    - mplayer
    - mpv
    - netcat-openbsd
    - nethogs
    - pkg-config
    - pv
    - pwgen
    - rcm
    - screen
    - sed
    - tree
    - neovim
    - vinagre
    - wget
    - xclip
    - zsh
- name: install amd64-specific packages
  when: ansible_architecture == "amd64"
  become: yes
  apt:
    pkg:
    - google-chrome-stable
