#- name: Create empty directory for local binaries
#  ansible.builtin.file:
#    path: "{{ local_scripts_path }}"
#    state: directory
#    recurse: true
#    mode: 0700
#- name: Download Java formatter
#  ansible.builtin.get_url:
#    url: https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar
#    dest: "{{ local_scripts_path }}/google-java-format.jar"
#    mode: 0755
- name: Install dev env
  become: true
  ansible.builtin.apt:
    pkg:
      # TODO: - python-is-python3
      # broken: google-cloud-sdk
      - ansible
      #- asciidoc
      #- bison
      #- cabal-install
      - clang
      - clang-format
      - cloc
      - cmake
      - flex
      - gcc
      - ghc
      - gitk
      - gnuplot
      - golang
      - jshon
      - jupyter-nbconvert
      - make
      - markdown
      - npm
      #- protobuf-compiler
      #- pyqt5-dev-tools
      - python3
      - python3-pip
      - ripgrep
      - sloccount
      - tidy  # HTML tidy
      - jq
- name: Remove unwanted pkgs
  become: true
  ansible.builtin.apt:
    name: silversearcher-ag  # I replaced with rg
    state: absent
- name: Install dev env PyPI packages
  ansible.builtin.pip:
    name:
      - autopep8
      - ruff

- name: Install stylua (Lua formatter for Neovim)
  # ansible-galaxy collection install community.general
  community.general.cargo:
    name: stylua

