- name: Add google APT repository
  become: true
  ansible.builtin.deb822_repository:
    name: google
    types: [deb]
    uris:
      - http://dl.google.com/linux/chrome/deb
    signed_by: https://dl-ssl.google.com/linux/linux_signing_key.pub
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  when: ansible_architecture == "amd64" or ansible_architecture == "x86_64"

- name: Add Bazel APT repository
  become: true
  tags:
  - bazel
  ansible.builtin.deb822_repository:
    name: google
    types: [deb]
    uris:
      - https://storage.googleapis.com/bazel-apt
    signed_by: https://bazel.build/bazel-release.pub.gpg
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  # when: ansible_architecture == "amd64" or ansible_architecture == "x86_64"

- name: Install Bazel
  become: true
  tags:
  - bazel
  ansible.builtin.apt:
    pkg:
      - bazel
