apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-stack.fullname" . }}-synapse
spec:
  selector:
    app.kubernetes.io/name: {{ include "matrix-stack.name" . }}
    app.kubernetes.io/component: synapse
  ports:
    - name: http
      port: {{ .Values.synapse.service.port }}
      targetPort: 8008

