- name: Install dev env
  become: true
  ansible.builtin.apt:
    pkg:
      # TODO: - python-is-python3
      # broken: google-cloud-sdk
      #- asciidoc
      #- bison
      #- cabal-install
      - clang
      - ninja-build
      - postgresql
      - postgresql-client
      - android-tools-adb
      - clang-format
      - cloc
      - cmake
      - esptool  # ESP8266/ESP32 flashing tool
      - flex
      - gcc
      - gcc
      - ghc
      - git
      - gitk
      - gnuplot
      - golang
      - golang
      - jq
      - jupyter-nbconvert
      - make
      - markdown
      - sloccount
      - tidy  # HTML tidy
      #- npm <- "you have requested an impossible situations"

      # TODO: this seems to not provide tree-sitter cli though
      # so does not provide latex higlihting
      # - libtree-sitter0  # tree-sitter for neovim syntax stuff

      #- protobuf-compiler
      #- pyqt5-dev-tools

- name: Install dev env PyPI packages
  ansible.builtin.pip:
    name:
      - autopep8
      - ruff
      - pre-commit

# Ubuntu 22.04 ships with ancient Ansible. Get it from pip.
- name: Ansible
  install_handler:
    apt: ansible
    pip: ansible
    use: pip

# TODO: cargo broken
#- name: Install stylua (Lua formatter for Neovim)
#  community.general.cargo:
#    name: stylua

- name: Install OpenAI Codex CLI
  community.general.npm:
    name: '@openai/codex'
    # Seems to mean "install user-globally"
    global: true

  # become: true

- name: Install Bazelisk
  community.general.npm:
    name: '@bazel/bazelisk'
    global: true
