---
- name: Set up dotfiles
  tags:
    - dotfiles
  block:
    # - name: Create empty directory for dotfiles repo
    #   file:
    #     path: "{{ ducktape_path }}"
    #     state: directory
    #     recurse: yes
    #     mode: '0755'
    # - name: Clone ducktape
    #   ansible.builtin.git:
    #     repo: git@gitlab.com:agentydragon/ducktape
    #     dest: "{{ ducktape_path }}"
    #     version: master

    # This is interactive if the files already exist.
    # The uncommented script fails if that happens.
    #
    # - name: Install ducktape dotfiles
    #   ansible.builtin.command: >
    #     rcup -B {{ rcup_computer }} -x vim -x README.md -d {{ ducktape_path }}/dotfiles
    #   register: rcup_result

    - name: Install ducktape dotfiles, fail if would need overwrite
      ansible.builtin.script: rcup_noninteractive.py -B {{ rcup_computer }} -x vim -x README.md -d {{ ducktape_path }}/dotfiles
      args:
        executable: python3
      timeout: 10

    # OrcaSlicer does not play well with its individual files being symlinks.
    - name: Install OrcaSlicer config folder symlink
      ansible.builtin.file:
        # !!! NOTE WEIRD REVERSED CONVENTION !!!
        # For some stupid reason "source" in Ansible convention means the *place where the symlink leads*
        # and "destination" is the *symlink*. Thanks Obama.
        src: "{{ ducktape_path }}/nonrcm-dotfiles/config/OrcaSlicer"
        dest: "/home/{{ my_user | default(ansible_user_id) }}/.config/OrcaSlicer"
        state: link
      become: true
      become_user: "{{ my_user | default(ansible_user_id) }}"
      tags:
      - orcaslicer

    - name: Install Cronomix config folder symlink
      ansible.builtin.file:
        # !!! NOTE WEIRD REVERSED CONVENTION !!!
        # For some stupid reason "source" in Ansible convention means the *place where the symlink leads*
        # and "destination" is the *symlink*. Thanks Obama.
        src: "{{ ducktape_path }}/nonrcm-dotfiles/config/cronomix"
        dest: "/home/{{ my_user | default(ansible_user_id) }}/.config/cronomix"
        state: link
      become: true
      become_user: "{{ my_user | default(ansible_user_id) }}"
