---
# Install kubeseal CLI for Sealed Secrets
- name: Install kubeseal CLI
  github_release_install:
    release_spec:
      repo: "bitnami-labs/sealed-secrets"
      version: "latest"
      asset_pattern: "kubeseal-.*-linux-{{ dpkg_arch }}\\.tar\\.gz$"
    method:
      name: archive
      dest_path: /usr/local/bin/kubeseal
      extract_file: kubeseal
  become: true
  when: dpkg_arch in ["amd64", "arm64"]
