- name: Set to generate only English locale
  become: yes
  ansible.builtin.copy:
    dest: /etc/locale.gen
    mode: '0644'
    content: |
      en_US.UTF-8 UTF-8
      cs_CZ.UTF-8 UTF-8

      # For some convenient time formatting
      en_DK.UTF-8 UTF-8
  notify: Regenerate locales

# See .pam_environment dotfile
- name: Set system-wide locale
  become: yes
  ansible.builtin.copy:
    dest: /etc/default/locale
    mode: '0644'
    content: |
      # English strings
      LANG=en_US.UTF-8

      # TODO: would be nice to have space thousands separator & decimal dot...
      # cs_CZ does 1 234,56. en_US does 1,234.56
      LC_NUMERIC=cs_CZ.UTF-8

      # en_DK does 24 hour time, YYYY-MM-DD date, English weekday & month names.
      # Happens to be convenient.
      LC_TIME=en_DK.UTF-8

      # $1,234.56. Would be nice to have space thousands separator & decimal dot. Alas.
      LC_MONETARY=en_US.UTF-8

      # Unfortunately US formatted paper...
      LC_PAPER=en_US.UTF-8

      # Just how the locale identifies itself..
      LC_IDENTIFICATION=en_US.UTF-8

      # How names are formatted (e.g. Mr. John Smith capitalization etc.)
      LC_NAME=en_US.UTF-8

      # US-formatted addresses
      LC_ADDRESS=en_US.UTF-8

      # US-formatted telephone numbers
      LC_TELEPHONE=en_US.UTF-8

      # Metric system
      LC_MEASUREMENT=cs_CZ.UTF-8
