# TODO: set once, reuse
- command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Enable NodeSource 22.x repo
  deb822_repository:
    name: nodesource
    types: [deb]
    uris: https://deb.nodesource.com/node_22.x
    suites: [nodistro]
    components: [main]
    architectures: ["{{ dpkg_arch.stdout }}"]
    signed_by: /usr/share/keyrings/nodesource.gpg
    state: present
  become: true

- name: Install Node.js (includes npm)
  ansible.builtin.apt:
    update_cache: true
    name: nodejs
    state: present
  become: true
