apiVersion: v1
kind: Secret
metadata:
    name: public-coder-devbox-host-key
    namespace: public-coder-agent
type: Opaque
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:qWnNoVH6c9rjKSnHP73kNvacR/kKn7jEaEL4OYZrNNHSiCRMxqVNQ/iHDK1VE4mfgofbsARgusa9ByWmeXod5MptcYCCvdceF6Zil3uPNuFFGc+Xo24by3InFsCwkR0X8S4M4SuloHQD1fbCtAuyPZhQ5N4OWg3DheQqr8Yv4UXLJHjZshuGSrram8wo1uTElEwTXeXv2CT4uH1rx+vx5AWFX044lEe+u3O979mbcujWSSkyLm/1MAEaLVsB7ToqsNbFEpDdyC4aRl903+nENTF86ZKpkJP9Edixm01hmQ9sE4UKN1vfiNuBvp/iEAYZruDgHeXaLbzhma0up6ZNHvulo291P+z261hMoSl+jAhBBXjJDtWWMGIsZ29DVRKy9ZC8GkY0U1+9n+GpL1hcVGLjVIgy/yWUzjnbcrXRAtM2xCyoL9oOidOpSmnKcks5uUeRI94qHMHaakZVNO03Q+hqyD6iOVfyxjB1daVnHGXqbh4JCmpM57oLN/nV6qK8V9Sx2uuTavXhpdKUOZ9fuNvrY+g09FIMzdrejItYcCwTNF4=,iv:JWrMiUA041NpqEvrjgDB8cGv1CefzQD3bUDHjDKVCUo=,tag:Mdss3VsdsLh2m28jfSINwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSElkZ1FjR21WVDBTQUUv
            RkxEUzh2c3BEQXgyMW15SDlIclJDWVRqYkZvCmNmMVhtc3ZwZUNNeGxVUzE5ZWtm
            STJaRmhyNUl6TlhwWktKVEVKM3BaMEUKLS0tIHpmVEt5MWYyQ0Fnd3BKRVE4MVZC
            WEN6cFJBWmt1Mm5zazFBUUlHMWpxUUkKqjAq9LgMAfGrgQnBDdUleWWQ/b3SNs2e
            2rprydfZTFTUUO2ofOSUW1DxNnF6WIdioho1hmEGTmlR6/qlnI8XJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZGVxS2xrcURBdlBFQ21T
            QklhTW10UldVa3M2VWdSQ3cxMkpFYVdTa2pzCm9rTGd6RkZhcXkyWnNjdlpuaXla
            ay9JMVcyTFhDcllvTU0wQWhBdFMxT1kKLS0tIFpadVdmdlAvbzR5ZUNVQnpreGpU
            RUJkOW5KM0tlVVJyMFBNTnAxM1czRWMKaNVwZB/GR+lWizBrFvMzWpv2T0pGzbZa
            2RR2+smxck1kNwQ80QzHd9SkCbHkwC5Q/cyoOi5dVSPM9ayTUl719Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T07:51:36Z"
    mac: ENC[AES256_GCM,data:ckmOJM7qKxPHNpJs3QGJ/MAJEd6meX6u7VTHPXccRHP0DjUi/IfoTHE8cXxnvtvKOMe3snq0jvVhDTgh/YG22VrhdBzVdqdSMAQf/r72QeHMceaGcUtoZx/7Xqtx/L/GozrVYT3Eld1dawYVndAQ5eOhTMGF0ZDuRIdYJ9M9cNA=,iv:duwIJRlJQyzyUNydk+NdsZxgGW/DCJbLVLyVvw2lM4E=,tag:JjlbOtr/NZwfUx3KDkelrg==,type:str]
    version: 3.13.3
