apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: haku-public-coder-codex
  namespace: haku-runtime-sandbox
spec:
  replicas: 0
  updateStrategy:
    type: Recreate
  sandboxTemplateRef:
    name: haku-public-coder-codex
