apiVersion: v1
kind: Secret
metadata:
  name: coinbase-api-credentials
  namespace: openclaw-sandbox
  annotations:
    description: Coinbase API credentials
type: Opaque
stringData:
  api_key: ENC[AES256_GCM,data:NVdNBhLnHL5vpg==,iv:3RyQeQhOXZp+7DBmClB9QSv4TOYtZ6eY3XF2nontPEU=,tag:G783Cm1p9P1EOZT0zpCBsA==,type:str]
  api_secret: ENC[AES256_GCM,data:+el+ZaopJjKGQQ==,iv:bjJvg8aCRo6OrPozDMSFSdYLkEYlqfvlWaJbrKzCnkU=,tag:Txt0uOgqN4uaDMF0cAgH4Q==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UVM5QXVNYjlPdERwTHlr
        bVNKOFN6SklkbTVoMzRDUlpQckMvbkwvdjJFClJjL2RwblFDOUVYUUtIWDdnVys5
        N0FaTkpmcUZZT05YTENpM0tqM1k4NnMKLS0tIG9tUU9hek1VbG44STB5WjY3Y2RL
        S0ZqeHBxOVgwM0oyUXhaQ1dhd3N5ZlEKMDm2ckZ7CsZvHTI66lrc7XYgtD//AufH
        6Y0wMWqDxYEJACK3wHCUrq6jRNEtrMNkNxNvC0l/6id8pv66RNt/9A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SFNpYm51dFhmbEI0bXda
        T0dVU1FFT2Z4ck9OOG01UVdOQXRKcWxIalJZCmdIWldaU2k3Tk5kUEtnNXg1TDRj
        TDhwMGc2RnpmMG5UNVpWemRFdVNGSTgKLS0tIDZScXVoNkFJRVlISHBBejJVKzgz
        TzdITlNCcDJ0ZUlYU1ZWOUN3N0lFeTgKAUTdKY2ryqKKMCBR3cETc56fQnoyRs+f
        m4ZQaqmyzjif+agssi6iG9NhSO7/n3gj/yeqv4Jnaa4RWlWbqEI5/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:17Z"
  mac: ENC[AES256_GCM,data:rvnIf0pF5Bluu9ZLtuHQVHes8C2DpdqzdN1b/hhg+i3MAwC8FQmqr49GoU6iaVUuq97f9/v9ne0Zb49khRfKffbtVxIVZDYzUiGcbnuuhJ9UE1lt1FmhIabOpaJ3bztmR316ebYrS3oYumNJDqMfV7TzPwTx3fBEdYGWAaHK2P8=,iv:q6telTrIpTuLOjm9xAep77KpQsbVDbKv9Lgw/CUdb6g=,tag:nGRGzyKqzUgTlm4DjhvCJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
