apiVersion: v1
kind: Secret
metadata:
  name: ibkr-flex-query-credentials
  namespace: openclaw-sandbox
  annotations:
    description: IBKR Flex Query credentials
type: Opaque
stringData:
  flex-token: ENC[AES256_GCM,data:orhlUFAtUgyLlw==,iv:bKOs5sbiCKGjxhadVj8FMFYcTvO2JxfbFWQD8RK1HG8=,tag:3ncn8abKNpGDj6LgONNxgg==,type:str]
  query-id: ENC[AES256_GCM,data:KJPveDOhTHE8dA==,iv:hh8YFksfPWkCucI3k2exgqlBuw6ZeJ49Kuyn/DLREmw=,tag:K9Gs8Q45OnjVEo8TpUORPA==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQVVGQjNTbE5LU2hLdm9M
        eU1HbHNVK294UkFGc29QUmZkck9PaDFEYlEwCmsrcjNzQ2lHdEJ4cUlLZUdDRDd2
        WFU3UVM2Mk00dSttdzVEbWl1QTAxL00KLS0tIGgrRWMrTUZNc1VEQ1FteldodFJ3
        aCtyWFFHcTJXWDB3WmJRNVUza0w3bE0KRLw/LtRf+EsFCV5bLRZOQplCUPfPbpVv
        G5mXu0Rw3xV87FS/TGm4CG1JUEePkJ0QU5j5pxMdogpaxxSi9M8kUA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNGNYdkd5cWg4MnJqVit0
        L1VmcmhDOWErNm9uSzQxeGpScWc2Wks3ZVJJCnllSGFFQXNveHpWZ0RCaG01dFJO
        ZjZ0YUpMdkdrUXJVQllKdnNJcnRabUkKLS0tIDdwczRTK0R0L2JjM3lDdk9ENUp6
        QWVyeURldmp4aVRMT3RXZWRDTXNCK0UKWMdsz3wnquvRZI3/5rLFC64JrZi+Lxwp
        FnbQ+GRTLTZWWh9MSmESEsAU139bdse/IOyDu2HsX9PN0G8dtD3r9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:17Z"
  mac: ENC[AES256_GCM,data:q41+rsmUtGuRWe1hj0JSEzHEuWDG6yJwHUSGO7mDIOhaYUVofuJsPr+J00zyMz4my88QbAO9EW1eOUyKmAFDDMl5/5LjU/8Sl281CDjWsNIKvj/HGkrJzpjNIuevEcBGOMUViVarkRi7P4OZUmo4TmMVCD6mBBoC2S5d5ltDpzg=,iv:eubSM4LlCBNTNVS3cSQcZ3um8zvm4ZZ9bvBrsvN/m2E=,tag:8CZ7WhUY8s01Bi/PXx7hsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
