load("@aspect_rules_js//js:defs.bzl", "js_library", "js_test")

_BABEL_DEPS = [
    "//:node_modules/@babel/generator",
    "//:node_modules/@babel/parser",
    "//:node_modules/@babel/traverse",
    "//:node_modules/@babel/types",
]

js_library(
    name = "core_libs",
    srcs = [
        "core.mjs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//devinfra/js/debundle/common:libs",
        "//devinfra/js/debundle/split:libs",
    ] + _BABEL_DEPS,
)

js_library(
    name = "libs",
    srcs = [
        "core.mjs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":core_libs",
        "//devinfra/js/debundle/extract:libs",
    ],
)

js_test(
    name = "bindings_test",
    data = [
        "core.mjs",
        "//devinfra/js/debundle/common:sources",
        "//devinfra/js/debundle/extract:libs",
        "//devinfra/js/debundle/split:libs",
        "//devinfra/js/debundle/test_support:sources",
    ] + _BABEL_DEPS,
    entry_point = "bindings_test.mjs",
)
