---
# PowerDNS role handlers

- name: restart powerdns
  community.docker.docker_compose_v2:
    project_src: /opt/powerdns
    state: present
    restart: true
  become: true
  when: powerdns_state == "present"