"""Tests for automatic example generation from expect_caught_from data.

Examples are now auto-generated by a database VIEW that combines file_sets
and whole-snapshot entries. These tests verify the VIEW produces correct examples.
"""

from __future__ import annotations

import hashlib

from adgn.props.db import get_session
from adgn.props.db.examples import Example
from adgn.props.db.models import FileSet, FileSetMember, Snapshot, SnapshotFile, TruePositive, TruePositiveOccurrenceORM
from adgn.props.ids import SnapshotSlug
from adgn.props.models.examples import ExampleKind, SingleFileSetExample, WholeSnapshotExample
from adgn.props.splits import Split


def _compute_files_hash(file_paths: list[str]) -> str:
    """Compute content-addressable hash for a file set (MD5 of sorted paths)."""
    sorted_paths = sorted(file_paths)
    content = "\n".join(sorted_paths)
    return hashlib.md5(content.encode("utf-8")).hexdigest()


def test_generate_examples_train_split(synced_test_db):
    """Test example VIEW for TRAIN split creates per-file-set examples + whole-snapshot."""
    with get_session() as session:
        # Use test-trivial fixture (train split)
        slug = SnapshotSlug("test-fixtures/test-trivial")
        snapshot = session.query(Snapshot).filter_by(slug=slug).one()
        assert snapshot.split == Split.TRAIN

        # Query examples from VIEW
        examples = session.query(Example).filter_by(snapshot_slug=slug).all()

        # Should have multiple examples (one per unique file set + full-specimen)
        assert len(examples) > 1

        # Each example should be an Example ORM object
        for example in examples:
            assert isinstance(example, Example)

            # Check example_kind is valid
            assert isinstance(example.example_kind, ExampleKind)
            assert example.example_kind in [ExampleKind.WHOLE_SNAPSHOT, ExampleKind.FILE_SET]

            # Verify example_spec conversion works
            example_spec = example.to_example_spec()
            assert isinstance(example_spec, WholeSnapshotExample | SingleFileSetExample)

            if example.example_kind == ExampleKind.WHOLE_SNAPSHOT:
                # Whole snapshot examples
                assert example.files_hash is None
                assert isinstance(example_spec, WholeSnapshotExample)
            else:
                # Single file set examples
                assert example.example_kind == ExampleKind.FILE_SET
                assert example.files_hash is not None
                assert isinstance(example_spec, SingleFileSetExample)
                assert example_spec.files_hash == example.files_hash

        # One example should be whole-snapshot
        full_specimen_found = any(ex.example_kind == ExampleKind.WHOLE_SNAPSHOT for ex in examples)
        assert full_specimen_found, "Whole-snapshot example not found in generated examples"


def test_generate_examples_valid_test_split(synced_test_db):
    """Test example VIEW for VALID split (per-file + whole-snapshot) and TEST split (whole-snapshot only)."""
    with get_session() as session:
        # Test VALID split using test-validation fixture
        slug = SnapshotSlug("test-fixtures/test-validation")
        valid_snapshot = session.query(Snapshot).filter_by(slug=slug).one()
        assert valid_snapshot.split == Split.VALID

        # Query examples from VIEW
        valid_examples = session.query(Example).filter_by(snapshot_slug=slug).all()

        # VALID should have multiple examples (per-file + whole-snapshot)
        assert len(valid_examples) > 1, "VALID split should generate per-file examples for targeted mode"

        # At least one should be whole-snapshot
        full_specimen_found = any(ex.example_kind == ExampleKind.WHOLE_SNAPSHOT for ex in valid_examples)
        assert full_specimen_found, "VALID split should include whole-snapshot example"

        # Note: TEST split testing skipped - no test-fixtures/test snapshot in git
        # TEST split behavior is well-defined: only generate full-specimen example


def test_generate_examples_unique_file_sets(test_db):
    """Test that duplicate file sets are deduplicated by the VIEW."""
    with get_session() as session:
        # Create a test snapshot with duplicate file sets
        slug = SnapshotSlug("test/example-generation")

        # Clean up any existing test data
        session.query(FileSet).filter_by(snapshot_slug=slug).delete()
        session.query(TruePositive).filter_by(snapshot_slug=slug).delete()
        session.query(Snapshot).filter_by(slug=slug).delete()
        session.commit()

        # Create snapshot
        snapshot = Snapshot(slug=slug, split=Split.TRAIN, source={"vcs": "local", "root": "."}, bundle=None)
        session.add(snapshot)

        # Add TP (occurrences are added via the relationship using ORM model)
        tp = TruePositive(
            snapshot_slug=slug,
            tp_id="test-dup",
            rationale="Test issue with duplicate file sets",
            occurrences=[
                TruePositiveOccurrenceORM(
                    snapshot_slug=slug,
                    tp_id="test-dup",
                    occurrence_id="occ-dup-1",
                    files={"file1.py": None},  # JSONB: dict with str keys
                    expect_caught_from=[["file1.py"], ["file1.py"]],  # JSONB: list[list[str]] - duplicates!
                ),
                TruePositiveOccurrenceORM(
                    snapshot_slug=slug,
                    tp_id="test-dup",
                    occurrence_id="occ-dup-2",
                    files={"file2.py": None},
                    expect_caught_from=[["file1.py"]],  # Same file set as above
                ),
            ],
        )
        session.add(tp)
        session.commit()

        # Add files to snapshot_files (required for FK validation)
        session.add(SnapshotFile(snapshot_slug=slug, relative_path="file1.py", line_count=10))
        session.add(SnapshotFile(snapshot_slug=slug, relative_path="file2.py", line_count=10))
        session.commit()

        # Manually create file sets (normally done by sync)
        # The deduplication happens in the VIEW's GROUP BY
        files_hash = _compute_files_hash(["file1.py"])
        file_set1 = FileSet(snapshot_slug=slug, files_hash=files_hash)
        session.add(file_set1)
        session.flush()

        fs_file1 = FileSetMember(snapshot_slug=slug, files_hash=files_hash, file_path="file1.py")
        session.add(fs_file1)
        session.commit()

        # Query examples from VIEW
        examples = session.query(Example).filter_by(snapshot_slug=slug).all()

        # Should deduplicate: 1 unique file set + 1 full-specimen = 2 examples
        assert len(examples) == 2

        # One example should be the single unique file set
        file_set_found = False
        full_specimen_found = False
        for example in examples:
            if example.example_kind == ExampleKind.WHOLE_SNAPSHOT:
                full_specimen_found = True
            elif example.example_kind == ExampleKind.FILE_SET:
                # Check if this is the file1.py file set
                # (We can't easily check the files without querying file_sets table)
                file_set_found = True

        assert file_set_found, "Single-file-set example not found"
        assert full_specimen_found, "Whole-snapshot example not found"
