apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: monitoring
  annotations:
    description: MinIO credentials for Mimir metrics storage
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EomXRkre0ILc1jVUHcmcJg==,iv:20tk6FFGaXT3r6BYh4n1j57hFukTG9XEgzD8x1VcmB4=,tag:4Ag91lVtVd9peK5UOhfnsg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NvjkJfKLp1+cht2gbsNO7tMs8cge9EBTb+HnJ+R3OSf9ErcBhLneA6lwgg==,iv:L39batI4FsdA1mWgsMNXO1epVHW78NqHq3Gc8FSChnQ=,tag:KU18Ov0Prx2cZau1k9JN0g==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodlVJKzNqNDc2ZktqYVhG
        aTdjUjZGeWJGTnU1dnhLNjh5MHVnTHVpd3lZCkJ4WUFQcXlwYVczeDJJNG00TUZY
        bjBPQkpITlM5VXpGMkp2aHNkUVhxZDAKLS0tIFMzcnNPZE5jYmVIallGcTY0bGlP
        YWFJU1BhdUdDVWRKdThsTEdZdW0rUlUKSoErncAeLe6aHs62WLIofJSUFbUh1Hd1
        oTVk2fi88Zx/zYDHs9JDEXP+X0HtRK23FeoL2BUrC5CPQgFZEqgcaA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRkFhU3MzQ251RVYxS05Y
        TUh4aXh6VG1pNjZ6K0xyQU1SYTFaSGxteXl3CmJQcGlzbFZsMDJmQy83K2dhVUpk
        bDU0THdDdEVURWtHM2NDeVNySDN6UlUKLS0tIERFbzUxR0ZSc2ZtRGxibDMyQjRx
        UzhOTEdQYWdQa01IeFQ0WElmK1UrY0EKeraoR+ujqWgWdI3flE1UBo8Ez44aMZYs
        MSaj7paSSx7x9jqY531qtrcvKvwnpcE6kgJotGA9lYrrhQtpBO7Edg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T06:17:18Z"
  mac: ENC[AES256_GCM,data:lW7OWFEkiizWGgpKnaYKyrC8+G7Xw/ckZYQK8Ku+hjg76Wd48OXpBDtL1X8rVgywPD+8mXwGB/B69w7zkCnmYTqVYxMJL8DMGVFQxkOnu8NGVrw0Cdchx+Z0aIdh2oK19HGC/14GFKJvPrd0WdZngaR4Qc6vxezEuQO2yjGVAtA=,iv:zL/dsvWHX9SG3xyA2X2R9xabzE10wzRyfWOpCCB3UE4=,tag:sI5/a2AhmGGKPAwIg9Y/9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
