load("//devinfra/python:defs.bzl", "py_library")

exports_files(["0001_session_history.py", "0002_unique_runner_locator.py"])

py_library(
    name = "0001_session_history",
    srcs = ["0001_session_history.py"],
    deps = [
        "@pypi//alembic",
        "@pypi//sqlalchemy",
    ],
)

py_library(
    name = "0002_unique_runner_locator",
    srcs = ["0002_unique_runner_locator.py"],
    deps = ["@pypi//alembic"],
)
