"""Module extension for proxy configuration.

This generates a proxy_env.bzl file that can be loaded by BUILD files.
The content differs based on whether we're on Claude Code web (with TLS proxy)
or local development (no proxy needed).

Detection:
- On CC web: BAZEL_PROXY_PORT env var is set by session hook
- Locally: env var not set, use empty proxy config
"""

def _proxy_config_repo_impl(repository_ctx):
    """Generate proxy_env.bzl based on environment."""
    # Check for proxy configuration from environment
    # On CC web, the session hook sets BAZEL_PROXY_PORT before invoking bazel
    proxy_port = repository_ctx.os.environ.get("BAZEL_PROXY_PORT", "")

    if proxy_port:
        # On Claude Code web with proxy - generate from env vars
        combined_ca = repository_ctx.os.environ.get(
            "BAZEL_COMBINED_CA",
            "/root/.cache/bazel-proxy/combined_ca.pem",
        )
        local_proxy = "http://localhost:{}".format(proxy_port)
        content = '''\
# Auto-generated proxy config for Claude Code web
PROXY_ENV = {{
    "HTTPS_PROXY": "{proxy}",
    "HTTP_PROXY": "{proxy}",
    "https_proxy": "{proxy}",
    "http_proxy": "{proxy}",
    "SSL_CERT_FILE": "{ca}",
    "REQUESTS_CA_BUNDLE": "{ca}",
}}
'''.format(proxy=local_proxy, ca=combined_ca)
    else:
        # Local development - no proxy needed
        content = '''\
# Default proxy config for local development
PROXY_ENV = {}
'''

    repository_ctx.file("proxy_env.bzl", content)
    repository_ctx.file("BUILD.bazel", """\
# Auto-generated by proxy_config module extension
exports_files(["proxy_env.bzl"])
""")

proxy_config_repo = repository_rule(
    implementation = _proxy_config_repo_impl,
    environ = ["BAZEL_PROXY_PORT", "BAZEL_COMBINED_CA"],
    doc = "Repository rule that generates proxy configuration based on environment.",
)

def _proxy_config_impl(module_ctx):
    """Module extension implementation."""
    proxy_config_repo(name = "proxy_config")

proxy_config = module_extension(
    implementation = _proxy_config_impl,
    doc = "Module extension for proxy configuration.",
)
