"""Settings for the auth-aware Grocy MCP server."""

from __future__ import annotations

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

from mcp_infra.authentik_auth.auth import AuthentikAuthConfig


class ServerSettings(BaseSettings):
    """Config for the Grocy MCP server."""

    model_config = SettingsConfigDict(env_prefix="GROCY_MCP_")

    # ── Authentik auth fields ─────────────────────────────────────────────
    oidc_issuer: str = Field(
        description="Authentik per-provider issuer URL, e.g. https://auth.allegedly.works/application/o/grocy-mcp/"
    )
    oidc_client_id: str = Field(description="OAuth2 client_id for the Authentik user-login OAuth2 provider")
    oidc_client_secret: str = Field(description="OAuth2 client_secret for the Authentik user-login OAuth2 provider")
    public_base_url: str = Field(
        description="Public URL at which this MCP server is reachable, e.g. https://grocy-mcp.allegedly.works"
    )
    grocy_proxy_client_id: str = Field(
        description=(
            "client_id of the existing Grocy authentik_provider_proxy (the inner "
            "OAuth2 client auto-generated by Authentik on the proxy provider). "
            "Used as the `client_id` in the JWT-bearer token exchange."
        )
    )

    # ── Grocy-specific fields ─────────────────────────────────────────────
    grocy_url: str = Field(
        description="Public URL of the outpost-protected Grocy instance, e.g. https://grocy.allegedly.works"
    )
    host: str = "0.0.0.0"
    port: int = 8765

    # ── Timeout and resilience knobs ──────────────────────────────────────
    grocy_timeout: float = Field(default=30.0, description="Timeout (seconds) for Grocy API requests.")
    exchange_timeout: float = Field(
        default=10.0, description="Timeout (seconds) for Authentik token exchange requests."
    )
    max_batch_size: int = Field(default=20, description="Maximum items per batch tool call.")
    max_concurrent_requests: int = Field(default=4, description="Maximum parallel Grocy API requests within a batch.")
    max_retries: int = Field(default=2, description="Retry count for transient errors (timeouts, 5xx).")
    retry_base_delay: float = Field(default=0.5, description="Initial retry delay in seconds; doubles each attempt.")

    def auth_config(self) -> AuthentikAuthConfig:
        """Construct the shared auth config from this server's settings."""
        return AuthentikAuthConfig(
            oidc_issuer=self.oidc_issuer,
            oidc_client_id=self.oidc_client_id,
            oidc_client_secret=self.oidc_client_secret,
            public_base_url=self.public_base_url,
            proxy_client_id=self.grocy_proxy_client_id,
            exchange_timeout=self.exchange_timeout,
        )
