apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-ci-data
  namespace: docker-ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvm-proxmox
  resources:
    requests:
      storage: 50Gi
