load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "generic_graders",
    srcs = ["generic_graders.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":scoresheet",
        "@pypi//openai",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "scoresheet",
    srcs = ["scoresheet.py"],
    visibility = ["//:__subpackages__"],
)
