apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/public-coder-agent
    newTag: devel-20261002164854-6e44b24 # {"$imagepolicy": "flux-system:public-coder-agent:tag"}
