apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: git.allegedly.works/ducktape-ci/public-coder-agent
    newTag: devel-20261001040651-ea9a3f7 # {"$imagepolicy": "flux-system:public-coder-agent:tag"}
