load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "proxmox": "bpg/proxmox:~>0.91.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "proxmox-vm",
    providers = [
        "proxmox",
    ],
    providers_versions = ":providers",
)
