apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: litellm-api-key
  namespace: flux-system
spec:
  interval: 15m
  approvePlan: "auto"
  path: ./cluster/terraform/gitops/litellm-api-key
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  serviceAccountName: tf-runner
  backendConfig:
    customConfiguration: |
      backend "kubernetes" {
        secret_suffix    = "litellm-api-key"
        namespace        = "flux-system"
      }
  vars: []
