---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgAflVb8F0zNvZGeyinXLTG1qr7xW0bqRpicL2+oICqAmJpu7fVw8DJxpcZtfgQT1xRIWNml4GxeVY6DNjW3k/t1cvnE5XlK9Vc2VBPYVORxoBUxPaVGgMYax7vJs/gglJyT7eeAeJoc4bHBG+CF4S5SwVid6Y//r231rSlTo4zX0XvPvxF0Wkoelo1/IvbHrk0S9PLMzK0KQD59+4wxFRqo2bmzRQi1KOWa1U2mf/ukS0zMHO1Cjr7p5l3xHizNA0d8YHzCRWaeyOIv+pP0xK4VBR0TZFnDfpFqp1gLT3KwV84f50p8v/Lv6tF0LSI1yh5+542csgf2gQIlfG7m4vyIY8yj4SD6ENv3vsVNtuYUrC8PSAtZj1zemQ9q1MS2Imn4a9G63YQ64xqMQkfrCx1bczXQsO6avvGl3HwFke/13Hf7Ok7UD9jfKT3NWmKvCJJKJwVcSUSBvuNfJMqOC6xUvHxq39i96FpmrjFQUzCZFqiMtux8wi9eoQgR/2qsOTsOoUl0fVb00scPldYicMBxiNx9BV1emfTXtb9KIzdM1co3eWPxif3FM/KytLgY3UzrIrDBIziFxV4+fuAERdMQXjYegrPo/5m3u26II03oNo0881A5ehvygRgr8P0oAM7w4RObgIcaFF424eLmQm0uC5TGzuVulwuXHBKlEnub24tf6rU+EpxfVv25yJReli5dfE/VXaI/qHm5V4n6hGxNkmc017I7dQsxEyhFvtUfnTXCmSgQR+SBShAwXHix+6EpBzjj5FOzqfSkFjTEkAjUQlNvNucAt9TENIGuSZCKtuyDUpqydao7EvV+Aafb0CSF+Dkb0r370bvN/RRaet9QT9kW/PQ4dID3uRAvoLyyfyek8Sl4l2YZxinwF6+Ph3vBy8KVHN4uX7XGT7CjVUbkYVvzPhSQtrgAByTqhZW3YUjlUlgmLw==
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
    type: Opaque
