---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgAZmbT11Puy7YRJ4dzYQJfB4vkEyw4n+LNQp3zrcfX1qzp1Q0m8eABw+L/D6TE7p8uJG/0msa8YQxF7SyYbI5q3VuQk2ybO2EcUj9Sl89GAEY2y9VyNCGl4e5Vjam5SVaZ+pUCiWJ2lA2ps1l3E72dWJtRl8zkL4EkoWO1YDbeEWPhWKAydT0/7evInP7TksWyGpginNP1+hlyRQOgD4Uay6/f7I+o/nMx6Rtt2a8XA6DY5RLEFKllGdkmjxLmxdsUwxryy4vGCF6Sv1p5ItMa1C+rTQkYJ6TjMQ/Cp1UB+RkwCXU3pzS6SB2qDLcijVYZu5LDNszIfRk1XHvARXmluFrSRobXpc3jc95zFK94z3Vf1MwtMtUVgY4gh+YicvEXBRPK2eJhRyVABhgnLiiL/q2Gcni5WCUWo3BVPVyreOdwKU3/NehoeGYvpO48KxUg9Lch6DuhaVvXw+jvH0xY177ixoLpkAzVUmHDeBh7mp6/pH0Kh5WFHpvLz/QDFXaM7banF97Eh/eI9TvH+xV8wVKGXtmDFiNQEMejnrwvW4atOSfqD8ZXVpdhg4MNOnML00JRAg7qEpcYFFt2C8aEloAMJtvDz422vHnV3IzN7e/PhqtLjuYRK6eQbtCqBXmx6DWxgYxPrpqGmuWpadyWkwVryZRMSqZvnmHPw+bKm91IdLwqOX2sCO0PlHdFutXj34TQAeQpq1jYRlvF8OXuRRCqBQC1ZUzFzh4PU5GlxccLXdHptMeINf/EVyw4mHdFr+izWPLO8Gva9v++o8HXMSY53BEgIKwI8sp8aS1Dgi1jduzlTNoDRDL0yjAWn7aUEQk2UNqydTh9H874l/J5BUrvhm6JnOuc+Q/HwkB94t8+/bPQtWi1OZ4Vv/z0txuHbRxhhQnXMzDUBmXx5P02C0Czi60/I6OEWHd8UpjoqqpdajCA4Jg==
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
    type: Opaque
