---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgA7ct1rhHrCc8GCBW2TgtGYmPV2cnajdCrvV3W+K347VZwqQEeFaLf71FHN9AjJHZDcXQBQTHcK/b9y2F5yoKdPqWZdRHfbnqqWIfgTdb1AROHq28LOCbaUy9Ci6ALv8iIFlcaFImehN1DizaM78W3PMX3kZdzaURGHJ3UImys1PmIIOnqUZalWRwZyvg1zfX2EZgVALrf/TKwytU9EHGNH0543Bg6W9jXxVj5wgvQaO/PYy02KR/KOZKPrfR3XInq40zYlXeWqJP0+/ZgpfUXxcKke4L2EwaG3AqpNLLgvGT67pw6gGPWSHbUhl8mjhsYCK3/rfP24ZmaZ5TIWARF7RlU//RzcCiHP7Lky1g+a367yjthJRFEKCroaa3mA+54LUZFcGLlxDCy21czNDtVw1gNf6eBtoo28SPBguXUBSBSvxKQHZ4jaT14YmZU5PkiEXei3LVA0kJOskkqInLFyRrqV1WltCrqa7BPbNo+xCd1CXxQXqR4hW40AQInYK3F5QmxXRawWg8bESVOHAJlx8c4VW2RjdCFmuLHIuBZYv/5odaCut2mBL5OZovhDYOl6ihFAdvrv69HI5GrsIyq5ldxSsiJV68JgzgQHMWr7fT74DYrkSFUe1UFeHWEC/NgoHxi0a/kbJ0/URpXgEWJUE3ITyspf+mCmdnd8/PigtvHj8l6GSyDWLstBgMPc7euiu60azDsA1qhMBepaSEUAypDx2931CSmZsfkwyaPZ0eYZCcYOW8PA0xaUr7zH0cfvoIF9ee3wpB5o/a7s9CDE6CwTuUVBgAH/zKfq6LImmvQAtgDSyF8Mxx+gGQYFO6GteqvmFf9LQeFkQx1lCst9uUOZIylcjVernRBYTwBVuuJxc2Al+TyuBGYvLuap4MbJyK/Dm7lHs69da7UwdnpaTNdgZpA9kvAaATGtri/eZD59nEJqMxNqGkelNJ9IaID+SQOllb92wpkZHbkJ
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
    type: Opaque
