apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanner-data
  namespace: scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: TODO # replace before unsuspending
  resources:
    requests:
      storage: 20Gi
