apiVersion: ENC[AES256_GCM,data:Bkc=,iv:LusXNgnSfpfbz+AG4E0VvDX3qd398jheVOEm8DUpn+M=,tag:cXX2NV4GcGJIW9dj7WalKg==,type:str]
kind: ENC[AES256_GCM,data:Btm80MUt,iv:H61c+IFRMS/gxsA+U7Fz5czwJUIMy863NcRqT1LaaCU=,tag:bx6xUHRLy1QmA6teifeTLg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:KXBvPd9U6UsxJ/RS3oQ8xlg=,iv:P8C+HGvM6FB3LoGl2NpCy7F4rk0n8T6AHhgWQI5Kp4Y=,tag:JB4JOqgjZCYyY3do5XcB9Q==,type:str]
  namespace: ENC[AES256_GCM,data:ld5ISHsLCA==,iv:OdIw2GNKMYEnB9nQhwlPrV10bIBxklN3y6tPtEqUGHo=,tag:LwjLMoqGDI0/H//YSgX/Vg==,type:str]
  annotations:
    description: ENC[AES256_GCM,data:D37TKK09qQEgH/SKrQYE60ksP4JUcpk=,iv:yD9ZoM7T23yAK/iFgEGntDdF2sOPopu/LboG6Yom/Iw=,tag:7eYHF811GKdqsMX7YL3chQ==,type:str]
type: ENC[AES256_GCM,data:fOc7Tr66,iv:QnJn9od+JfgZ8LjdV5FcgDbputYia3/PJ2tstghxOFM=,tag:q0FhwBYbci1nBERE5mTjlg==,type:str]
stringData:
  username: ENC[AES256_GCM,data:A+PkXtNl05Ftjg==,iv:SNbekokH14Zwvu6xKYSbI25QU0WKElxNOQjKIFDiEoQ=,tag:Vb+H5FDm2NfP6c/baXS6mw==,type:str]
  password: ENC[AES256_GCM,data:8M4GugNsZaQKgQ==,iv:8v/2XA5d/QA5DHcwGiXigy7etw/s55JFB4VimeXgEns=,tag:VEu7fgagDAq+p791sGnC9A==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaUsraDBlcjY4enM4My9L
        a0prRDRWMTFNWFNDRjhPajB4c1JTTDh0SjN3CjNEVjNHYitaZGRITk9OaXZUUTcy
        ZWtjcUtDall1Z3lYOUhEbndsNHd0Y2sKLS0tIFNBeSt4WHZRRUNvUFJCMGNVbTNr
        WlJuMWhyUWxGbSs1K1l3RHpnYU1zTEUK3pXY3OI1WLRuOD6B5leJccUekxRanQzK
        npue0efvLvFo7jfgVApQXuEEQIDHPzz/6IiNWxD5aOSpA7igF0Uvow==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMDEwRExINzUzRmJscXg2
        d1FMSkFUUExrdWFPazRwVGMrY0NVSU1BNTFFCjFlbHZ3ZkZxNU5BbFhLcGo1Q1dm
        Sjc4aVc5N1l3UzQxY2ZacXRCWm81MnMKLS0tIGNtVmN1cmZJYzZXOUR6aFlDZ1Fr
        bVJES3JaNVNvZGUyR0xyTjBQbXlOWWcKAdhJrz/vGb0vwctJeb2PC9Z+iHAs8IUQ
        3PnNKftXkWYWbIVOaDHk55rKFb9PYehYH3ZuG0O06JTbnr64dZNo0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T07:01:40Z"
  mac: ENC[AES256_GCM,data:xwzXDLunegYIwaARo2WGIArEkyoL0u1LnIXooTxYOkumlK76qixuBVyUkgda4q0oYGbKYbSj+JNtl3QYhWBdkBpun7T/DB3LBxg4w9h4CJjnmpdJynWvQ+lC8iIdkFQpITQAfSG/576HqWMZuRcUnlzoXw6ksmvYDP0bWX442lE=,iv:w7ireiXZGfEDYclv/I3L65FI//AoYbT/d//CMnhMlSY=,tag:jymI+g0og0UFsMRo2rVPQw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
