"""Database models and connection management for Claude instruction optimizer."""

import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import ClassVar, Optional

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    Text,
    UniqueConstraint,
    create_engine,
    event,
)
from sqlalchemy.orm import Session, declarative_base, relationship, sessionmaker

Base = declarative_base()


class OptimizationRun(Base):
    """
    Top-level optimization run containing multiple iterations.
    
    Each optimization run represents a complete experiment where we iteratively 
    improve CLAUDE.md system prompts by running agent rollouts, grading them,
    analyzing patterns, and generating improved prompts.
    """
    __tablename__ = 'optimization_runs'
    __table_args__: ClassVar[dict] = {'comment': 'Complete optimization experiments with iterative prompt improvement'}
    
    id = Column(Integer, primary_key=True, comment='Unique identifier for each optimization run')
    start_time = Column(DateTime, nullable=False, default=datetime.utcnow, 
                       comment='When this optimization run started')
    end_time = Column(DateTime, comment='When this optimization run completed (NULL if still running)')
    base_output_dir = Column(Text, nullable=False, 
                            comment='Filesystem path where all agent outputs are stored (e.g., ./agent_output/20250728141530)')
    total_iterations = Column(Integer, comment='Total number of optimization iterations planned')
    config_snapshot = Column(Text, comment='JSON snapshot of OptimizerConfig used for this run')
    status = Column(Text, default='running', 
                   comment='Current status: running, completed, failed')
    
    # Relationships
    system_prompts = relationship("SystemPrompt", back_populates="run")
    rollouts = relationship("Rollout", back_populates="run")
    pattern_analyses = relationship("PatternAnalysis", back_populates="run")


class SystemPrompt(Base):
    """
    System prompts (CLAUDE.md content) used across iterations.
    
    Each iteration uses a system prompt to guide agent behavior. Iteration 0 uses
    the initial prompt, while later iterations use prompts generated by the 
    PromptEngineer based on pattern analysis of previous rollouts.
    """
    __tablename__ = 'system_prompts'
    __table_args__: ClassVar[dict] = {'comment': 'CLAUDE.md system prompts that guide agent behavior in each iteration'}
    
    id = Column(Integer, primary_key=True, comment='Unique identifier for each system prompt')
    run_id = Column(Integer, ForeignKey('optimization_runs.id'), nullable=False,
                   comment='Which optimization run this prompt belongs to')
    iteration = Column(Integer, nullable=False, 
                      comment='Iteration number: 0=initial prompt, 1+=generated by PromptEngineer')
    content = Column(Text, nullable=False, 
                    comment='Full CLAUDE.md system prompt content that guides agent behavior')
    content_hash = Column(Text, nullable=False, 
                         comment='SHA256 hash of content for deduplication and change detection')
    created_at = Column(DateTime, default=datetime.utcnow, comment='When this prompt was created')
    prompt_engineer_reasoning = Column(Text, 
                                     comment='JSON of OpenAI o3 reasoning that led to this prompt generation')
    
    # Relationships
    run = relationship("OptimizationRun", back_populates="system_prompts")
    rollouts = relationship("Rollout", back_populates="system_prompt")
    
    @classmethod
    def compute_content_hash(cls, content: str) -> str:
        """Compute SHA256 hash of content for deduplication."""
        return hashlib.sha256(content.encode('utf-8')).hexdigest()


class SeedTask(Base):
    """
    Seed tasks loaded from seeds.yaml, stored with full content and requirements.
    
    These are the programming tasks that agents attempt to solve. Each task
    is designed to test specific coding patterns and behaviors. Tasks are
    loaded from YAML and synchronized to the database with change detection.
    """
    __tablename__ = 'seed_tasks'
    __table_args__: ClassVar[dict] = {'comment': 'Programming tasks that agents attempt to solve, loaded from seeds.yaml'}
    
    id = Column(Integer, primary_key=True, comment='Unique database identifier for each task')
    task_id = Column(Text, unique=True, nullable=False, 
                    comment='Task identifier from YAML (e.g., "seed_broad_except_002")')
    prompt = Column(Text, nullable=False, 
                   comment='Full task description that agents receive (searchable)')
    description = Column(Text, comment='Optional human-readable description of what this task tests')
    
    # Task execution requirements
    allowed_tools = Column(Text, comment='JSON list of allowed tools for this task')
    docker_image = Column(Text, nullable=False, comment='Docker image name for this task (e.g., "claude-dev:python")')
    pre_task_commands = Column(Text, comment='Shell commands to run inside container before task execution')
    
    content_hash = Column(Text, nullable=False, 
                         comment='SHA256 hash of all task content for change detection')
    created_at = Column(DateTime, default=datetime.utcnow, comment='When this task was first added')
    updated_at = Column(DateTime, default=datetime.utcnow, comment='When this task was last modified')
    is_active = Column(Boolean, default=True, 
                      comment='Whether this task is currently active (FALSE if removed from YAML)')
    
    # Relationships
    rollouts = relationship("Rollout", back_populates="task")
    task_repositories = relationship("TaskRepository", back_populates="task")
    
    @classmethod
    def compute_content_hash(cls, prompt: str, description: Optional[str] = None, 
                           allowed_tools: Optional[str] = None, docker_image: Optional[str] = None, 
                           pre_task_commands: Optional[str] = None) -> str:
        """Compute SHA256 hash of all task content for change detection."""
        content = f"{prompt}|{description or ''}|{allowed_tools or '[]'}|{docker_image or ''}|{pre_task_commands or ''}"
        return hashlib.sha256(content.encode('utf-8')).hexdigest()
        
    @property
    def allowed_tools_list(self) -> list[str]:
        """Parse allowed_tools JSON into list."""
        return json.loads(self.allowed_tools) if self.allowed_tools else []
        


class GradingCriteria(Base):
    """
    Grading criteria loaded from graders.yaml, stored with full content.
    
    These define the evaluation facets used to grade agent solutions. Each 
    criterion has detailed evaluation instructions that guide the OpenAI o3
    grader. Criteria are loaded from YAML and synchronized with change detection.
    """
    __tablename__ = 'grading_criteria'
    __table_args__: ClassVar[dict] = {'comment': 'Evaluation criteria that define how agent solutions are graded, loaded from graders.yaml'}
    
    id = Column(Integer, primary_key=True, comment='Unique database identifier for each grading criterion')
    name = Column(Text, unique=True, nullable=False, 
                 comment='Criterion name from YAML (e.g., "type_safety_data_design")')
    description = Column(Text, nullable=False, 
                        comment='Human-readable description of what this criterion evaluates')
    evaluation_criteria = Column(Text, nullable=False, 
                               comment='Full evaluation instructions that guide the OpenAI grader (searchable)')
    content_hash = Column(Text, nullable=False, 
                         comment='SHA256 hash of description+criteria for change detection')
    created_at = Column(DateTime, default=datetime.utcnow, comment='When this criterion was first added')
    updated_at = Column(DateTime, default=datetime.utcnow, comment='When this criterion was last modified')
    is_active = Column(Boolean, default=True, 
                      comment='Whether this criterion is currently active (FALSE if removed from YAML)')
    
    # Relationships
    facet_results = relationship("GraderFacetResult", back_populates="criterion")
    
    @classmethod
    def compute_content_hash(cls, description: str, evaluation_criteria: str) -> str:
        """Compute SHA256 hash of criteria content for change detection."""
        content = f"{description}|{evaluation_criteria}"
        return hashlib.sha256(content.encode('utf-8')).hexdigest()


class Rollout(Base):
    """
    Individual agent rollout execution.
    
    Each rollout represents one coding agent attempting to solve one task
    using a specific system prompt. The agent produces code files and has a
    conversation that gets graded. Multiple rollouts per task per iteration
    provide statistical validation of prompt effectiveness.
    """
    __tablename__ = 'rollouts'
    __table_args__: ClassVar[dict] = {'comment': 'Individual coding agent executions attempting to solve specific tasks'}
    
    id = Column(Integer, primary_key=True, comment='Unique identifier for each rollout')
    run_id = Column(Integer, ForeignKey('optimization_runs.id'), nullable=False,
                   comment='Which optimization run this rollout belongs to')
    iteration = Column(Integer, nullable=False, comment='Iteration number within the run')
    task_id = Column(Integer, ForeignKey('seed_tasks.id'), nullable=False,
                    comment='Which seed task the agent attempted to solve')
    agent_id = Column(Text, nullable=False, comment='Agent instance identifier (e.g., "agent_1")')
    system_prompt_id = Column(Integer, ForeignKey('system_prompts.id'), nullable=False,
                             comment='Which system prompt guided this agent execution')
    start_time = Column(DateTime, comment='When the agent execution started')
    end_time = Column(DateTime, comment='When the agent execution completed')
    total_cost_usd = Column(Float, comment='Total cost in USD for this coding agent execution')
    is_error = Column(Boolean, default=False, comment='Whether the rollout failed with an error')
    duration_ms = Column(Integer, comment='Total execution time in milliseconds')
    output_dir_path = Column(Text, nullable=False, 
                            comment='Filesystem path where agent outputs are stored')
    
    # Relationships
    run = relationship("OptimizationRun", back_populates="rollouts")
    task = relationship("SeedTask", back_populates="rollouts")
    system_prompt = relationship("SystemPrompt", back_populates="rollouts")
    messages = relationship("RolloutMessage", back_populates="rollout")
    files = relationship("RolloutFile", back_populates="rollout")
    grader_run = relationship("GraderRun", back_populates="rollout", uselist=False)
    
    @property
    def duration_seconds(self) -> Optional[float]:
        """Duration in seconds, computed from duration_ms."""
        return self.duration_ms / 1000.0 if self.duration_ms is not None else None


class RolloutMessage(Base):
    """Messages from Claude SDK conversation, stored with full content."""
    __tablename__ = 'rollout_messages'
    __table_args__: ClassVar[tuple] = (UniqueConstraint('rollout_id', 'sequence_order'),)
    
    id = Column(Integer, primary_key=True)
    rollout_id = Column(Integer, ForeignKey('rollouts.id'), nullable=False)
    sequence_order = Column(Integer, nullable=False)
    message_type = Column(Text, nullable=False)  # 'system', 'user', 'assistant', 'result'
    content = Column(Text, nullable=False)  # Full JSON message content stored
    timestamp = Column(DateTime)
    
    # Relationships
    rollout = relationship("Rollout", back_populates="messages")


class RolloutFile(Base):
    """
    Agent output files, stored as path + SHA256 hash only.
    
    This table stores metadata about files created by agents, but NOT the file
    content itself. Content stays on the filesystem and is verified using SHA256
    hashes. This provides efficient storage while maintaining data integrity.
    """
    __tablename__ = 'rollout_files'
    __table_args__: ClassVar[dict] = {'comment': 'Metadata for agent-created files (content stored on filesystem, verified by SHA256)'}
    
    id = Column(Integer, primary_key=True, comment='Unique identifier for each file record')
    rollout_id = Column(Integer, ForeignKey('rollouts.id'), nullable=False,
                       comment='Which rollout created this file')
    relative_path = Column(Text, nullable=False, 
                          comment='Path relative to rollout directory (e.g., "main.py")')
    absolute_path = Column(Text, nullable=False, 
                          comment='Full filesystem path where the actual file content is stored')
    content_sha256 = Column(Text, nullable=False, 
                           comment='SHA256 hash of file content for integrity verification')
    file_size = Column(Integer, nullable=False, comment='File size in bytes')
    is_truncated = Column(Boolean, default=False, 
                         comment='Whether file content was truncated for API limits')
    is_binary = Column(Boolean, default=False, comment='Whether this is a binary file')
    created_at = Column(DateTime, default=datetime.utcnow, comment='When this file record was created')
    
    # Relationships
    rollout = relationship("Rollout", back_populates="files")
    
    def verify_file_integrity(self) -> bool:
        """Verify that the file on disk matches the stored SHA256 hash."""
        file_path = Path(self.absolute_path)
        if not file_path.exists():
            return False
        
        try:
            with file_path.open('rb') as f:
                content = f.read()
            
            actual_hash = hashlib.sha256(content).hexdigest()
            return actual_hash == self.content_sha256
        except OSError as e:
            # File system errors (permissions, disk full, etc.) should not be hidden
            # These are unrecoverable and indicate serious problems
            raise RuntimeError(f"Failed to verify file integrity for {self.absolute_path}: {e}") from e
    
    def read_content(self) -> str:
        """Read and return file content, verifying integrity."""
        if not self.verify_file_integrity():
            raise ValueError(f"File integrity check failed for {self.absolute_path}")
        
        with self.absolute_path.open(encoding='utf-8') as f:
            return f.read()
    
    @classmethod
    def compute_file_hash(cls, file_path: Path) -> str:
        """Compute SHA256 hash of file content."""
        with file_path.open('rb') as f:
            content = f.read()
        return hashlib.sha256(content).hexdigest()


class GraderRun(Base):
    """Grading results for a rollout."""
    __tablename__ = 'grader_runs'
    
    id = Column(Integer, primary_key=True)
    rollout_id = Column(Integer, ForeignKey('rollouts.id'), nullable=False)
    overall_score = Column(Float, nullable=False)
    overall_rationale = Column(Text, nullable=False)  # Full rationale stored
    graded_at = Column(DateTime, default=datetime.utcnow)
    grader_model = Column(Text)
    grader_reasoning = Column(Text)  # JSON of OpenAI reasoning
    
    # Relationships
    rollout = relationship("Rollout", back_populates="grader_run")
    facet_results = relationship("GraderFacetResult", back_populates="grader_run")


class GraderFacetResult(Base):
    """Individual facet scores within a grader run."""
    __tablename__ = 'grader_facet_results'
    
    id = Column(Integer, primary_key=True)
    grader_run_id = Column(Integer, ForeignKey('grader_runs.id'), nullable=False)
    criterion_id = Column(Integer, ForeignKey('grading_criteria.id'), nullable=False)
    score = Column(Float, nullable=False)
    rationale = Column(Text, nullable=False)  # Full facet rationale stored
    facet_order = Column(Integer)
    
    # Relationships
    grader_run = relationship("GraderRun", back_populates="facet_results")
    criterion = relationship("GradingCriteria", back_populates="facet_results")


class PatternAnalysis(Base):
    """Pattern analysis summaries for iterations."""
    __tablename__ = 'pattern_analyses'
    
    id = Column(Integer, primary_key=True)
    run_id = Column(Integer, ForeignKey('optimization_runs.id'), nullable=False)
    iteration = Column(Integer, nullable=False)
    input_rollout_count = Column(Integer)
    summary_text = Column(Text, nullable=False)  # Full analysis text stored
    created_at = Column(DateTime, default=datetime.utcnow)
    tokens_used = Column(Integer)
    analysis_reasoning = Column(Text)  # JSON of OpenAI reasoning
    
    # Relationships
    run = relationship("OptimizationRun", back_populates="pattern_analyses")
    rollouts = relationship("PatternAnalysisRollout", back_populates="pattern_analysis")


class PatternAnalysisRollout(Base):
    """Many-to-many relationship between pattern analyses and rollouts."""
    __tablename__ = 'pattern_analysis_rollouts'
    
    pattern_analysis_id = Column(Integer, ForeignKey('pattern_analyses.id'), primary_key=True)
    rollout_id = Column(Integer, ForeignKey('rollouts.id'), primary_key=True)
    rollout_order = Column(Integer)
    
    # Relationships
    pattern_analysis = relationship("PatternAnalysis", back_populates="rollouts")
    rollout = relationship("Rollout")


class TaskRepository(Base):
    """Repository requirements for tasks, extracted from git_repos field."""
    __tablename__ = 'task_repositories'
    __table_args__: ClassVar[dict] = {'comment': 'Git repository requirements for each task'}
    
    id = Column(Integer, primary_key=True, comment='Unique identifier')
    task_id = Column(Integer, ForeignKey('seed_tasks.id'), nullable=False,
                    comment='Which task requires this repository')
    repo_url = Column(Text, nullable=False, comment='Git repository URL')
    required_commit = Column(Text, nullable=False, comment='Required commit hash or ref')
    is_main_repo = Column(Boolean, default=False, 
                         comment='Whether this repo should be symlinked to /workspace')
    mount_path = Column(Text, comment='Container mount path (e.g., /git/git@github.com:foo/bar)')
    
    # Relationships
    task = relationship("SeedTask", back_populates="task_repositories")


class DockerLayer(Base):
    """Tracks Docker layers built for repository requirements."""
    __tablename__ = 'docker_layers'
    __table_args__: ClassVar[dict] = {'comment': 'Docker layers built for git repositories'}
    
    id = Column(Integer, primary_key=True, comment='Unique identifier')
    layer_tag = Column(Text, unique=True, nullable=False, comment='Docker image tag')
    repo_url = Column(Text, nullable=False, comment='Git repository URL')
    commit_hash = Column(Text, comment='Commit hash (None for base layers)')
    layer_type = Column(Text, nullable=False, comment='base, merge_base, or commit')
    parent_layer_tag = Column(Text, comment='Parent Docker layer tag')
    created_at = Column(DateTime, default=datetime.utcnow, comment='When layer was built')
    size_bytes = Column(Integer, comment='Layer size in bytes')
    
    # Usage tracking
    last_used = Column(DateTime, comment='When layer was last used in a rollout')
    usage_count = Column(Integer, default=0, comment='Number of times layer has been used')


class RolloutDockerInfo(Base):
    """Tracks Docker information for each rollout execution."""
    __tablename__ = 'rollout_docker_info'
    __table_args__: ClassVar[dict] = {'comment': 'Docker execution details for rollouts'}
    
    id = Column(Integer, primary_key=True, comment='Unique identifier')
    rollout_id = Column(Integer, ForeignKey('rollouts.id'), unique=True, nullable=False,
                       comment='Which rollout this Docker info belongs to')
    docker_image_tag = Column(Text, nullable=False, comment='Docker image used for execution')
    container_id = Column(Text, comment='Docker container ID')
    internet_enabled = Column(Boolean, default=False, comment='Whether internet was enabled')
    git_repos_used = Column(Text, comment='JSON of git repositories mounted in container')
    
    # Relationships
    rollout = relationship("Rollout")


class DatabaseManager:
    """Manages database connections and operations."""
    
    def __init__(self, database_url: str = "sqlite:///optimizer.db"):
        self.database_url = database_url
        self.engine = create_engine(database_url, echo=False)
        self.SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=self.engine)
        
    def create_tables(self):
        """Create all database tables."""
        Base.metadata.create_all(bind=self.engine)
        
    def get_session(self) -> Session:
        """Get a new database session."""
        return self.SessionLocal()
    
    def close(self):
        """Close the database connection."""
        self.engine.dispose()


# Global database manager instance
db_manager: Optional[DatabaseManager] = None


def init_database(database_url: str = "sqlite:///optimizer.db") -> DatabaseManager:
    """Initialize the global database manager."""
    global db_manager
    db_manager = DatabaseManager(database_url)
    db_manager.create_tables()
    return db_manager


def get_db_session() -> Session:
    """Get a database session from the global manager."""
    if db_manager is None:
        raise RuntimeError("Database not initialized. Call init_database() first.")
    return db_manager.get_session()


# Auto-update timestamps on updates
@event.listens_for(SeedTask, 'before_update')
def update_seed_task_timestamp(mapper, connection, target):
    target.updated_at = datetime.utcnow()


@event.listens_for(GradingCriteria, 'before_update')  
def update_grading_criteria_timestamp(mapper, connection, target):
    target.updated_at = datetime.utcnow()
