"""initial_schema

Revision ID: 362914e33560
Revises:
Create Date: 2025-12-11 14:08:54.140241

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "362914e33560"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_costs",
        sa.Column("transcript_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("transcript_id", "model"),
        info={"is_view": True},
    )
    op.alter_column(
        "critic_scopes",
        "files",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="List of file paths to review",
        existing_comment="Files to review: set[Path] or 'all' sentinel",
        existing_nullable=False,
    )
    op.alter_column(
        "critiques",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Critique payload (DB model). Conversion to/from MCP model happens in critic layer.",
        existing_comment="CriticSubmitPayload as dict",
        existing_nullable=False,
    )
    op.alter_column(
        "grader_runs",
        "canonical_issues_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Snapshot of canonical TPs+FPs used at grading time",
        existing_comment="Snapshot of canonical TPs+FPs used at grading time. Keys: true_positives, false_positives",
        existing_nullable=False,
    )
    op.alter_column(
        "grader_runs",
        "output",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Grader output (DB model, flat structure).",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "grader_runs",
        "output",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Grader output (DB model, flat structure).",
        existing_nullable=False,
    )
    op.alter_column(
        "grader_runs",
        "canonical_issues_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Snapshot of canonical TPs+FPs used at grading time. Keys: true_positives, false_positives",
        existing_comment="Snapshot of canonical TPs+FPs used at grading time",
        existing_nullable=False,
    )
    op.alter_column(
        "critiques",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="CriticSubmitPayload as dict",
        existing_comment="Critique payload (DB model). Conversion to/from MCP model happens in critic layer.",
        existing_nullable=False,
    )
    op.alter_column(
        "critic_scopes",
        "files",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Files to review: set[Path] or 'all' sentinel",
        existing_comment="List of file paths to review",
        existing_nullable=False,
    )
    op.drop_table("run_costs")
    # ### end Alembic commands ###
