load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "difftree",
    srcs = glob(
        ["**/*.py"],
        exclude = [
            ".*/**",
            "tests/**",
        ],
    ),
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//click",
        "@pypi//rich",
        "@pypi//unidiff",
    ],
)

py_binary(
    name = "difftree_bin",
    srcs = ["__main__.py"],
    main = "__main__.py",
    deps = [":difftree"],
)

py_test(
    name = "test_all",
    srcs = glob(["tests/**/*.py"]),
    data = glob([
        "tests/**/*.txt",
        "tests/**/*.diff",
    ]),
    imports = ["."],
    main = "tests/test_diff_tree.py",
    deps = [
        ":difftree",
        "@pypi//pyhamcrest",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
        "@pypi//syrupy",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":difftree"],
)
