load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "vecm",
    srcs = ["vecm.py"],
    deps = [
        "//augur:frames",
        "//augur/model:exogenous",
        "//augur/model:location_series_sources",
        "//augur/model:provenance",
        "//augur/model:schemas",
        "//augur/model:series",
        "//augur/model/path_models:density",
        "//augur/model/path_models:scenarios",
        "@pypi//numpy",
        "@pypi//pydantic",
        "@pypi//statsmodels",
    ],
)

py_test(
    name = "vecm_test",
    srcs = ["vecm_test.py"],
    deps = [
        ":vecm",
        "//augur/model/path_models:scenarios",
        "@pypi//numpy",
        "@pypi//pytest_bazel",
    ],
)
