# Generic incremental commit layer Dockerfile
ARG PARENT_IMAGE
ARG TARGET_COMMIT
ARG REPO_MOUNT_PATH

FROM ${PARENT_IMAGE}

WORKDIR ${REPO_MOUNT_PATH}
RUN git checkout ${TARGET_COMMIT} && git clean -fd

# Create /workspace symlink if this is the main repo
ARG IS_MAIN_REPO=false
RUN if [ "$IS_MAIN_REPO" = "true" ]; then \
        ln -sf ${REPO_MOUNT_PATH} /workspace; \
    fi