load("@rules_python//python:defs.bzl", "py_binary", "py_library")

exports_files(["pyproject.toml"])
py_library(
    name = "gnome_terminal_profile_switcher",
    srcs = glob(["src/gnome_terminal_profile_switcher/**/*.py"]),
    imports = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//absl_py",
        "@pypi//dbus_python",
        "@pypi//pycairo",
        "@pypi//pygobject",
    ],
)

py_binary(
    name = "switch_gnome_terminal_profile",
    srcs = ["src/gnome_terminal_profile_switcher/__init__.py"],
    main = "src/gnome_terminal_profile_switcher/__init__.py",
    deps = [":gnome_terminal_profile_switcher"],
)
