load("@rules_python//python:defs.bzl", "py_library")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "host",
    srcs = glob(["**/*.py"]),
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//mcp_infra",
        "@pypi//aiodocker",
        "@pypi//fastmcp",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":host"],
)
