---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: twin
  namespace: gatus
spec:
  interval: 24h
  url: https://twin.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 15m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: gatus
      version: "1.5.0"
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: gatus
  values:
    externalConfigMap: gatus-config

    envFrom:
      - secretRef:
          name: gatus-ollama-api-key

    ingress:
      enabled: false

    persistence:
      enabled: true
      size: 200Mi
      storageClassName: local-path

    serviceMonitor:
      enabled: true

    nodeSelector:
      topology.kubernetes.io/region: hetzner
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
