"""Python detectors package."""

load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "py_detectors",
    srcs = glob(
        ["**/*.py"],
        exclude = [
            ".*/**",
            "tests/**",
        ],
    ),
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//pydantic",
    ],
)

py_binary(
    name = "py_detectors_cli",
    srcs = ["__main__.py"],
    main = "__main__.py",
    deps = [":py_detectors"],
)

py_binary(
    name = "py_detectors_custom",
    srcs = ["cli_custom.py"],
    main = "cli_custom.py",
    deps = [":py_detectors"],
)

py_test(
    name = "test_py_detectors",
    srcs = glob(
        ["tests/**/*.py"],
        exclude = ["tests/fixtures/**/*.py"],
    ),
    data = glob(["tests/**/*.md"]) + glob(["tests/fixtures/**/*.py"]),
    imports = ["."],
    main = "tests/test_detectors.py",
    deps = [
        ":py_detectors",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":py_detectors"],
)
