"""Python detectors package."""

load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

exports_files(["pyproject.toml"])
py_library(
    name = "py_detectors",
    srcs = glob(["src/py_detectors/**/*.py"]),
    imports = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//pydantic",
    ],
)

py_binary(
    name = "py-detectors",
    srcs = ["src/py_detectors/__main__.py"],
    main = "src/py_detectors/__main__.py",
    deps = [":py_detectors"],
)

py_binary(
    name = "py-detectors-custom",
    srcs = ["src/py_detectors/cli_custom.py"],
    main = "src/py_detectors/cli_custom.py",
    deps = [":py_detectors"],
)

py_test(
    name = "test_py_detectors",
    srcs = glob(["tests/**/*.py"]),
    data = glob(["tests/**/*.md"]),
    main = "tests/test_detectors.py",
    deps = [
        ":py_detectors",
        "@pypi//pytest",
    ],
)
