apiVersion: v1
kind: Secret
metadata:
  name: mitmproxy-ca-cert
  namespace: openclaw-mitmproxy
  annotations:
    description: MITM proxy CA cert for sandbox HTTPS inspection
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: claude-sandbox,openclaw-sandbox,openclaw-gateway
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: claude-sandbox,openclaw-sandbox,openclaw-gateway
type: Opaque
stringData:
  mitmproxy-ca-cert.pem: ENC[AES256_GCM,data:zxPn/5lfav3yEobu0BqiUXAyeMfy2YF2HIqw/fZfnYq3Nx7EMDEa9E1WePy8iigosMQFbA7+0h+IyLUJJDgljSPGikIuExwm5IW89ADx0st+Ow/nZBdPhKU4/VRB4D/s9iDPQwdQempzeyIsdnczap/o2h+GFilJjgXujo0RJF0i3wfoBnEIyLDqk5JJECYgQuQv+lHjuqOZNkD+ctKnbkRpygDXLcUje1hTJdE6k6R/R4FWhwx+Kny2T232OutiLKD/U2wW7pC6nPn/jAx0Ry3pP0ICI9r2ZjbJLlktiOORU8ziGUCXsYveAD/bqZGBGlSxh41yT/2EdLxqEqGERUC3e1pjnIvIYGtihedsqgunxZp7wCYgHZXn+taT1oyQiaYyi9rURLwEC7jtU4F7fslkPJgqKPYJkJyS62gsj8b6j9gSQcfQlq+AW+AkXUDyOXPsXf9k5T7hlDrueCU4q6yuZj3BUiqkhkbMRHiLU2eerUiw+KbSpSUi+b5wj7Z4kae+3siDKHxv5Q5Ln1kcYNe4AsaSFKrIsJOcHzykwxJ5puGf3GNBX26p+M5cPrPYuZgustkGVenAkKnA9LUDPFiZmKXNOuiTmrbXUKG4LKmMsnlnF1yulHWNdxOKDjsE90JuUiNC9s23UZdfYlks6ZiQUAvtYUUKHASlC3DdR5Me8/6WknDDOU7KaaPS67mzSUcT1IanzKNIKVLNL6NfTqIezl+eC9ivPx9Cu5byVF8Of2Gwj2JZ2NWfMj4373V+fo0uAQViQRXbAdpfYcYp4816dsiKGY6/Y7BZvzGj04gu3O5o+geqrq7m8PPEGUXLEFYF/dbPzQhkKtYKdkAw9gazh/K50plAxiPXSC22kJDxC9WmRdca449fGgly3JQnG9HsR7/HM8y/ApL/O4qJjODJcJyTzRHSVasEPZDYZWw5w9p/vl5PHC7pbvUpe7jx8igRWqnjLPW6Rv7zlPAdKNjUu2zKBRN8nZ2PjHi4QgzNu1Kr//lwQksYXNQVRjpLjEcBlskprYw7gDHd1/ey4BM6RipBY+6EaFyiBT5c2TgyC9vlnVp4AM4ifwfycVScwzeLb/IhNPovGmwH0o2nvMbbzaEoSEF5O/iU1QyDH4MqMr6YVafqO+jC5gplAS7hIVi6a7tS+lb6N8YsIF6AJ3vWefy+HWpfE20i0Bx1E0Z6tYnXzjnJT2UsieOEEf8YYloTRpE89COT4u6sm6G4RcMt5ixMTmnra4D2Bwjq9xDK9O7B83/k/npljupDsMddjB7LVppn0l8bviqZxyDE42jSfNONR5M9qGwbj2HeBeGgCgevVsZRUL0cXwz9VftesyiSLXEP+TuEqgEQUj+b+ER/xHqKJ5N4Bfi6OdU4B9IBczBhVvd+Yk/0pO20TbIkMnnbPrdRbNBOTmAUEPvGDAYU4ObI5CgTxjO6ARlihdq/mmQ8dZQbQRdWaBBjBeCtjLivOxZVZfLATjJ82rjy+cuV8JOtQOyDwwoBKvhkmubfejYYprDSe/PfS68GVjVp14wvvHxL8ViN5zKMbQ/JqA==,iv:wIPDihtOFxFPCZt5IWWWCqmbr64auFgzmjaMPZwintk=,tag:G+TOzxfSOSsMGtpMisMNUQ==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQnVBS042SlNwc0RFZkJC
        dTM0QzdOc3o0bUxCRE5VSUtpdDJ2dWZ0Ulg4CkJSKzNtaFdzajJXZCtoeEdMRmJN
        b00xUTdrRVNHbmczaG00WU9hUTdpbncKLS0tIFhDejBtRDE3NTIvTEpEaDBsMGkr
        NE1GckxtK2ZXeGJoOGZuRzR2d2NSZGMKPqaYnfuxDk0hexZAAltQN5yyMel8YdWi
        feBGGPmzgu/fh6HP+OnwzQXWgiCtHfIpfbo8F82cqD7JcDX+9fccxg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Sjhva0dPVEpQclpreTdB
        NlM0LzVsaHhBTSsxM3h3UzJDRVIyUEcxN0hBClpvRFlIbGVUTmp4aDN5YkpxZFNt
        WVdpRDhmeUZMRkR6ME82bWJaSVVOOWcKLS0tIDFGK01JSFVJcEJiQlhaTTFZZXZP
        MVVzbXUwamk3b3d2cmpxazVBOUVEVzQK6wAIbIZGW/ifheEq6X2+IFlWavsszZ3c
        w2VNfmFxBAejbvCxQjFfdG+fX1imSDOMViyEv4bCmHOl8Qh1O5b54Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:17Z"
  mac: ENC[AES256_GCM,data:w7nzY595kFkI/knaypaNthJKoNFxjrtBPiL5I0gGWGx2x9yrIRGA+fFFrLhULICE63tTugDvNxDbpQxWHG0z/oBaVif+/VZu/EkQ1Gbay5prqtpHAYSGgwPlpOc1Deendi9B/U1JCq9EwJ+s4NKdxxNX+iuD4zegbVGEg97lvkw=,iv:yS5dpAwyOBocEDyTM1a8drz9w0zNA1rYe3+N8AemVpo=,tag:DR3qX8qMntQindYQ3OViqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
