apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-data-pvc.yaml
  - openclawinstance.yaml
  - clusterrolebinding-flux-reader.yaml
  - clusterrolebinding-diagnostics-reader.yaml
  - rolebinding-ollama-consumer.yaml
  - rolebinding-props-reader.yaml
  - networkpolicy-authentik.yaml
  - networkpolicy-node-ingress.yaml
  - cnp-cloud-api-egress.yaml
  - cnp-kube-api-egress.yaml
  - rolebinding-gatus-reader.yaml
