apiVersion: v1
kind: Secret
metadata:
  name: claude-forgejo-tea
  namespace: claude-sandbox
  annotations:
    description: Forgejo API token + tea config minted by forgejo-token-rotation.
type: Opaque
stringData:
  config.yml: ENC[AES256_GCM,data:oN0VlVWDikN7Deal+PyYz9OfLk74h+hANT+JbMeRy4eSq6J3c2m1neZdzVrnS93oc03qC5vfgydS/b4kSzEesfF1QNYPXrShgquSsm/l9u+YiRIV92pexfgkQRPQh1djuK9oAJYKV42MNko8DM31+GD1+K3PMaDbgKmMTwE0gxoFD3p7I0NbU6T0brjZ2LDl2HZTIqi/vAQseUTjpQDXAc1n7g==,iv:xnj7UYMb9XUM9eIBwAZ89NFfLtVIdu+R8JChAf/Mm+c=,tag:eivT2lJlyB9Kt8TuGcJ4bA==,type:str]
  token: ENC[AES256_GCM,data:TZv/zhIw1VOaVntJGRRVecLeP6CvIaBsnUqPWIikgAba5Zmh1+KIsw==,iv:NeBoBfj9saTHITcHI5IAHMgL2LptiOPQJXbMhm1GSCw=,tag:MITc8FyaZPlDuDJmKfSOzQ==,type:str]
  username: ENC[AES256_GCM,data:+Gun+zYR,iv:XC0+WJoKk7ipKaalreQlDtpTbfq2p5dfw2Ns1lg2wA8=,tag:WlceC1LWKxq59JxzanAt2w==,type:str]
  url: ENC[AES256_GCM,data:dobZhouuM3POU4HPXCueHwtOTmsw1pWAEMdQ,iv:BkTtUH/Z5x/KlPR3grCRKEHEwfOGWcnAflToGvrEYO4=,tag:pLHsz7eNBEol0asi0dGHXw==,type:str]
  token-name: ENC[AES256_GCM,data:ina5EwDjefCt22CczIrbUPn9zxr08IW/N1CStuwGnlPTNH+2Uqd/,iv:ryuhdZHpLLvoDeNUnC24IfRLIjVEhAQPoP+cMSJ0wV8=,tag:VQk5OJLWAfvo0id7uoKB5w==,type:str]
  token-last-eight: ENC[AES256_GCM,data:HUlu+lJhgEw=,iv:pZbdfuBa5K4ixhPVGCGXXhT/d+qaJk0iIV0Igwj2LM4=,tag:qXEM0eNusM5oYaIJTHgu3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRXk4Ymc1WDV1Ty83aGVy
        enovWTlORUVkWG5RbDVHZGZsZGFoWlpiaGkwCngvU2RWalEvVjZkeG56UFN5Risr
        N3JiWmZkRTBlbHRuY3ZhNE44SUFmY1EKLS0tIDM5SmR3VW12dHFDN3BqTHUrQzVN
        OXhkY1REbG1NMmh3RFpCYjFldkZIeUUKUZS4m3JA2nyK6lHYRashClXhVREgSdfJ
        IHr+5Cfo8fuWddAGOL9sAKMlfKE0sIVc8krbqKci0uJ6kGeqK5WEVg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bWxsVGM4K2xaU2pXS20x
        R3B6N2hqVElxZSs4SkJ3OXVWSzZyQzBUZDBVCmVlaXlXbTUybXBMTUh1aHI3WnZj
        Tmw3VktLU3ZlcEJDN3N6VURqMDM0T2MKLS0tIDYzWW1BM0ZDSlFsTk1vYmhXMVl5
        YXFaeWRXaDJCdjJHaFFnczF1Y0h0bzgKDxfMr7BLz8QGrc83l8VGu16aEEEYB3Qk
        ptLxJsjs9YhnZJQvKIMMqBsJmiZlMz7pEMwXhyjjIH/aSLGoLZ3+hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-03T02:35:11Z"
  mac: ENC[AES256_GCM,data:dHdkcorWfnuXJdohLRfoG3gx8SUs+FnKCj4vl8aS1OHG7L9qLASuTASS5ocfBmJ0Sa4QgxXqFYPkKLFoRtRiSwB74V+mhq17kcMyn2ZLbDGKQUD0adGC0eIau2yhI6ZFt6GeiLbLkSQKeDoOOL7Zad+6d5KNhHMQa8T7CF9NBpg=,iv:gSO+TCXQSOBa9G4Yv0dxy+ATXaa2lI9CANvvqGgXEoA=,tag:leu9GD6DZXpboj1OcgAVIg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
