apiVersion: ENC[AES256_GCM,data:kEw=,iv:Rw+Z4HZI/jh4+HiKOR+syz0ZpY4S9tBJ6Jqb0zJUx7k=,tag:GEpaGH1xQs6bBW+ibs8uTQ==,type:str]
kind: ENC[AES256_GCM,data:iZt6Y1K7,iv:7P6j823cVBpU9Lc6NRj+nUPCuipvouNxYbtPoxRbTUk=,tag:bjG8oJV76WyyEDQZD7rRTg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:pVQFSqvNZwMMsrQFyN2THW+u,iv:ObUHpQgPmae6DbhpSD1ycy35HzJmceJc1IALznDqsic=,tag:tvr5kyz7KryzcfuRnxvPbw==,type:str]
  namespace: ENC[AES256_GCM,data:sHxMMRXXsBq4U3cDea0=,iv:WhtedtJfdIH9jCXhA9TX6qQVU4ujkhPX2GWUAhpKgNI=,tag:Catg519qdrLPEf/oaNvoDg==,type:str]
  annotations:
    description: ENC[AES256_GCM,data:mjzt++lrCk4TjmuKiPUUqXbi9naaF3JMNP4HWZQ24QdiWyHR6m1Eeh7ViEH+OLx0vwhn6sNv9NB2GZ7x4mcR,iv:dnJcvrGT6KicGBEeLRmY6CgIdqPXrTfoxv7GbmRUabE=,tag:GrE5j6wDv2ERL9HOWucRDA==,type:str]
type: ENC[AES256_GCM,data:1CsNfBZb,iv:DyLjmUlPX43GEzuJf+/M6taPVSFQHOWdwBfOBToZcCI=,tag:ukPVI1RVRej+MOnN+eLrfQ==,type:str]
stringData:
  age-key: ENC[AES256_GCM,data:dILNMUjn4koFlD8mzivEjd9jUjpqgUkG+A/YOsVnOnTRR3aWh5UH1AgaJrBalUjI6irnWaVFIDdGh6OV3UhpCT+Ei7RStnRzNXg=,iv:QAEdCAT2wQJcT5Dbqh1fNevaHt9P86F4nA5NFBR3n7Q=,tag:mce33QOomFRPPCwVJXAxxQ==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dUh4dko4NngyTG56eHVo
        Z2hrSjBTaE8vSTdvMDFFek41VURqL1FsTTJVCkJPSFkxY0MwU2tJeEZieUFUVDhD
        U21rK3RZaHcvTUtrc28xZ0o5NS9xU1UKLS0tIHR5QnNwODlDQk5HbGx6KzdUem91
        ak5zSGFJOXplRXFSZ2w5c1krQkcvR1EKJmSjyzyGxxGtOnKs3KmfobZ13xD8Wm5+
        Xarp2Cz9KDdcs+hZMbxbXOrl+8tnc8diHfwINvrrHWAmih4bmdVKKg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eGN5andQbEl4bjVCYmZi
        QjJJK2ZvQXRucTlUdVRZRHVOVklrRnFSWXhRCis4Vlc2V0pvSWlyS3dETzRIOXpr
        d0cxMHNNR2dUaXMwdEc2dUZWWGxNMmcKLS0tIDZPM0RJMTVrZEtQODAreHZoVTZS
        RTNCZDdscGY1VWNrVnlPeGVXWnNBOXMKD7avQGJRKEULU0pmTcnWbQHZ4PYp5lG6
        ChgGzNhz99DPviYFoITnOCm057RXGOi8lGbKdUr9PpXG/vr5BjOQNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T06:55:29Z"
  mac: ENC[AES256_GCM,data:IzkHcqnRIBJQiasEfgdtPVcB2UnslPpVzGh23kxFaInpKKHueV1uKFfY11opaDJ+FH1DV7zwjDW0jNtcatMotcIgUKOUjp3fDq7wXEUdY6R4usn7XYKgf3TDxoYuA5QOniRdsrFUWssk5vZDt1oMG7jYzy9X10er4j+BKdG/rU8=,iv:k/WtvCjCN3ALGkTryjvOgLaTHOLREKNQw2NdgDzeK+A=,tag:4NcAD8dGUlOmAuJlz4qvMw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
