apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-auth
  namespace: registry
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    htpasswd: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: registry-auth
      namespace: registry
    type: Opaque

# How to generate:
# 1) htpasswd -nbBC 10 registry 'YOUR_PASSWORD' > htpasswd
# 2) kubectl -n registry create secret generic registry-auth --from-file=htpasswd=./htpasswd --dry-run=client -o yaml \
#    | kubeseal --format yaml > k8s/registry/sealedsecret-htpasswd.yaml
