---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-openai-api-key
  namespace: openclaw-gateway
  annotations:
    description: OpenAI API key for OpenClaw LLM gateway (api.openai.com)
spec:
  encryptedData:
    api-key: AgBtmg5h0IBrz2QvctvcDSvzbR/0o+ouZeFJAz0bOhoDpCUfeg+AxNX8iqbBIj1hu/VXZ0imdh21LxyIcWbBDhel6Zz17smBq9uGRgrPqayL2wAJLBKZztMc5qvOJY7L5yZGGPtclp4pgf+SG8Pjmf+ua27qTVV6OEYaItDev5/9Te12ZokkQKeaV8HHwKJrs7SWaU7LfwaQ+Vb4SNC7uF5pNUOkxqW9E5LDBCVVxD4I5kV/Bogk77bo21NSDBUu4eCsxNkSyAwTJfitZVX8mZtA7vALBT8mbjiOoljsr7wHrpTS0ON5tU47eT7T8udRHqPw7M6H+8ChbfeaqaAGzCA8Rg4uR/YYjRZL6mMyMwvZBTmvJ28t5Ak+0ZIbCSjUKJNN9hEaJ1bn2S5u1DejNYeHd6V5oKVSEt6goOurIy7WR7X2zd8DXQG1abizMWv/4eGoZnm3iDItDOlO2oTJW9laT3YIDSjnJNCoLzFdd18Mfb5R5Ksi/Y8oDAnxaO7JN6S+bc+9DqZKZK7Lf4nOb19BwLu1vYyaOWuhPlr3s9EoXwiTLFIOm0V3VcVEFKqHcdLOKiZt/Ja9zjUv4Qr6b3QQ8bTYatd1NTX84Gm6Ug0VMSmIehkeYnDRiWjCKuV0mA9Jkd9pTNMVMqOwlBetqrw/fMlCspuwN2YzT+54r8dbGrQGF8lyFvLpIg3h0NM+2dkUi+NOsW3FoH8I4VUQP8zPEhtUxTwBJt8ZALkV/GspIATi1OvxKVeh3kYy0SUfXX8sS9B9XlMi3PRiz5hzX1vNE1DXLqtf9tQm/gmEPaS0ge/PawbeCWbfHaQmEWQjcFxuiOZMh3lQoo3Y+nj5yeTyhS3lQmj4k9Ht5ea9LX5NujCKyhh4dhGdAY+dA9p4IigVfapK0tgOoLh2aYDzHhUpZoI55g==
  template:
    metadata:
      name: openclaw-openai-api-key
      namespace: openclaw-gateway
