load("@my_deps//:requirements.bzl", "requirement")
load("@rules_python//python:python.bzl", "py_library")

py_library(
    name = "gnucash_util",
    srcs = ["gnucash_util.py"],
    visibility = ["//finance:__subpackages__"],
    # TODO: add gnucash
    deps = [],
)
