apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-api-key
  namespace: dns-system
spec:
  refreshInterval: "0"
  target:
    name: powerdns-api-key
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "external-dns,cert-manager,powerdns-operator,flux-system"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "external-dns,cert-manager,powerdns-operator,flux-system"
      data:
        powerdns_api_key: "{{ .password }}"
        PDNS_API_KEY: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: powerdns-api-key
