
- name: Set sloppy focus (focus follows mouse)
  ansible.builtin.dconf:
    key: /org/gnome/desktop/wm/preferences/focus-mode
    value: "'sloppy'"
- name: Minimize - maximize - close buttons
  ansible.builtin.dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "':minimize,maximize,close'"

- name: Set Ctrl+Alt+T shortcut to open terminal
  ansible.builtin.dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/terminal
    value: "['<Primary><Alt>t']"

- name: Enable GNOME Night Light
  ansible.builtin.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/{{ item.suffix }}"
    value: "{{ item.value }}"
  loop:
    - { suffix: "night-light-enabled",     value: "true" }
    - { suffix: "night-light-temperature", value: "uint32 2414" }
