
- name: Set sloppy focus (focus follows mouse)
  ansible.builtin.dconf:
    key: /org/gnome/desktop/wm/preferences/focus-mode
    value: "'sloppy'"
- name: Minimize - maximize - close buttons
  ansible.builtin.dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "':minimize,maximize,close'"

- name: Set Ctrl+Alt+T shortcut to open terminal
  ansible.builtin.dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/terminal
    value: "['<Primary><Alt>t']"

# This makes Ctrl+Alt+Up/Down switch workspaces and Ctrl+Alt+Shift+Up/Down
# move windows between workspaces.
# TODO: clean this up, I don't use some of those bindings
- name: GNOME ctrl+alt+* for workspace stuff
  block:
  - ansible.builtin.dconf:
      key: /org/gnome/desktop/wm/keybindings/move-to-workspace-down
      value: "['<Primary><Shift><Alt>Down']"
  - ansible.builtin.dconf:
      key: /org/gnome/desktop/wm/keybindings/move-to-workspace-up
      value: "['<Primary><Shift><Alt>Up']"
  - ansible.builtin.dconf:
      key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-down
      value: "['<Primary><Super>Down', '<Primary><Super>j', '<Primary><Alt>Down']"
  - ansible.builtin.dconf:
      key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-up
      value: "['<Primary><Super>Up', '<Primary><Super>k', '<Primary><Alt>Up']"
