# TODO: get once, reuse
- command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Google Chrome
  # no i386 included
  when: ansible_architecture in ["amd64", "x86_64"]
  block:
  - name: Add Google Chrome APT repository
    become: true
    ansible.builtin.deb822_repository:
      name: google-chrome
      uris: http://dl.google.com/linux/chrome/deb
      signed_by: https://dl-ssl.google.com/linux/linux_signing_key.pub
      suites: [stable]
      components: [main]
      architectures: ["{{ dkgp_arch.stdout }}"]

  - name: Install Google Chrome apt package
    become: true
    ansible.builtin.apt:
      pkg: google-chrome-stable
