- name: KiCad
  block:
    - name: Enable KiCad 8 PPA
      ansible.builtin.deb822_repository:
        name: kicad-8
        uris: https://ppa.launchpadcontent.net/kicad/kicad-8.0-releases/ubuntu
        suites: ["{{ ansible_distribution_release }}"]
        components: [main]
        signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFAD7A805
      become: true

    - name: Install KiCad
      become: true
      ansible.builtin.apt:
        name: kicad
        state: present
        update_cache: true  # deb822_repository doesn't reliably trigger apt cache update
