- name: Set Night Theme Switcher to also switch gnome-terminal & nvim colors
  # TODO: dedupe
  block:
    - ansible.builtin.dconf:
        key: "/org/gnome/shell/extensions/nightthemeswitcher/commands/enabled"
        value: "true"
    - ansible.builtin.dconf:
        key: "/org/gnome/shell/extensions/nightthemeswitcher/commands/sunrise"
        value: "'set_light_theme'"
    - ansible.builtin.dconf:
        key: "/org/gnome/shell/extensions/nightthemeswitcher/commands/sunset"
        value: "'set_dark_theme'"
