- name: Install SyncThing
  become: true
  ansible.builtin.apt:
    pkg:
      - syncthing
      - syncthing-gtk

- name: Autostart Syncthing-GTK
  import_tasks: autostart_entry.yml
  vars:
    exec: "syncthing-gtk --minimized"
    name: "Syncthing-GTK"
    icon: "syncthing-gtk"
