- name: Install Tana desktop
  github_release_install:
    release_spec:
      repo: "tanainc/tana-desktop-releases"
      version: "latest"
      acknowledged_version: v1.0.31
      asset_pattern: "tana_.*_{{ dpkg_arch }}\\.deb$"
    method: deb
  become: true
  when: dpkg_arch == "amd64"
