# ActivityWatch talks to VPS, not localhost
# For reporting to webhook
#
# ActivityWatch devs strongly discourage talking to remote servers and SSH tunnel is the one current ~secure way.
# See: https://docs.activitywatch.net/en/latest/remote-server.html
- name: Install ActivityWatch via dpkg from GitHub
  become: true
  github_release_install:
    release_spec:
      repo: ActivityWatch/activitywatch
      version: v0.13.2
      acknowledged_version: v0.13.2
      asset_pattern: ".*-{{ ansible_architecture }}\\.deb$"
    method: deb
  tags: activitywatch

- name: Start and enable ActivityWatch tunnel
  ansible.builtin.systemd:
    name: aw-tunnel.service
    scope: user
    state: started
    enabled: yes
  tags: activitywatch

# aw-watcher-ask --interval 45m --jitter 15m --question "How focused are you? (1-5)"

# TODO: maybe: pipx install aw-notify -- auto notifications
