---
# Dependencies of dconf module.
# https://docs.ansible.com/ansible/latest/collections/community/general/dconf_module.html#notes
- name: Install dconf dependencies
  ansible.builtin.apt:
    pkg:
      - python3-pip
- name: Install Python packages for dconf
  ansible.builtin.pip:
    name:
      - psutil

# TODO: hmm, what WM did I write this for again?

- name: Configure custom datetime indicator
  community.general.dconf:
    key: "/com/canonical/indicator/datetime/{{ item.suffix }}"
    value: "{{ item.value }}"
  loop:
    - { suffix: "time-format", value: "'custom'" }
    - { suffix: "custom-time-format", value: "'%Y-%m-%d %H:%M:%S'" }
    - { suffix: "show-week-numbers", value: "true" }
