load("@rules_python//python:defs.bzl", "py_library")
load("//devinfra/testing:defs.bzl", "py_test")

exports_files(
    ["rect.py"],
    visibility = ["//skills/freecad:__subpackages__"],
)

py_library(
    name = "rect",
    srcs = ["rect.py"],
    imports = ["../../../.."],
    visibility = ["//skills/freecad:__pkg__"],
    deps = [
        "@pypi//freecad_stubs",
    ],
)

py_test(
    name = "test_rect",
    size = "medium",
    srcs = ["test_rect.py"],
    data = [
        "//skills/freecad/conda:freecadcmd",
    ],
    imports = ["../../../.."],
    deps = [
        ":rect",
        "//skills/freecad:conftest",
        "//util/bazel:runfiles",
        "//util/testing:undeclared_outputs",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
