apiVersion: v1
kind: Secret
metadata:
  name: loki-minio-credentials
  namespace: loki
  annotations:
    description: MinIO credentials for Loki chunk/index storage
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UCAJZ9UdQ6W5JVDSPJI7Lg==,iv:xAqYfs7UaXn9fUxTH4H3l9AoL5L7TCXxUHHLvPLLTTI=,tag:pCEYgQ5gftuqSEn1utzjtA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vauuWNYnC8gtqAfQIfLtdxQU4UyEjbDnazMMCCBXYe01TDXmZToK8OeVTA==,iv:iqtULO/ac8IbLlcn2hgrRiRRZbVwFXlWJGdVDI3s2xc=,tag:OAvM0aIWDKCza3CCa9PWZQ==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYkdpR1B0TWx6M2k4ZzNB
        Y2VpT1NnSkhIYjVnOWxnZWlnTm1IL3RjS3d3Ci9ORUU0cFc3dEkxMjVIQjFGaE5x
        Z3plNEZ6L2ZaK1VTZlh0OG9PYk1lWEUKLS0tIFdyYzdzZGZaWDRhVm96a3gzRFZv
        dXVBZE5kbm1CTTJoT2hOc2xGQ1lya1kK+EUZP9StXmPyKbOLV4uOKAKCnE3Aj1jR
        7S4fjdwTjEjlUSfG3Pf3wGJyu8WzaE24ynOfwMigoX5zfLaON59skg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdzl3T254VFJUSzZjZXFU
        cE9pTXNqZ3ViWmJLRTFXeXBmdXU5RlMwUUJRCkFGVTIvVm0yMVNJSkZlNURkeU95
        cW9WazVlTzZCZm1nK1gxcDlZSDlpM2sKLS0tIFBzZmEyaGlkdG1mc21jODdiazhY
        Q3VvREZ6M2ZBS0Q0U0tjNGM5TVlpckUKuLApYdYHoIZAydnk6CatUTA+WKBu6sCE
        tYU76Dzu2IQwEAWrRI9F5nkmz0zPhksfvrJ9gWvRnB7jSiQzjrDY0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T05:07:58Z"
  mac: ENC[AES256_GCM,data:r5um553oEHYDXNAs04h4UQ78QdwaI2sy7+/jdFI+8nGlTAFmx+v8bnEHxlWFfA/lWlLJb1/5qkhVaek7KNOh0yTPFCGdvwPZZdGSLCfdSxKAu0J7rSEu3QcqRa4HCUXXs+X19h+6vrDan5FgAzY2yE8xLgdFAIINE7+isF8ev2c=,iv:ISl/jFSwflgf0rRB3GLXjp3YvU5wHfY3whLs9MFDlxU=,tag:zK5dmmHYbDDM8Mx4Zk6gRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
