# Loki's S3 credentials for SeaweedFS. Matches the "loki" identity in
# cluster/k8s/seaweedfs/secrets/s3-config.sops.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ajKrEmak4++9372pQo5VLE1mUkA=,iv:pedcaN9vWmueKNbgX05/eAzZV6P0Pg6ef5egSuYn8qQ=,tag:CnLh8+eCHTSP4krbd1rdQA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XAPBZeTe0V5nu44Ly3Hik3hM02YugvCjYuDar4mGKNLiveFfHNCDiA==,iv:c2vE5VItdGi+5ICvTYw5go+vFq26wyZ+foQljT8EGvg=,tag:89bl8n1tp3xqYSvzaHvqXw==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2akNPNkdPL0V3Vk8rR3dO
            cTVvNTU2TVpMaitjS0dKL0YvL2E2SVgzeGtzCjVUQVFaYkRZR2tKdVBPVXlLVkdL
            dXh2d3d5U3k2YVBSV0g4ZVBrMGxxakEKLS0tIGhDdC9BNHFscjV3VEJVb0FHSk1O
            UEdiSFlMUE9nK0dHdXBwMkJ1WTgyaUUKh8hN054DPmmjaEGv6bCrEPUvMTBfoqR3
            EUHhHGPJMowOqn01EkjYQHvsjDfBmi2N9p+/rOBEiEgahsrOvEgwGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVjFScHlyQk1GUkZHN2JD
            dHp0MmZDUkdrdjBSK2hBclNGRE5pa3NHTG1VCkJUK2RNYVhEY3dOdXRrSEdJMjhX
            WGJHenV2ZHRGN1hnWkhCYVkyZitPckEKLS0tIFFOVSt0UWw1RVpnNFRiOUVYQXhC
            TUhwekdVdHpnb0FaVm52aVgzdEcwTEUKRAkK2dOGSmH7ApYQtYRaMqfyleguF1TX
            ZETw7SFdxn7VUpuS24Dyzr3N54fBeEKA396aBzKDUHZMcsxJkKavkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T08:56:31Z"
    mac: ENC[AES256_GCM,data:mX6EQqO9wt9SRNHhgHwGYyXERRMY4K5b4bKiSjcYsTLrq2E/iMNJUOGm+MOwMWwonyZJyZprw9uCqtbqjRhhXLsf+k50A8L3AirpDmu3j9GxIXrNAn7ubYWZsg0Zv2D21Euikag7YBgpn51remAqz7eZqS1MBk4o0bWAB1W1bC4=,iv:RLqvqGW15RWd+kOlmfjT49sZvcQRBZzNxPthPAOj+lg=,tag:RHLJGMJL6xu6EmRbKEBXLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
