apiVersion: ENC[AES256_GCM,data:Eww=,iv:Lw80I9XYoNDRqA/56mBmzOJgJbvG9/qED/hJUtnLESQ=,tag:469gvCe8NUc7C79/ng4qxA==,type:str]
kind: ENC[AES256_GCM,data:FztU0IEN,iv:JniC0FkkOhP/oTnFrnzgQ0qgHyN6H0A9wcwMlrdbYCs=,tag:Y+npaSLawgXQEB/vQol2vQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dQmLjOeoktOJfw0+8Wq45z5mqgwaeHmdBQ==,iv:72Qudw5NkKJ3vAOHdX09qpGpksJC5BjtKDihsDH0r5Y=,tag:SBf8tzz581X8xBn2yx/OvA==,type:str]
    namespace: ENC[AES256_GCM,data:VN9E1ZTzkQ==,iv:jo1Whrbe9AutSZ9xuwcUdQ3XbHUV9sptCHrs6rpkykg=,tag:CKW5903/gUOlz7+bXL1kKQ==,type:str]
    annotations:
        description: ENC[AES256_GCM,data:qqT7w40pl+lsxK6qNg0rew0ybYOjHalbQz0FcbcfvyE=,iv:rPAcSQ6wK0+Mc8SpDs8njz4sPYGSuMhEzLKOmFA8YLc=,tag:WEEaZNdLOBXShSSBdUwu5A==,type:str]
type: ENC[AES256_GCM,data:ZZPRDSE3,iv:jJhnFcXBN+PGCuX2i1V6AxqbIgewBTugIk/l11/cVAo=,tag:pWcbbJLbevOQAJEr7fBc+w==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:GEnLuccjjH3Lzg==,iv:Gc7vhkVP7BCXFezByCVbOaI456pNINpP8GZHOJRcHSc=,tag:Xp19smG+Z0uyIGKhyVZ/Pg==,type:str]
    client_secret: ENC[AES256_GCM,data:is+h8KOBR34Clg==,iv:gMr2Ht1qbKMeCqzuPpIXiJeC9oL3diEG8TSQK0d2Y4A=,tag:rPl5H64tER5dVrucj5e/WQ==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMFFtd0MwVWxMSkY3WTJo
            b3RTRW56L0orckpGVEtYNVVaWXI2c0JOWUJJCnZRV0pQelB5d0M0endwY2FiZDM3
            Z0ZUYUJHeTJDVjVJL1ByTWRPblFKQkEKLS0tIFVHektGdkEwamphQ2lnTGlWeFRZ
            djk4cUZoaFJZQ3I2QzEwOHdDeXE1UEEKe/cJotAdH8JAn0SLTITWeQUO3TxwgVcY
            HD5RNZnFACqPPocNBmWUlqCNwZWWe/VaoqKFgzVVi8cvAc5CohZiLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVJIUjY5TnUxcGJJMVhL
            RnM2cXRRbUIvYWdtRkU2SS9aQkFTWEVJQVZjCjRqN2ZGS3RaV2tZWHg4cVZzdFZn
            cWVBUUV5ZGdiMjhXZW9LSDdiekJwTzgKLS0tIHFzb2oxSWo3TS93YUdVcXdQRTJx
            VlAvTnRjM24ydWoyVWd4RmZkL2xLY3MKGT/nort3LfydvTalhAcKXrrp85KzsWzI
            6aUwWGrCjbROfcgYKQnEcp7vDrGpdLtog803nvZaYkmWXOdAb14fjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T07:01:40Z"
    mac: ENC[AES256_GCM,data:nKaLd5YqSNDpTIchKndLGUYDvnLfHQu/0hN0vfRevYYIBt2eGamIU1jzuI9ea7N6Tu1S65ZsRiWnltCr6EQBuC6u6RDKPR1JV4hLsyaEZMje/LJKE61073DgKnvaf+jMeoe/dowI8bfplV5FoHKKySKykjuGPgkw+qd5OcFt25Q=,iv:ikEwdtrem5DJQu+HSH434p1dajS+Wc3C74mESbJH5BY=,tag:stTlrIKORKbs5yJOFUCOag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
