"""Props core package."""

load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

exports_files(["pyproject.toml"])

py_library(
    name = "props_core",
    srcs = glob(["src/props_core/**/*.py"]),
    data = glob([
        "src/props_core/docs/**/*.md",
        "src/props_core/docs/**/*.j2",
        "src/props_core/agent_defs/**/*",
    ]),
    imports = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "//agent_core",
        "//agent_pkg/host",
        "//agent_pkg/runtime",
        "//cli_util",
        "//mcp_infra",
        "//net_util",
        "//openai_utils",
        "@pypi//aiodocker",
        "@pypi//alembic",
        "@pypi//asyncpg",
        "@pypi//canonicaljson",
        "@pypi//docker",
        "@pypi//jinja2",
        "@pypi//plotext",
        "@pypi//psycopg",
        "@pypi//psycopg2_binary",
        "@pypi//pydantic",
        "@pypi//pygit2",
        "@pypi//pyyaml",
        "@pypi//rich",
        "@pypi//sqlalchemy",
        "@pypi//tiktoken",
        "@pypi//typer",
        "@pypi//typer_di",
        "@pypi//uvicorn",
    ],
)

py_binary(
    name = "props",
    srcs = ["src/props_core/cli/main.py"],
    main = "src/props_core/cli/main.py",
    deps = [":props_core"],
)

py_test(
    name = "test_props_core",
    srcs = glob(["tests/**/*.py"]),
    main = "tests/test_agent_types.py",
    deps = [
        ":props_core",
        "//agent_core_testing",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
        "@pypi//pytest_env",
        "@pypi//pytest_mock",
        "@pypi//pytest_timeout",
        "@pypi//pytest_xdist",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":props_core"],
)
