---
- name: Update font version file
  ansible.builtin.copy:
    content: "{{ nerd_fonts_version.stdout }}"
    dest: "{{ installed_version_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Mark fonts updated
  ansible.builtin.set_fact:
    fonts_updated: true
