[project]
name = "dbus_fast_example"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "dbus-fast",
    "pytest",
    "pytest-asyncio",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["client", "dbus_service", "service_manager", "test_example"]

[tool.pytest.ini_options]
addopts = "-vv"
asyncio_mode = "auto"
