[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "indoor_aqi"
version = "0.1.0"
description = "Indoor Air Quality Index component for Home Assistant"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
    "homeassistant>=2022.1.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",

    # exact pin to avoid long install time hell
    "pytest-homeassistant-custom-component==0.13.45",
    "PyHamcrest>=2.0.4",
]

[tool.setuptools]
packages = ["custom_components.indoor_aqi"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
