load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "endpointfilter",
    srcs = ["endpointfilter.go"],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand/endpointfilter",
    visibility = ["//cluster/kubespand:__subpackages__"],
)

go_test(
    name = "endpointfilter_test",
    srcs = ["endpointfilter_test.go"],
    embed = [":endpointfilter"],
)
