load("@aspect_rules_js//js:defs.bzl", "js_library")
load("//devinfra/js:openapi.bzl", "js_openapi_zod")

package(default_visibility = ["//visibility:public"])

js_openapi_zod(
    name = "schema_zod",
    generator = "//augur/api:export_schema_bin",
)

js_library(
    name = "casing",
    srcs = ["casing.js"],
)

js_library(
    name = "frame",
    srcs = ["frame.js"],
)

js_library(
    name = "chart",
    srcs = ["chart.js"],
    deps = [":format"],
)

js_library(
    name = "controls",
    srcs = ["controls.jsx"],
    deps = [
        "//:node_modules/@mantine/core",
        "//:node_modules/react",
    ],
)

js_library(
    name = "format",
    srcs = ["format.js"],
)

js_library(
    name = "backend_client",
    srcs = ["backend_client.js"],
)
