load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

py_library(
    name = "agent_core",
    srcs = glob(
        ["**/*.py"],
        exclude = [
            ".*/**",
            "tests/**",
        ],
    ),
    data = ["compaction_prompt.md"],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "//openai_utils",
        "@pypi//anyio",
        "@pypi//fastmcp",
        "@pypi//mcp",
        "@pypi//pydantic",
        "@pypi//pyhamcrest",
        "@pypi//rich",
        "@pypi//structlog",
    ],
)

py_test(
    name = "test_agent_core",
    srcs = glob(["tests/**/*.py"]),
    main = "tests/test_compaction.py",
    deps = [
        ":agent_core",
        "//agent_core_testing",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":agent_core"],
)
