# Generic package install handler with exclusive source enforcement.
# Each caller should pass `use` and some method variables.
# Example usage:
# - include_tasks: tasks/install-method-handler.yaml
#   vars:
#     apt: foo
#     snap: { name: foo-snap, classic: true }
#     use: snap

- name: Resolve install method details
  set_fact:
    resolved:
      apt: "{{ apt if apt is defined else omit }}"

      snap_name: >-
        {{ (snap if snap is string else snap.name) if snap is defined else omit }}
      snap_classic: >-
        {{ false if snap is string else snap.classic | default(false) }}

- ansible.builtin.debug:
    msg: "Resolved: {{ resolved }}"
    verbosity: 1

- name: Install selected method
  block:
    - assert:
        that:
          - use in ['apt', 'snap']
        # TODO: check that something did get installed
        fail_msg: "Invalid install method: {{ use }}."

    - name: Install via apt
      become: true
      ansible.builtin.apt:
        pkg: "{{ resolved.apt }}"
        state: present
      when: use == 'apt' and resolved.apt is defined

    - name: Install via snap
      become: true
      community.general.snap:
        name: "{{ resolved.snap_name }}"
        classic: "{{ resolved.snap_classic }}"
      when: use == 'snap' and snap is defined

- name: Ensure other methods are absent
  block:
    - name: Remove unused {{ resolved.apt }} APT package
      become: true
      ansible.builtin.apt:
        name: "{{ resolved.apt }}"
        state: absent
      when: use != 'apt' and resolved.apt is defined

    - name: Remove unused {{ resolved.snap_name }} snap
      become: true
      community.general.snap:
        name: "{{ resolved.snap_name }}"
        state: absent
      when: use != 'snap' and snap is defined

