---
- name: Clone oh-my-zsh
  tags:
    - oh-my-zsh
    - zsh
  git:
    # TODO(agentydragon): shallow clone
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "/home/{{ my_user }}/.oh-my-zsh"
