apiVersion: v1
kind: Secret
metadata:
  name: tofu-state-db-credentials
  namespace: tofu-state
  annotations:
    description: PostgreSQL credentials for tofu-state-db (CNPG)
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:hoiZcWkPTQ==,iv:NxlId2iLEYdS9VEpctTcVwHA3LEe/uAPUiqubIktSsY=,tag:D+jcZScrUyrw39E15KtJ/g==,type:str]
  password: ENC[AES256_GCM,data:p+KJCY3/Lb8kwJIaoixEpTe95JNk3moGqciAuVujq8aa9MhGJHt/h2RONQ==,iv:wyzUXxqdP+RWUImG3zJuAdYstTqpaF7E27ciWc9n5k0=,tag:54nHlGUzwtYBpQdKJlfidg==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbWg3TjJGOHBKdlhNQk5r
        Zy9XeFFMU0Ryekp4Ni9EQTUzWFB1Zjd4Sm1JCkN5Z08vQ2laT3doUDJEU2w2LzFF
        Y1RxNlhMekMxc2Q2R1dkbWt4T2cydzAKLS0tIG1DcVQ2aHZQOEVScnpZUHRSYmhW
        aUdtQkRRUllGR2FseFBQRFlMWVE2c28KD4+8fNGWYwEwxrHpYR97FftTcV5Mt4Nq
        5Dy5YfgKYNvioqfmr0aaxWYfa7Uz+thPBYy30uJmV2tSnZ6BbKmX+Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ29PbEc3Sll5TWttWUNG
        a1hCQlFpTHZ3WjVqZUFzQU5FckNVdXJKQkZzClo3VG9JckhVNkw0Mm5iWi9UTTNC
        RzY2SGQwT1RHenA5TDR6Sm9ZSklDUDgKLS0tIG14aTBXSjczem1HYlE1ejc2QmVr
        amdROUxOV1I2TzRVYmFpUmMzRVpCQkUKT2cMK35M/GkMYNfhhx16d5Lh8wFtfXOp
        FKPSv0l1P1DxMkLSXAT3TJEJv7flQfKyBSBefuyuo4sIOm7cqslQog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:19Z"
  mac: ENC[AES256_GCM,data:7VwVrtQMkX2DNBOoz16VMCic92tc8Phw08ymgvJChWlAKWSuKjJ2GcR+dGQ91KNlbZD3DlPCWQ0nC709o3puShmKhq75qx82WVYZ7mUGn7BgOk9HYfrTzLt9ZChR/heP12tBFNboPaIYJpIi155VxYKKovHZM9aD14hAzVbqTZs=,iv:x4M0BR7d+j2hMJmUyv7bk3MN0L+r7pESzYGgpek4Rxw=,tag:sNEWcfvCtN7kH8tJ9Ydg2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
