---
# ActivityWatch server enabled - ensure the service is running
#
# TODO: dedupe w/ tunneled_activitywatch.yml
- name: Install ActivityWatch via dpkg from GitHub
  become: true
  github_release_install:
    release_spec:
      repo: ActivityWatch/activitywatch
      version: v0.13.2
      acknowledged_version: v0.13.2
      asset_pattern: ".*-{{ ansible_architecture }}\\.deb$"
    method: deb

- name: Create aw-server user
  become: true
  user:
    name: aw-server
    system: yes
    create_home: no

- name: Make aw-server data dir
  become: true
  file:
    path: "{{ activitywatch_data_dir }}"
    state: directory
    owner: aw-server
    mode: 0755 # TODO: this should not be world-readable

- name: Install systemd service for aw-server
  template:
    src: aw-server.service.j2
    dest: /etc/systemd/system/aw-server.service
    mode: "0644"

- name: Reload systemd and enable+start service
  systemd:
    daemon_reload: true
    name: aw-server
    state: started
    enabled: true
