apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: harbor-admin
  namespace: flux-system
spec:
  interval: 15m
  approvePlan: "auto"
  path: ./cluster/terraform/gitops/harbor-admin
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  # Use in-cluster service account
  serviceAccountName: tf-runner

  # Configure runner to trust cluster CA
  runnerPodTemplate:
    spec:
      volumes:
        - name: cluster-ca
          configMap:
            name: cluster-internal-ca-bundle
      volumeMounts:
        - name: cluster-ca
          mountPath: /etc/ssl/certs/cluster-ca
          readOnly: true
      env:
        - name: VAULT_CACERT
          value: /etc/ssl/certs/cluster-ca/ca-certificates.crt

  # Store Terraform state in Kubernetes secret
  backendConfig:
    customConfiguration: |
      backend "kubernetes" {
        secret_suffix    = "harbor-admin"
        namespace        = "flux-system"
      }

  # Variables for Terraform
  vars:
    - name: vault_address
      value: "https://instance.vault.svc.cluster.local:8200"
  varsFrom:
    - kind: Secret
      name: vault-token
      varsKeys:
        - vault_token
      optional: false
