apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attic-cache
  namespace: nix-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  # CLEANUP(2026-04-02): Migrate to local-path-proxmox
  storageClassName: local-path
