apiVersion: ENC[AES256_GCM,data:tn4=,iv:y55ClrWrYZjtpM1BVTjWYEvtDyUueuv+KybxnAhwROA=,tag:GN+QlUL6L2/ASOF6jqeTCA==,type:str]
kind: ENC[AES256_GCM,data:t8KUO2eW,iv:V0ZgMbPGz70TO8dBUoYRPxTGXnQYIr53IlmHzl33f7w=,tag:UogITJPnY36aRbGXbz+eWw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:tPUBmaRNpntEe7lhsQeZx01qjgcr,iv:E40oZUX9HgjSa0Xq4PK6hFI0dtqZ96+X98W5SGPny5U=,tag:b2Q3nN7/SHgChZ/fAb2lPw==,type:str]
  namespace: ENC[AES256_GCM,data:orgjYYdb30Jm,iv:yfrqHJkFSznmGNJvB2ji386cW5qCX0p1iv74W29AYwk=,tag:BA81esC+btK/khQh16u7ng==,type:str]
  annotations:
    description: ENC[AES256_GCM,data:mn192vFs30r/hmUW44NTFowNFZbIbE3MDWZC3P4Iafz6MIO9LhNTgjNjZ1ysS8/k+kpP,iv:mfSwk+d9Z+zJoL2iiFAftU9AOn/j+nflLhplg3HXXgs=,tag:l7VTMFKwvmCsigwz9fKk5Q==,type:str]
type: ENC[AES256_GCM,data:m4K9yACI,iv:npk3wBW2JpS+M1qJdO2o9GYxMAYXW+r59sE0PiTx8Pg=,tag:CqLM3bwla+/MJ0UZall5QA==,type:str]
stringData:
  signing-key.sec: ENC[AES256_GCM,data:iwDYt2RuYavQ4YknSV/wE2AwA2HsbaO+DxYzMv5eKFAp/qNKRrkL1Jny55ZaOXB61aDvsWOm3GNjvH7ZwBqU1JH37Mm3Pw9KNybRQ0vVeb47TJvemjbFSlnZ1puTO6q7U4wRapPG8CxHBISB73Escg==,iv:aP+BDhIvk+MLuXtXAsYXG8hVkvBgO9TeKBS5163F96o=,tag:z8KWW1pXWk/gcqRGk7jANw==,type:str]
  signing-key.pub: ENC[AES256_GCM,data:PIRcxf3auZ8zBWtn+QLLD7wIy1WirhzlS6RvYcTYbJdWoXoX9o4/Byo2nx0wVzd+nlpRlfmCrUOHZZ2wuPlfy42ogJs=,iv:sbyxQ/3uiOwgUSMcVhvMBdUbc3dcNeZpv941Hg3vQrQ=,tag:gZTRVqZddi9O3keO4dn0kQ==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTnQyUVFzckI3cW02RllC
        cHVLWThDU283QUFRZEJjZ29FZlNRWEpHUVRrCjhGSmU0UFF6eTRENmkwc012eENS
        ZHZsQnlEcno5bCtSVHJFUGtWdGxIYVUKLS0tIFFJYVdydk5PcEpnS3JvTFErRFA1
        NDdvQ0tyV1pDSFFzSDhFOE8wMkxOLzQKh5hLqKByydPK6QNG1sgu7CkgNTGyCnz2
        HL713FurH6moua21AYNOd40gjcYorz/khzmqV33BqXkHcC16WgHRRQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT3pOOGpDTHdpRnJZWFJX
        THBGeVJwVnFmZGw0UEIzdk5UUWR6M2RhYVZ3CnhyODI2dGdyY2wveXVlRmUrNFNT
        ZnBabFdFODE4bkM3ZkdqTHE0ZXRDQ28KLS0tIGw4SFhMTG96MEZrSFBGYkxNeGNi
        WkpuN1ZrMVlTQUh0bG5tUDhsSEVjUHcKgThTW54+xVke1/aIHDH3n6DGDs7aAAV3
        ZV8Aa4ZdhrokKsbcYZqmwJvcq5COVvJor8cqkIv7TLqGtEIZAZPR2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T06:42:13Z"
  mac: ENC[AES256_GCM,data:MJcPvY7dv6xcQoEUR9lXQG6yc1EbtilKB6RL8OhtEK8rRA7ojpkbIu8WA9WoTEyD2oI5WRYkWXhuE1QBirlFzwTiBGQ0KKkUbSdD/1NFxoSzpPYiFF4G1uOVgiEblFv+ti7amyDjmokS4TQ4RgVhykStMWpB9qTun8ANC4UzkGI=,iv:BSafo63ogTN6dnsel6fQ4EFP8pjxE193GU+Kex1R6EA=,tag:YtyoF3YKbrtPTAaBKolE4Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
