{{- if and .Values.secrets .Values.secrets.rootToken .Values.secrets.rootToken.token }}
{{ include "common.sealedSecret" (dict
  "context" .
  "namespace" (include "vault-ducktape.namespace" .)
  "name" .Values.oidc.rootTokenRef.name
  "encryptedData" (dict .Values.oidc.rootTokenRef.key .Values.secrets.rootToken.token)
  "annotations" (dict "reflector.v1.k8s.emberstack.com/reflection-allowed" "false")
) }}
{{- end }}
