{{- if .Values.oidc.useExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "harbor.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ include "harbor.fullname" . }}-oidc
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-secret: "{{ `{{ .clientSecret }}` }}"
  data:
  - secretKey: clientSecret
    remoteRef:
      key: kv/data/harbor
      property: client-secret
{{- end }}