apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-api-proxy-tls
  namespace: kube-api-proxy
spec:
  secretName: kube-api-proxy-tls
  issuerRef:
    name: "${LETSENCRYPT_ISSUER}"
    kind: ClusterIssuer
  dnsNames:
    - api.allegedly.works
