load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "location_market_sources_py",
    srcs = ["location_market_sources.py"],
    deps = [
        "//augur/core:schemas_py",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "sim_market_api_py",
    srcs = ["sim_market_api.py"],
    deps = [
        "@pypi//numpy",
        "@pypi//polars",
    ],
)

py_library(
    name = "sim_market_series_py",
    srcs = ["sim_market_series.py"],
)

py_library(
    name = "sim_market_deterministic_py",
    srcs = ["sim_market_deterministic.py"],
    deps = [
        "@pypi//numpy",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "sim_market_gbm_py",
    srcs = ["sim_market_gbm.py"],
    deps = [
        "@pypi//numpy",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "sim_market_py",
    srcs = ["sim_market.py"],
    deps = [
        ":sim_market_api_py",
        ":sim_market_deterministic_py",
        ":sim_market_gbm_py",
        "//augur:frames",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "simple_market_py",
    srcs = ["simple_market.py"],
    deps = [
        ":sim_market_api_py",
        ":sim_market_deterministic_py",
        ":sim_market_gbm_py",
        ":sim_market_py",
        ":sim_market_series_py",
        "//augur:frames",
        "//augur/core:schemas_py",
        "@pypi//numpy",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "core_market_adapter_py",
    srcs = ["core_market_adapter.py"],
    deps = [
        ":sim_market_api_py",
        ":sim_market_series_py",
        "//augur/core:market_bundle_py",
        "//augur/core:scenario_set_py",
        "@pypi//numpy",
    ],
)

py_library(
    name = "market_provider_config_py",
    srcs = ["market_provider_config.py"],
    deps = [
        ":core_market_adapter_py",
        ":simple_market_py",
        "//augur/core:market_bundle_py",
        "//augur/core:schemas_py",
        "//augur/model/markets/models:vecm_py",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "testing_py",
    testonly = True,
    srcs = ["testing.py"],
    deps = [
        ":core_market_adapter_py",
        ":sim_market_api_py",
        ":sim_market_deterministic_py",
        ":sim_market_py",
        "//augur:frames",
        "//augur/core:market_bundle_py",
        "@pypi//numpy",
    ],
)

py_test(
    name = "sim_market_test",
    srcs = ["sim_market_test.py"],
    deps = [
        ":sim_market_api_py",
        ":sim_market_deterministic_py",
        ":sim_market_gbm_py",
        ":sim_market_py",
        ":sim_market_series_py",
        ":testing_py",
        "@pypi//polars",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "simple_market_test",
    srcs = ["simple_market_test.py"],
    deps = [
        ":core_market_adapter_py",
        ":market_provider_config_py",
        ":sim_market_api_py",
        ":sim_market_series_py",
        ":simple_market_py",
        "//augur/core:market_bundle_py",
        "//augur/core:scenario_set_py",
        "@pypi//numpy",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
