load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "schemas_py",
    srcs = ["schemas.py"],
    deps = [
        "@pypi//pydantic",
    ],
)

py_library(
    name = "provenance_py",
    srcs = ["provenance.py"],
)

py_library(
    name = "location_series_sources_py",
    srcs = ["location_series_sources.py"],
    deps = [
        ":schemas_py",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "exogenous_py",
    srcs = ["exogenous.py"],
    deps = [
        "@pypi//numpy",
        "@pypi//polars",
    ],
)

py_library(
    name = "series_py",
    srcs = ["series.py"],
)

py_library(
    name = "deterministic_py",
    srcs = ["deterministic.py"],
    deps = [
        "@pypi//numpy",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "gbm_py",
    srcs = ["gbm.py"],
    deps = [
        "@pypi//numpy",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "series_model_py",
    srcs = ["series_model.py"],
    deps = [
        ":deterministic_py",
        ":exogenous_py",
        ":gbm_py",
        "//augur:frames",
        "@pypi//polars",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "simple_exogenous_py",
    srcs = ["simple_exogenous.py"],
    deps = [
        ":deterministic_py",
        ":exogenous_py",
        ":gbm_py",
        ":schemas_py",
        ":series_model_py",
        ":series_py",
        "//augur:frames",
        "@pypi//numpy",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "exogenous_provider_config_py",
    srcs = ["exogenous_provider_config.py"],
    deps = [
        ":schemas_py",
        ":simple_exogenous_py",
        "//augur/model/path_models/models:vecm_py",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "testing_py",
    testonly = True,
    srcs = ["testing.py"],
    deps = [
        ":deterministic_py",
        ":exogenous_py",
        ":series_model_py",
        "//augur:frames",
        "@pypi//numpy",
    ],
)

py_test(
    name = "series_model_test",
    srcs = ["series_model_test.py"],
    deps = [
        ":deterministic_py",
        ":exogenous_py",
        ":gbm_py",
        ":series_model_py",
        ":series_py",
        ":testing_py",
        "@pypi//polars",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_test(
    name = "simple_exogenous_test",
    srcs = ["simple_exogenous_test.py"],
    deps = [
        ":exogenous_provider_config_py",
        ":exogenous_py",
        ":series_py",
        ":simple_exogenous_py",
        "@pypi//numpy",
        "@pypi//pytest_bazel",
    ],
)
