---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    image: ubuntu:22.04
    pre_build_image: false
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"

verifier:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"

