- name: Prepare test environment
  become: true
  hosts: all
  tasks:
    - name: Install test dependencies
      ansible.builtin.apt:
        update_cache: true
        name:
          - xvfb
          - dbus-x11
          - gnome-terminal
          - fonts-ubuntu
          - fontconfig # needed for fc-list; TODO: should assert its presence in the container...
          - dconf-cli # for final test - 'dconf' utility

    - name: Start fake X server
      ansible.builtin.shell: |
        Xvfb :99 -screen 0 1024x768x24 &
        echo $! > /tmp/xvfb.pid
      changed_when: true
