# Nebula Mesh PKI — CA + per-node certificates
#
# CA and node certs are generated by nebula-cert CLI via local-exec, then read
# into tofu state. Infrastructure layer consumes them via terraform_remote_state.
# This ensures CA and node certs are always consistent (signed by the same CA).

locals {
  nebula_cert_dir = "${path.module}/nebula-certs"

  # All Nebula mesh nodes — add new nodes here when expanding the mesh.
  nebula_nodes = {
    "talos-vps-cp-0"  = { ip = "10.42.0.1/16", groups = "lighthouse,controlplane,vps" }
    "talos-vps-cp-1"  = { ip = "10.42.0.2/16", groups = "lighthouse,controlplane,vps" }
    "talos-pve-cp-0"  = { ip = "10.42.0.10/16", groups = "controlplane,proxmox" }
    "wyrm2"           = { ip = "10.42.0.20/16", groups = "worker,proxmox,gpu" }
    "rugged"          = { ip = "10.42.0.30/16", groups = "worker,roaming" }
    "k8s-worker-test" = { ip = "10.42.0.99/16", groups = "worker,test" }
    "activitywatch"   = { ip = "10.42.0.40/16", groups = "service" }
  }
}

# Generate CA cert + key (once, stored on disk + in state).
# Only runs if ca.crt doesn't exist yet in the cert directory.
resource "null_resource" "nebula_ca" {
  triggers = {
    cert_dir = local.nebula_cert_dir
  }

  provisioner "local-exec" {
    command = <<-EOT
      set -e
      mkdir -p ${local.nebula_cert_dir}
      if [ ! -f ${local.nebula_cert_dir}/ca.crt ]; then
        nebula-cert ca -name "allegedly.works" -duration 87600h \
          -out-crt ${local.nebula_cert_dir}/ca.crt \
          -out-key ${local.nebula_cert_dir}/ca.key
        echo "Generated new Nebula CA"
      else
        echo "Nebula CA already exists, skipping"
      fi
    EOT
  }
}

data "local_file" "nebula_ca_crt" {
  filename   = "${local.nebula_cert_dir}/ca.crt"
  depends_on = [null_resource.nebula_ca]
}

# Generate per-node certs signed by the CA.
# Re-runs when CA, IP, or groups change.
resource "null_resource" "nebula_node_cert" {
  for_each = local.nebula_nodes

  triggers = {
    ca_hash = data.local_file.nebula_ca_crt.content_sha256
    ip      = each.value.ip
    groups  = each.value.groups
  }

  provisioner "local-exec" {
    command = <<-EOT
      set -e
      nebula-cert sign \
        -ca-crt ${local.nebula_cert_dir}/ca.crt \
        -ca-key ${local.nebula_cert_dir}/ca.key \
        -name "${each.key}" \
        -ip "${each.value.ip}" \
        -groups "${each.value.groups}" \
        -out-crt ${local.nebula_cert_dir}/${each.key}.crt \
        -out-key ${local.nebula_cert_dir}/${each.key}.key
    EOT
  }

  depends_on = [null_resource.nebula_ca]
}

data "local_file" "nebula_node_crt" {
  for_each   = local.nebula_nodes
  filename   = "${local.nebula_cert_dir}/${each.key}.crt"
  depends_on = [null_resource.nebula_node_cert]
}

data "local_sensitive_file" "nebula_node_key" {
  for_each   = local.nebula_nodes
  filename   = "${local.nebula_cert_dir}/${each.key}.key"
  depends_on = [null_resource.nebula_node_cert]
}
