---
- name: Hide gnome-terminal menu
  tags:
    - gnome-terminal
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/default-show-menubar"
    value: false

- name: Set GNOME default terminal to gnome-terminal
  tags: [gnome-terminal]
  block:
    - name: Set GNOME default terminal to gnome-terminal.wrapper
      community.general.dconf:
        key: "/org/gnome/desktop/applications/terminal/exec"
        value: "'gnome-terminal.wrapper'"
    - name: Expicitly set GNOME default terminal exec-arg empty
      community.general.dconf:
        key: "/org/gnome/desktop/applications/terminal/exec-arg"
        state: absent
