"""Install Bazelisk for Bazel version management.

Bazelisk automatically downloads and runs the correct Bazel version
based on .bazelversion or USE_BAZEL_VERSION.

TODO: Eventually unify tool installation via direnv/devenv instead of
      manual downloads in session hooks.

IMPORTANT: This module must not import any non-stdlib packages.
"""

from __future__ import annotations

import logging
import platform
import stat
import subprocess
import urllib.request
from pathlib import Path

log = logging.getLogger(__name__)

BAZELISK_VERSION = "1.25.0"
# Private install location - we put wrapper in bin/, bazelisk in bazelisk
CACHE_DIR = Path.home() / ".cache" / "bazel-proxy"
BAZELISK_PATH = CACHE_DIR / "bazelisk"  # The actual bazelisk binary
WRAPPER_DIR = CACHE_DIR / "bin"  # Dir with wrapper, added to PATH
WRAPPER_PATH = WRAPPER_DIR / "bazel"  # The wrapper script


def get_bazelisk_url() -> str:
    """Get the appropriate Bazelisk download URL for this platform."""
    system = platform.system().lower()
    machine = platform.machine().lower()

    # Normalize architecture names
    if machine in ("x86_64", "amd64"):
        arch = "amd64"
    elif machine in ("aarch64", "arm64"):
        arch = "arm64"
    else:
        raise RuntimeError(f"Unsupported architecture: {machine}")

    if system == "linux":
        binary = f"bazelisk-linux-{arch}"
    elif system == "darwin":
        binary = f"bazelisk-darwin-{arch}"
    else:
        raise RuntimeError(f"Unsupported OS: {system}")

    return f"https://github.com/bazelbuild/bazelisk/releases/download/v{BAZELISK_VERSION}/{binary}"


def install_bazelisk() -> Path:
    """Download bazelisk to private location, returning the binary path.

    Installs to ~/.cache/bazel-proxy/bazelisk (private, not on PATH).
    The wrapper script in ~/.cache/bazel-proxy/bin/bazel will call this.
    Skips download if already installed.
    """
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    # Check if already installed
    if BAZELISK_PATH.exists():
        result = subprocess.run([str(BAZELISK_PATH), "--version"], capture_output=True, text=True, check=False)
        if result.returncode == 0:
            log.info("Bazelisk already installed: %s", BAZELISK_PATH)
            return BAZELISK_PATH

    url = get_bazelisk_url()
    log.info("Downloading Bazelisk from %s", url)

    # Download with proxy support (urllib respects https_proxy env var)
    try:
        with urllib.request.urlopen(url, timeout=60) as response:
            BAZELISK_PATH.write_bytes(response.read())
    except urllib.error.URLError as e:
        raise RuntimeError(f"Failed to download Bazelisk: {e}") from e

    # Make executable
    BAZELISK_PATH.chmod(BAZELISK_PATH.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    log.info("Installed Bazelisk to %s", BAZELISK_PATH)

    return BAZELISK_PATH


def install_wrapper(proxy_port: int = 18081, repo_root: Path | None = None) -> Path:
    """Install wrapper script that sets proxy env vars before calling bazelisk.

    The wrapper is in ~/.cache/bazel-proxy/bin/bazel and calls the real
    bazelisk at ~/.cache/bazel-proxy/bazelisk.
    Also creates a bazelisk symlink for pre-commit hooks.
    Includes health checks for supervisor and proxy service.
    """
    _ = repo_root  # No longer used - proxy config is handled by module extension
    WRAPPER_DIR.mkdir(parents=True, exist_ok=True)

    local_proxy = f"http://localhost:{proxy_port}"
    supervisor_conf = Path.home() / ".config" / "supervisor" / "supervisord.conf"
    supervisor_sock = Path.home() / ".config" / "supervisor" / "supervisor.sock"

    wrapper_content = f'''#!/bin/bash
# Bazel wrapper for Claude Code web - sets proxy env vars and checks health
# Generated by bazelisk_setup.py

# Health check: supervisord must be running
if [[ ! -S "{supervisor_sock}" ]]; then
    echo "ERROR: supervisord is not running" >&2
    echo "The bazel proxy requires supervisor for process management." >&2
    echo "" >&2
    echo "To check status:" >&2
    echo "  tail -20 ~/.cache/claude-code-web/session-start.log" >&2
    echo "" >&2
    echo "If you're in Claude Code web, this should have been set up automatically." >&2
    echo "If you're running locally, you may need to start supervisor manually." >&2
    exit 1
fi

# Health check: bazel-proxy service must be running
if ! supervisorctl -c "{supervisor_conf}" status bazel-proxy 2>/dev/null | grep -q RUNNING; then
    echo "ERROR: bazel-proxy service is not running under supervisor" >&2
    echo "" >&2
    echo "To check proxy status:" >&2
    echo "  supervisorctl -c {supervisor_conf} status" >&2
    echo "" >&2
    echo "To view proxy logs:" >&2
    echo "  tail -50 ~/.config/supervisor/bazel-proxy.log" >&2
    echo "  tail -50 ~/.config/supervisor/bazel-proxy.err.log" >&2
    echo "" >&2
    echo "To restart proxy:" >&2
    echo "  supervisorctl -c {supervisor_conf} restart bazel-proxy" >&2
    exit 1
fi

export HTTPS_PROXY="{local_proxy}"
export HTTP_PROXY="{local_proxy}"
export https_proxy="{local_proxy}"
export http_proxy="{local_proxy}"

exec "{BAZELISK_PATH}" "$@"
'''
    WRAPPER_PATH.write_text(wrapper_content)
    WRAPPER_PATH.chmod(0o755)
    log.info("Installed bazel wrapper at %s with health checks", WRAPPER_PATH)

    # Create bazelisk symlink for pre-commit hooks
    bazelisk_symlink = WRAPPER_DIR / "bazelisk"
    if bazelisk_symlink.exists() or bazelisk_symlink.is_symlink():
        bazelisk_symlink.unlink()
    bazelisk_symlink.symlink_to(WRAPPER_PATH)
    log.info("Created bazelisk symlink at %s", bazelisk_symlink)

    return WRAPPER_PATH


def get_env_script() -> str:
    """Get bash script fragment to add wrapper dir to PATH.

    This should be appended to CLAUDE_ENV_FILE.
    """
    return f"""\
# Bazel wrapper (sets proxy for TLS-inspecting proxy)
[ -d "{WRAPPER_DIR}" ] && export PATH="{WRAPPER_DIR}:$PATH"
"""


def is_installed() -> bool:
    """Check if bazelisk is available."""
    return BAZELISK_PATH.exists()


def get_status() -> str:
    """Get status string for logging."""
    if WRAPPER_PATH.exists():
        # Get version from the actual bazelisk
        result = subprocess.run([str(BAZELISK_PATH), "version"], capture_output=True, text=True, check=False)
        if result.returncode == 0:
            # Extract first line (aspect or bazel version)
            version = result.stdout.split("\n")[0].strip()
            return f"{version} ({WRAPPER_PATH})"
    if BAZELISK_PATH.exists():
        return f"bazelisk at {BAZELISK_PATH} (no wrapper)"
    return "not installed"
