load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "config_py",
    srcs = ["config.py"],
    deps = [
        "//augur/core:bootstrap_py",
        "//augur/core:local_regulation_py",
        "//augur/core:scenario_set_py",
        "//augur/core:schemas_py",
        "@pypi//pydantic",
    ],
)

py_test(
    name = "config_test",
    srcs = ["config_test.py"],
    deps = [
        ":config_py",
        "//augur/core:local_regulation_py",
        "//augur/core:scenario_set_py",
        "@pypi//pydantic",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "catalog_py",
    srcs = ["catalog.py"],
    deps = [
        ":config_py",
        "//augur/core:bootstrap_py",
        "//augur/core:local_regulation_py",
        "//augur/core:scenario_set_py",
        "//augur/core:schemas_py",
    ],
)

py_library(
    name = "augur_backend_py",
    srcs = ["augur_backend.py"],
    deps = [
        ":catalog_py",
        ":config_py",
        "//augur/core:augur_accounting_py",
        "//augur/core:bootstrap_py",
        "//augur/core:local_regulation_py",
        "//augur/core:market_bundle_py",
        "//augur/core:rollout_provider_py",
        "//augur/core:scenario_engine_py",
        "//augur/core:scenario_set_py",
        "//augur/core:schemas_py",
        "//augur/model:market_bundle_adapter_py",
    ],
)

py_library(
    name = "rollout_server_py",
    srcs = ["rollout_server.py"],
    deps = [
        ":augur_backend_py",
        ":config_py",
        "//augur/core:backend_py",
        "//augur/core:rollout_provider_py",
        "//augur/core:static_py",
        "//augur/model:macro_rollout_provider_py",
        "//augur/model/markets:registry_py",
        "@pypi//uvicorn",
    ],
)
