#!/bin/bash
# Spawn-graph initialization script
# Usage: source ~/code/ducktape/llm/ducktape_llm_common/spawn-graph/init.sh "instance-name" "phase-name"
#
# This is a global helper for use across all projects

# Check if spawn-graph directory exists, create if needed
if [ ! -d "./spawn-graph" ]; then
    echo "Creating spawn-graph directory..."
    mkdir -p ./spawn-graph
fi

# Create README.md if it doesn't exist
if [ ! -f "./spawn-graph/README.md" ]; then
    cat > ./spawn-graph/README.md << 'EOF'
# Spawn Graph Directory

This directory contains parallel task execution graphs using git worktrees.
Each subdirectory represents a separate spawn-graph execution instance.

Git worktrees allow multiple working directories for the same repository,
enabling true parallel development without conflicts.

DO NOT manually edit files in task directories while agents are working.
EOF
fi

# Create path-helpers.sh if it doesn't exist
if [ ! -f "./spawn-graph/path-helpers.sh" ]; then
    echo "Creating path-helpers.sh..."
    cat > ./spawn-graph/path-helpers.sh << 'EOF'
#!/bin/bash
# Spawn-graph path helper functions
# Auto-generated by spawn-graph init.sh

task_output_dir() {
    local task_name="$1"
    if [ -z "$INSTANCE" ] || [ -z "$PHASE" ]; then
        echo "ERROR: INSTANCE and PHASE must be set" >&2
        return 1
    fi
    echo "spawn-graph/${INSTANCE}/${PHASE}/${task_name}/spawn-graph/${INSTANCE}/${PHASE}/${task_name}"
}

task_output_file() {
    local task_name="$1"
    echo "$(task_output_dir "$task_name")/OUTPUT.md"
}

task_dir() {
    local task_name="$1"
    echo "./spawn-graph/${INSTANCE}/${PHASE}/${task_name}"
}

assert_task_output_path() {
    local path="$1"
    local slash_count=$(echo "$path" | tr -cd '/' | wc -c)
    if [ "$slash_count" -ne 8 ]; then
        echo "ERROR: Invalid path - expected 8 slashes, got $slash_count" >&2
        echo "Path: $path" >&2
        return 1
    fi
    return 0
}

show_spawn_config() {
    echo "Spawn-graph configuration:"
    echo "  INSTANCE: ${INSTANCE:-NOT SET}"
    echo "  PHASE: ${PHASE:-NOT SET}"
}
EOF
    chmod +x ./spawn-graph/path-helpers.sh
fi

# Set INSTANCE and PHASE from arguments
if [ $# -eq 2 ]; then
    export INSTANCE="$1"
    export PHASE="$2"
elif [ $# -eq 0 ] && [ -n "$INSTANCE" ] && [ -n "$PHASE" ]; then
    # Already set, keep existing values
    :
else
    echo "ERROR: Usage: source ~/code/ducktape/llm/ducktape_llm_common/spawn-graph/init.sh \"instance-name\" \"phase-name\"" >&2
    echo "       Or set INSTANCE and PHASE before sourcing" >&2
    return 1 2>/dev/null || exit 1
fi

# Source the path helpers
source ./spawn-graph/path-helpers.sh

# Show configuration
show_spawn_config

# Export commonly needed functions for convenience
export -f task_output_dir
export -f task_output_file
export -f task_dir
export -f assert_task_output_path
export -f show_spawn_config