- name: Enable NodeSource 22.x repo
  deb822_repository:
    name: nodesource
    types: [deb]
    uris: https://deb.nodesource.com/node_22.x
    suites: [nodistro]
    components: [main]
    architectures: ["{{ dpkg_arch }}"]
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present
  become: true

- name: Install Node.js (includes npm)
  ansible.builtin.apt:
    update_cache: true
    name: nodejs
    state: present
  become: true
