load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "gatelet",
    srcs = glob(["gatelet/**/*.py"]),
    data = glob([
        "gatelet/**/*.html",
        "gatelet/**/*.jinja2",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//alembic",
        "@pypi//asyncpg",
        "@pypi//aw_client",
        "@pypi//aw_core",
        "@pypi//compact_json",
        "@pypi//cryptography",
        "@pypi//fastapi",
        "@pypi//fastapi_csrf_protect",
        "@pypi//fastapi_sessions",
        "@pypi//fastapi_users",
        "@pypi//homeassistant_api",
        "@pypi//jinja2",
        "@pypi//oura",
        "@pypi//passlib",
        "@pypi//psycopg2_binary",
        "@pypi//pydantic",
        "@pypi//python_multipart",
        "@pypi//sqlalchemy",
        "@pypi//tomlkit",
        "@pypi//uvicorn",
    ],
)

py_binary(
    name = "gatelet-reporter",
    srcs = ["gatelet/reporter/__init__.py"],
    main = "gatelet/reporter/__init__.py",
    deps = [":gatelet"],
)
