[project]
name = "gatelet"
version = "0.1.0"
description = "LLM-friendly API for Home Assistant and webhooks"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
    {name = "agentydragon", email = "agentydragon@example.com"},
]
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.23.2",
    "SQLAlchemy>=2.0.0",
    "types-sqlalchemy>=1.4.53",
    "alembic>=1.12.0",
    "psycopg2-binary>=2.9.6",
    "asyncpg>=0.27.0",
    "cryptography>=41.0.0",
    "jinja2>=3.1.2",
    "python-multipart>=0.0.9",
    "pydantic>=2.4.0",
    "compact_json>=1.0.0",
    "homeassistant-api",
    'passlib',
    "tomlkit",
    'fastapi-csrf-protect',
    'fastapi-users[sqlalchemy]',
    'fastapi-sessions',

    # ActivityWatch stuff
    'aw-client',
    'aw-core', # bundles: 'aw-query', 'aw-transform',

    "oura", # Oura API: https://github.com/turing-complet/python-ouraring
    # TODO: google - activity?
    "python-metar", # weather
    # "withings-api", # TODO: scale, later

    # weather
    "pyowm", # live weather, forecasts
    "aqipy",
    "meteostat",
    "geopy",  # geocoding: gps -> place name

    # google cal
    "google-api-python-client",
    "google-auth",


    # Not anytime soon:
    #   Smart home extra:         pytradfri, pywizlight
    #   NextCloud/Apple Calendar: caldav
    #   Finance:                  yfinance, ccxt
    #   Fitness:                  strava, pytrain (Apple Fitness), polaracceslink, garminconnect, fitbit
    #   Time tracking:            py-toggl, rescuetime-py
    #   LLM helpers:              openai, tiktoken, anthropic
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.25",
    "pytest-timeout>=2.3.0",
    "isort>=5.12.0",
    "pyhamcrest>=2.0.4",
    "httpx>=0.27.0",
    "pytest-postgresql>=4.1.1",
    "sqlalchemy-stubs>=0.4.0",
    "playwright",
    "pytest-playwright",
    "invoke",
]

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["server"]
filterwarnings = ["ignore::DeprecationWarning"]

