apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: tailscale-router
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tailscale-auth
    creationPolicy: Owner
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: tailscale-router/authkey
        property: authkey
