load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "identity",
    srcs = ["identity.go"],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand/identity",
    visibility = ["//cluster/kubespand:__subpackages__"],
    deps = [
        "//cluster/kubespand/peerstate",
        "@com_github_siderolabs_talos_pkg_machinery//resources/kubespan",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)
