apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-stack.fullname" . }}-homeserver-tmpl
  labels:
    app.kubernetes.io/name: {{ include "matrix-stack.name" . }}
    helm.sh/chart: {{ include "matrix-stack.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  homeserver.yaml.tmpl: |
    server_name: "{{ .Values.synapse.serverName }}"
    public_baseurl: "{{ .Values.synapse.publicBaseUrl }}"
    listeners:
      - port: 8008
        tls: false
        type: http
        x_forwarded: true
        resources:
          - names: [client]
            compress: false
    enable_registration: false
    report_stats: {{ ternary "yes" "no" .Values.synapse.reportStats | quote }}
    media_store_path: "/data/media_store"
