{{- if .Values.synapse.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "matrix-stack.fullname" . }}-synapse-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.synapse.persistence.size }}
  {{- if .Values.synapse.persistence.storageClass }}
  storageClassName: {{ .Values.synapse.persistence.storageClass }}
  {{- end }}
{{- end }}

