apiVersion: v1
kind: Secret
metadata:
    name: agentplane-oidc
    namespace: agentplane-testing
    annotations:
        description: Dex client credentials and Agentplane session signing key for testing.
stringData:
    client-id: ENC[AES256_GCM,data:xZNPApwopqEpr6RbQOhGGAQN,iv:wYE16/ttXhGqLMf6fSzwqnNGhDW33eG0xeloF98LuzA=,tag:6081j775u6hSCmAiYRj4zg==,type:str]
    client-secret: ENC[AES256_GCM,data:GNF6Tqv0LOic2mevJ6nOjb/3BpSdNf1YoSzhsnzjBj8+KuSSOqfIv8N58fkm8J9t/J7KXRftVG/oDgTRgiNtkg==,iv:Q3SK21JJV10Krh3TSDqn5v+KvNGdgerVP7Ft7jis4Cg=,tag:AccIA4Xg1U4m5wa9vaxNiw==,type:str]
    session-secret: ENC[AES256_GCM,data:tqAL804fkGWDlqOoVsCz5MCtiztFcQD9ir8UQOpLRqvIrqEzrsla1T1eKoR41PZXH6PofcuKPDYc33XfW6gScw==,iv:G0dcAyweJIEMH8bKwVvcTPmZf3yKQ5M2fQnS9V4mxTQ=,tag:wJCng5rM5wdNUakldJHnRg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WE9vYzlYVzgrc0E3SzlI
            Rnd5ZmN3Qi9hSFhxeWRZU2MyS0Y3ZW1Zd0hJCkk0aU5BSGQ4SEF6elRkdGtrUENV
            L21VT1JqYlB3Z040SjhNT1ZiUDFINUUKLS0tIHlUK0RZVEh1Mm14Z3daelBxZTlS
            K3B5U0RVNHh2VWQ0d2pyT0JZL2pMemsKV2klXnchNI1xLrIq+kwHDoUDm0aTjYKx
            s2ngXrC87bNSoLaeDvfVHeVKL+UAHZvNEZaRO4LmvMcswdq5kt+36w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T02:38:21Z"
    mac: ENC[AES256_GCM,data:VdR07HxrnpDCI0M6FjvFbT4LlTwU0jfJD8ltj5V2aeHJdHTOqltpvI6iwmzrtVxBxoxLX8NOJZKGUCyyOvVw4GBONxTzml1GfY0xDUNo8AqR7M1hQN+qALNPhP4vp+3d+oqEVHrYW1wCHA/mAToVrNGDJapK4Hy2o4p67TN1PhE=,iv:fmXhTOsIxi+IpdFB0zZCyp4AG/bJT12gPGYwJiXtiVU=,tag:k+7ZLUTPzeVEIguNbUt6yw==,type:str]
    version: 3.13.3
