{{- $fullname := include "common.fullname" . -}}
{{- $sa := include "common.serviceAccountName" (dict "default" $fullname "values" (default (dict) .Values.controller.serviceAccount)) -}}
{{- $labels := include "common.componentLabels" (dict "context" . "component" "sealed-secrets-controller") | fromYaml -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
  labels:
{{ toYaml $labels | indent 4 }}
