apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-proxy-ha-token
  namespace: homeassistant-proxy
  annotations:
    description: Home Assistant token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:dC32+lwLeKqgyQ==,iv:tuqp+n8ftZiKj6DtLekLEEKjCtMi67klGA6fME9ICnA=,tag:DvhcaN9TGGSzgsPjnxo2TQ==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTlppMjQyRVpxQ3FrQ2pu
        dTI0YmF0S3BEUFIxY1FwLzAyQWZwQjJwRG1FCmE4UTRPUEdscmVtckhEYi81MDd2
        TGd4RSswOFZmUm5aY3FmUlNlRnE4bkUKLS0tIGlTL0RpaG42Mi9vVmRIdUd1MGVD
        QzlyK3RmdERVQ0M0QnZsMUozSmFKV1UK9kW08m3wCKBtbIxRYaG1KiBUxKsbklUr
        AETtPf389XRqq8Tad3ao3tMEq1ujcsZwnJ+Y9AUTsWzwkL2gPgNAAQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ellCWFcvcFluZ21tMm01
        MlV1VldFUG83eElvWkw0SGdudVdKRXBjMnlJCk9qaXFIdmc2RWdQdnlxNmc3NUNa
        eE1BSW9Ya2JpcHVLZ3paZTNJWFZ6bWcKLS0tIFNNR2hOV2JkNllhaXRpWVpWZFhH
        Y1dyUW9oR2ZPMi9WTzVVRkVYSWxQcG8K3lgd2zwFZb2bQKGB8+Bs+QXPI3Dr2oj2
        i1FrCHndZhifjANpKDDfSOxpMhvGgumqsUicaC1bMUYCZo1/ugVMSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:16Z"
  mac: ENC[AES256_GCM,data:PGc9BnQ1osM8kfE+ph/L6XdaWazwSkYGyrcPA8f0EfmApGRWWT1sIN/ZzXtv+qO1B0ZH8gpsvoXIPn2L5PlMGi+w+EousdX0F4m7js9yPesiIPKwUI/yhHKZ0zF2x0d67KcGUiMNB2yooe0QTp/ZXl02gUjYxOQMGUiMf8I8mo0=,iv:++udct4ZBtg4BJoy0vY+LQF7EorR+UcJTOeBe2E/8BQ=,tag:TGYAydk6q0jE78D4qjMNkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
