---
# google-repos need to come before update - in case Google's keys changed.
- include_tasks: tasks/google-repos.yaml

- name: update everything
  become: yes
  apt:
    update_cache: yes
    upgrade: dist
# - name: install youtube-dl
#   # TODO: validate
#   get_url:
#     url: https://yt-dl.org/downloads/latest/youtube-dl
#     dest: "{{ local_scripts_path }}/youtube-dl"
- include_tasks: tasks/common-packages.yaml
- include_tasks: tasks/anki.yaml
  tags:
  - anki
- include_tasks: tasks/dev-env.yaml
- include_tasks: tasks/dotfiles.yaml
- name: Set up custom scripts
  tags:
  - custom-scripts
  git:
    repo: https://github.com/agentydragon/scripts
    dest: "{{ scripts_path }}"
    version: master

- name: set up vim
  tags: vim
  block:
  - name: Clone Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: "/home/{{ my_user }}/.vim/bundle/Vundle.vim"
      version: master
  - name: install vim plugins
    command: "vim -E -s -c 'source /home/{{ my_user }}/.vimrc' -c PluginInstall -c PluginUpdate -c qall"

- name: gnome-terminal
  tags:
    - gnome-terminal
    - solarized
  block:
  - include_tasks: gnome-terminal-solarized.yaml
  - name: hide gnome-terminal menu
    command: |
      gsettings set
        org.gnome.Terminal.Legacy.Settings default-show-menubar false
  - name: do not use system font
    dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:{{ profile_uuid.stdout }}/use-system-font"
      value: "false"
  - name: set terminal font
    dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:{{ profile_uuid.stdout }}/font"
      value: "'Ubuntu Mono 14'"
- include_tasks: tasks/datetime-format.yaml
- name: Install Telegram Desktop, youtube-dl
  become: true
  tags: snap
  snap:
    name:
    - telegram-desktop
    - youtube-dl
- name: Install Slack
  become: true
  tags: snap
  snap:
    classic: true
    name:
    - slack
- include_tasks: tasks/dev-env.yaml
- name: set sloppy focus (focus follows mouse)
  dconf:
    key: /org/gnome/desktop/wm/preferences/focus-mode
    value: sloppy
- name: minimize - maximize - close buttons
  dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: :minimize,maximize,close
