[project]
name = "inventree-utils"
version = "0.0.0"
description = "External utilities for InventTree API interaction."
authors = [{ name = "Rai" }]
requires-python = ">=3.12"
dependencies = [
  "beautifulsoup4>=4.12",
  "inventree>=0.15",
  "pint>=0.24",
  "platformdirs>=4.0",
  "pyyaml>=6.0",
  "requests>=2.31",
  "structlog>=24.0",
  "tqdm>=4.66",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.3",
]

[project.scripts]
inventree-beautifier = "inventree_utils.beautifier.__main__:main"
