load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//agentplane:__subpackages__"])

py_library(
    name = "listener",
    srcs = ["listener.py"],
    deps = [
        "@pypi//asyncpg",
        "@pypi//sqlalchemy",
        "@pypi//tenacity",
    ],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    deps = ["//util/testing:postgres_fixtures"],
)

py_test(
    name = "test_listener",
    srcs = ["test_listener.py"],
    deps = [
        ":conftest",
        ":listener",
        "//:conftest",
        "@pypi//asyncpg",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
        "@pypi//sqlalchemy",
        "@pypi//testcontainers",
    ],
)
