---
golang_version: "1.25.0" # Latest stable as of Aug 2025
golang_install_dir: "{{ ansible_user_dir }}/.local"
golang_download_url: "https://go.dev/dl/go{{ golang_version }}.linux-{{ golang_arch }}.tar.gz"
golang_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
golang_bin_path: "{{ golang_install_dir }}/go/bin"
