load("//devinfra/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "schema",
    srcs = ["schema.py"],
    deps = [
        "//augur/api:schemas",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "default_rules",
    srcs = ["default_rules.py"],
    deps = [":schema"],
)

py_library(
    name = "categorize",
    srcs = ["categorize.py"],
    deps = [
        ":default_rules",
        ":schema",
        "//plaid_utils:schema",
    ],
)

py_test(
    name = "test_categorize",
    srcs = ["test_categorize.py"],
    deps = [
        ":categorize",
        ":schema",
        "//plaid_utils:schema",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "aggregate",
    srcs = ["aggregate.py"],
    deps = [
        ":categorize",
        ":schema",
        "//augur:dates",
        "//plaid_utils:schema",
    ],
)

py_test(
    name = "test_aggregate",
    srcs = ["test_aggregate.py"],
    deps = [
        ":aggregate",
        ":categorize",
        ":schema",
        "//augur:dates",
        "//plaid_utils:schema",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "wire",
    srcs = ["wire.py"],
    deps = [
        ":schema",
        "//augur/api:schemas",
        "@pypi//pydantic",
    ],
)

py_library(
    name = "service",
    srcs = ["service.py"],
    deps = [
        ":aggregate",
        ":categorize",
        ":schema",
        ":wire",
        "//plaid_utils:read_model",
    ],
)
