---
- name: Stop and disable WireGuard service
  become: true
  ansible.builtin.systemd:
    name: "wg-quick@wg0"
    enabled: false
    state: stopped
  failed_when: false
  # Ignore errors if service doesn't exist

- name: Remove WireGuard configuration file
  become: true
  ansible.builtin.file:
    path: /etc/wireguard/wg0.conf
    state: absent

- name: Remove WireGuard packages
  become: true
  ansible.builtin.package:
    name:
      - wireguard
      - wireguard-tools
    state: absent
  # Ignore errors if packages aren't installed
  failed_when: false

- name: Remove WireGuard configuration directory
  become: true
  ansible.builtin.file:
    path: /etc/wireguard
    state: absent
