apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - props-secrets-tf.yaml
  - evaluator-credentials-externalsecret.yaml
  - openai-api-key.sops.yaml
  - props-harbor-robot-externalsecret.yaml
