# 'Props cluster deployment key' API key in the 'Props' OpenAI project
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: props-openai-api-key
  namespace: props
  annotations:
    description: OpenAI API key for props evaluator
spec:
  encryptedData:
    api-key: AgCY/pRkMzgCPEQ7p9nqj86MFWpnSzWoeADXluEjFgJLFaWjVGny8TyKqRNYOkIh/HePfXyQedF4y5wYArVhPcbEQySAsyT+WSeKVJspLgoWq1PemSBmSs6ZPywJ85ETLwSwlxstMyr2IjKM7JqOy4zex+U+pOiOBwt8zobhllCgZ8Fl/sJywxwzrzbia/JXM4uNs5xV8GdUZUVIhjTN7PeR692S9tIndYTQYCZtGMIbsWNtkDSXheHDFltsoQMkfRag52gijV3qiM3hHfdWFMTgYSN+giQr3m6PprCsDDDjepAdZEJemlxsq+ZSkTQ4MoINAIBJHlCcN9Eh6NAb59T2paWi6A6dCs3bdXZJ8KhyiNhFADos2c4Jgld8ndK2vPL9h2w5EhnMTRc0upKIJ6XxlG4nwYZzPlm15q1KckJVYavP91AA4t/J8RPLnkvS+9zs72qmYIOhE90140EYGeiv8l0PHdpoIbGG7USuHOmR2xINWNSoMP5qwPW0UYEWctFc34wugbvPZur1T0XP9ZHb/Gi0+RVnMNcf9TatyTyGW59E5OpUYg7zyWs9hUA2K7tyxkxbNb/MQY73Sg7xuX/FlxLIfGsQY7wZ14u8TAm2TZS2SD6KrvWlrTtUaNxELFB9X9ePkMiUIk7VCUZBhrcHchcDmgLRNfcqw9xv70ZxWCJArPfXxOIUAxu3LKxewFTiI1uLOa/1N4qKDSYw60Rxk1P+1/3MmOI7+Cbgf4ZOHAVgBwQ/avu8BnJa2N0TcPRsfiDXECAMmhWxAjgAOuudIBZd+EQcXCNC0kAcOW/43yaveHwvN+GnuU/KH1FPEtKlcBNdJkv3vQcwMMFJvza1x9ClYSj1Sh7dsLxIHIWjeCm87hseatujx2qVlYtiulWSMUku6LoVpmBLc4uzzdcd1JbXBg==
  template:
    metadata:
      name: props-openai-api-key
      namespace: props
