---
- hosts: localhost
  vars:
    my_user: agentydragon
    home_path: "/home/{{ my_user }}"
    scripts_path: "{{ home_path }}/bin"
    local_scripts_path: "{{ home_path }}/.local/bin"
    ducktape_path: "{{ home_path }}/code/ducktape"
    rcup_computer: gpd
  remote_user: "{{ my_user }}"
  roles:
    - role: jaredhocutt.gnome_extensions
      vars:
        gnome_extension_ids:
          # gTile - https://extensions.gnome.org/extension/28/gtile/
          # Not needed on Pop! OS
          # Install gTile.
          # - 28

          # Desaturate All - https://extensions.gnome.org/extension/1102/desaturate-all/
          - 1102

          ## Panel Date Format
          # https://extensions.gnome.org/extension/1462/panel-date-format/
          # https://github.com/KEIII/gnome-shell-panel-date-format
          - 1462

          ## Night Theme Switcher
          # For auto-switching gnome-terminal themes following GNOME night theme.
          #
          # https://extensions.gnome.org/extension/2236/night-theme-switcher/
          - 2236

    - common
    - anki
    - gnome-terminal-solarized
    - google-drive-client
    - timekpr

  tasks:
    - name: Set Night Theme Switcher to also switch gnome-terminal & nvim colors
      # TODO: dedupe
      block:
        - ansible.builtin.dconf:
            key: "/org/gnome/shell/extensions/nightthemeswitcher/commands/enabled"
            value: "true"
        - ansible.builtin.dconf:
            key: "/org/gnome/shell/extensions/nightthemeswitcher/commands/sunrise"
            value: "'set_light_theme'"
        - ansible.builtin.dconf:
            key: "/org/gnome/shell/extensions/nightthemeswitcher/commands/sunset"
            value: "'set_dark_theme'"

    - name: Set Gnome top panel datetime format
      ansible.builtin.dconf:
        key: "/org/gnome/shell/extensions/panel-date-format/format"
        value: "'%a %Y-%m-%d %H:%M'"  # e.g.: "Wed 2023-11-15 22:49"
      tags:
        - gnome-shell-datetime-format

    - name: Set zsh as login shell
      become: true
      tags:
        - zsh
      user:
        name: "{{ my_user }}"
        shell: /bin/zsh

    - name: Install packages for laptop
      become: true
      ansible.builtin.apt:
        pkg:
          - acpi
          - blender
          - flameshot  # Nice screenshot tool.
          - locate
          - powertop
          - torbrowser-launcher
          - transmission-gtk
          - virtualbox
          - virtualbox-dkms
          - vlc
          - wine-stable
          - wireshark
          - xournal

          # For getting background color for Vim background color auto-switch.
          - xtermcontrol

          # TODO: add Ubuntu startup programs, like Flameshot etc.


    - name: Install Rescuetime
      tags:
        - rescuetime
      become: true
      when: ansible_architecture == "amd64" or ansible_architecture == "x86_64"
      ansible.builtin.apt:
        deb: https://www.rescuetime.com/installers/rescuetime_current_amd64.deb

    - name: Enable Gnome Night Light
      tags:
        - nightlight
      block:
        - dconf:
            key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
            value: "true"
        - dconf:
            key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
            value: "uint32 2414"

    - name: Update githooks
      tags:
        - githooks
      # should only succeed if we don't need to update
      ansible.builtin.shell: git hooks update --no

    # GPD Win Max 2's right tracking stick pretends to be a mouse,
    # which limits the maximum speed that libinput easily allows with it.
    - name: Add udev rule GPD right tracking stick
      become: true
      tags:
      - gpd-quirks
      ansible.builtin.copy:
        content: |
          # This is a pointing stick pretending to be a mouse. Make libinput
          # interpret it as a "pointing stick" (/ "trackpoint"). Keep
          # ID_INPUT_MOUSE=1, because that makes Xorg's MatchIsPointer match
          # it and direct it to libinput for handling.
          ACTION=="add|change", SUBSYSTEMS=="input", ATTRS{id/vendor}=="2f24", ATTRS{id/product}=="0135", ENV{ID_INPUT_POINTINGSTICK}="1"
        dest: /etc/udev/rules.d/99-gpd-trackpoint.rules
        owner: root
        group: root
        mode: '0644'

    # trying out on 2023-11-24: install Telegram as snap
    - name: Install Telegram as snap
      tags:
        - telegram
      block:

      - name: Install snapd for Telegram
        become: true
        ansible.builtin.apt:
          pkg:
            - snapd

      - name: Install Telegram snap
        become: true
        snap:
          name: telegram-desktop
