all:
  hosts:
    vps:
      ansible_host: agentydragon.com
    agentydragon:
      ansible_connection: local
    gpd:
      ansible_connection: local
    wyrm:
      # ansible_connection: local
      ansible_connection: local # _cached_sudo
      ansible_become_pass_ask: true
      # ansible_host: 10.0.167.15
      # ansible_user: agentydragon
    atlas:
      ansible_host: atlas
      ansible_user: root
