wg_peers:
  hosts:
    vps:
    agentydragon:
    gpd:
    homeassistant: # (not managed by Ansible but included in mesh)
    pixel6: # Pixel 6 phone
    new-vm:
    atlas: # Proxmox host

all:
  hosts:
    vps:
      ansible_host: agentydragon.com
    agentydragon:
      ansible_connection: local_cached_sudo
      # (pyenv breaks interpreter detection)
      ansible_python_interpreter: /usr/bin/python3
    gpd:
      ansible_connection: local_cached_sudo
      # (pyenv breaks interpreter detection)
      ansible_python_interpreter: /usr/bin/python3
    new-vm:
      ansible_host: 10.0.167.15
      ansible_user: agentydragon
    atlas:
      ansible_host: 10.0.182.102  # on home network
      ansible_user: root

k3s_nodes:
  hosts:
    k3s-master:
      ansible_host: 10.0.167.200
      ansible_user: ubuntu
    k3s-worker:
      ansible_host: 10.0.167.201
      ansible_user: ubuntu
