---
- name: Check installed version file for {{ item }}
  ansible.builtin.stat:
    path: "{{ installed_version_path }}"
  register: version_file
  changed_when: false

- name: Read installed version file for {{ item }}
  ansible.builtin.slurp:
    src: "{{ installed_version_path }}"
  register: installed_version
  when: version_file.stat.exists
  changed_when: false

- name: Decide whether to reinstall {{ item }}
  ansible.builtin.set_fact:
    # b64decode: slurp reads content base64-encoded
    need_install: >-
      {{ (
        not version_file.stat.exists
        or (installed_version.content | b64decode | trim != nerd_fonts_version.stdout | trim)
      ) }}
  changed_when: false

- name: Debug info about reinstall need
  ansible.builtin.debug:
    msg: "{{ item }}: reinstall needed? -> {{ need_install }}"
    verbosity: 1

- name: Download & install {{ item }}
  when: need_install
  block:
    - name: Ensure dir exists for {{ item }}
      ansible.builtin.file:
        path: "{{ family_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Get download URL for {{ item }}
      ansible.builtin.shell: |
        set -o pipefail
        jq --raw-output '.assets[]
          | select(.name == "{{ item }}.tar.xz")
          | .browser_download_url' {{ latest_release_json_path }}
      register: font_download_url
      changed_when: false
      args:
        executable: /bin/bash

    - name: Assert URL was found for {{ item }}
      ansible.builtin.assert:
        that:
          - font_download_url.stdout != ""

    - name: Download and extract font archive for {{ item }}
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ font_download_url.stdout }}"
        dest: "{{ family_path }}"
        mode: '0644'
      register: unarchived_font

      notify:
        - update font version file
        - mark fonts updated
