apiVersion: v1
kind: Secret
metadata:
    name: drivefs-artifacts-s3-credentials
    namespace: seaweedfs
    annotations:
        description: Credentials used only by the dedicated drivefs-artifacts S3 gateway.
type: Opaque
stringData:
    writerAccessKey: ENC[AES256_GCM,data:HGzZ8pA2KQakt4DgDbIu6jZYGzx7SeYvMivj,iv:1iOaBUDcl7wlQ+L6vK+GBq/PCH8wQkoSPI7CVCn/OLg=,tag:M87TJwZpO21QjT/XX1GZYA==,type:str]
    writerSecretKey: ENC[AES256_GCM,data:Ur/205s9xeGfPncwmMyILBiwwgEzdcgcUcVBUc9KfrOOzGC+9jrp2D5a0L6kN6jo3gxe3U3M,iv:m9G3qUSJwA7kQ994S26P2pw7XuK8kXBKfSgXdNqcIPc=,tag:x6yxDLSNgknxk9bGRX4i4g==,type:str]
    readerAccessKey: ENC[AES256_GCM,data:O6xu3AGF1FWGSYMFqtTZUeULlaJVW4/Lla2l,iv:Npk6bLAhM2MHq2kw6Alt5xlEPsxYGXZi00axgWQkGf8=,tag:fXqHbWwCgt1CJVpqWZoO9g==,type:str]
    readerSecretKey: ENC[AES256_GCM,data:vWUu0QG6mXUV4+ZEXdQsaY5XkGyopagqjE96EEgh4dmmFRLbTd60r48HNJMRFaZ18PCBypfb,iv:HtgB1tuK8/yhfxLfVLNsy1MD46uBcnoUboEhgJqbWRg=,tag:DhyqZaDFmrQgbKe2g5Iv9w==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWDlSNnJFd0xZdTM4UlZJ
            NFI1L0tGcDFDNzZYNEF0aHduMEh2c2VHelg4CkFkN0FPZUdsTTk4RHRtdDhMWlBr
            VTRPSjNLOElSWWpLNmhHVUlla01Cd3cKLS0tIExQL015eW5lM1ZBY0U4aXFOajI1
            aEJObnJUdFFtSVBYNWpwRWdyTlIzV1kKWf9fOJL/G3/KFf0nxLT0+fQIbrKNkLEb
            MvfoNzL5+bwXnqGy5MyLV7SHr/4StakWNLC2JAGChDxx7WkqjSFZ7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVUpJdTk5VWwvWHVvZ0JX
            WWZkUExvcXRXdWRBSGhNWGFmTEd0SnBnZWhrCk1BRUd0L0NaMGRuVUxocWY2cDVN
            Zm1ZLzZORHFteVUwNFgxYkZtMjlmUUUKLS0tIG5wT3hUZ3ZzZG5SOHpFSHppM0dG
            WWVsdGQyTVAwRWhuQWtPMmNtTlFLZHcKU01RUziymL7qPlnXGsWFbFHyQbEFRlfp
            DRaQBhLwJfaoA2iYN7euDenf7HgGXoinH8zS3pFVZkyA5J8RxMBXBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T22:42:31Z"
    mac: ENC[AES256_GCM,data:NPJ7V9sjM0RScgFwETPlnngPNPBR8kyAqKsZO2yaO+hQz6Lm0ABmAT39OFNJhBtHw+FpXppUmRbEl2qjxMw74hIJ2c0kjXpAt1hl64V92k4L6GoNyfgAhyhrqwrYdtYXQdILT+kugzq1x/OwB7tL2SQTEFAdMbbF2b50YXtfBdk=,iv:wEgsiZkcYSjl9+c9VpYJp2Og05YL5TMdoiVTGX0nX/c=,tag:nfPjfxmsLPf6TRPMxuLXcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
