load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "headscale": "awlsring/headscale:~>0.5.0",
        "vault": "hashicorp/vault:~>5.7.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "headscale-config",
    providers = [
        "headscale",
        "vault",
    ],
    providers_versions = ":providers",
)
