load("@rules_tf//tf:def.bzl", "tf_module", "tf_providers_versions")

tf_providers_versions(
    name = "providers",
    providers = {
        "vault": "hashicorp/vault:~>5.7.0",
        "grafana": "grafana/grafana:~>3.22.0",
    },
    tf_version = "1.9.8",
)

tf_module(
    name = "grafana-flux-token",
    providers = [
        "vault",
        "grafana",
    ],
    providers_versions = ":providers",
)
