# NixOS K8s Worker — NixOS VM joining the Talos cluster via KubeSpan
#
# Lifecycle: Independent of the cluster bootstrap (infrastructure/).
# Destroying the cluster does not destroy this VM.
#
# After boot: systemctl start kubespand && systemctl start kubelet
# Then approve CSR: kubectl certificate approve <csr-name>

# =============================================================================
# REMOTE STATE
# =============================================================================

data "terraform_remote_state" "persistent_auth" {
  backend = "local"
  config = {
    path = "../persistent-auth/terraform.tfstate"
  }
}

# =============================================================================
# LOCALS
# =============================================================================

locals {
  proxmox_endpoint = "https://${var.proxmox_api_host}/"

  # SSH key handling - try common key types in order of preference
  ssh_key_candidates = [
    pathexpand("~/.ssh/id_ed25519.pub"),
    pathexpand("~/.ssh/id_ecdsa.pub"),
    pathexpand("~/.ssh/id_rsa.pub")
  ]
  ssh_key_path = var.ssh_public_key != "" ? "" : (
    fileexists(local.ssh_key_candidates[0]) ? local.ssh_key_candidates[0] :
    fileexists(local.ssh_key_candidates[1]) ? local.ssh_key_candidates[1] :
    fileexists(local.ssh_key_candidates[2]) ? local.ssh_key_candidates[2] :
    ""
  )
  ssh_public_key = var.ssh_public_key != "" ? var.ssh_public_key : (
    local.ssh_key_path != "" ? trimspace(file(local.ssh_key_path)) : ""
  )
}

# =============================================================================
# PROVIDERS
# =============================================================================

provider "proxmox" {
  endpoint  = local.proxmox_endpoint
  username  = "terraform@pve"
  api_token = data.terraform_remote_state.persistent_auth.outputs.terraform_pve_token.token
  insecure  = true

  ssh {
    agent    = true
    username = "root"
    node {
      name    = var.proxmox_node_name
      address = var.proxmox_host
    }
  }
}

# =============================================================================
# VALIDATION
# =============================================================================

check "ssh_key_required" {
  assert {
    condition     = local.ssh_public_key != ""
    error_message = "No SSH public key found. Provide via ssh_public_key variable or create ~/.ssh/id_ed25519."
  }
}

check "k8s_join_prerequisites" {
  assert {
    condition     = !var.enable_k8s_cluster_join || var.k8s_controlplane_node != ""
    error_message = "k8s_controlplane_node is required when enable_k8s_cluster_join is true."
  }
}

# =============================================================================
# NIXOS CLOUD IMAGE
# =============================================================================

# Build and upload NixOS cloud image (idempotent — same image as nixos-dev-env)
resource "null_resource" "nixos_cloud_image" {
  triggers = {
    cloud_image_config = filemd5("${path.module}/../../../../terraform/modules/nixos-vm/cloud-image.nix")
    proxmox_host       = var.proxmox_host
    storage            = var.storage
  }

  provisioner "local-exec" {
    command     = <<-EOT
      set -e
      echo "Building NixOS qcow2 cloud image..."

      nix run github:nix-community/nixos-generators -- \
        --format qcow-efi \
        --configuration ${path.module}/../../../../terraform/modules/nixos-vm/cloud-image.nix \
        -o nixos-cloud-image

      QCOW2_PATH=$(readlink -f nixos-cloud-image)/nixos.qcow2

      echo "Uploading qcow2 to Proxmox import directory..."
      ssh root@${var.proxmox_host} "mkdir -p /var/lib/vz/import"
      scp "$QCOW2_PATH" "root@${var.proxmox_host}:/var/lib/vz/import/nixos-cloud.qcow2"

      echo "qcow2 image ready for import at local:import/nixos-cloud.qcow2"
    EOT
    working_dir = path.module
  }
}

# =============================================================================
# K8S CLUSTER JOIN CREDENTIALS
# =============================================================================

# Extract cluster credentials from Talos control plane via talosctl.
# Uses the talosconfig generated by the infrastructure layer.
data "external" "k8s_credentials" {
  count = var.enable_k8s_cluster_join ? 1 : 0

  program = [
    "bash", "-c",
    "export CP_NODE='${var.k8s_controlplane_node}' TALOSCONFIG='${path.module}/../infrastructure/talosconfig.yml'; exec python3 '${path.module}/scripts/extract_k8s_credentials.py'"
  ]
}

# =============================================================================
# VM INSTANCE
# =============================================================================

module "k8s_worker_test" {
  source = "../../../../terraform/modules/nixos-vm"

  vm_name      = "k8s-worker-test"
  vm_id        = 111
  username     = var.username
  vcpus        = 4
  memory_mb    = 8192
  disk_size_gb = 50
  auto_start   = true

  nixos_flake_url        = var.nixos_flake_url
  nixos_host             = "k8s-worker-test"
  home_manager_flake_url = var.home_manager_flake_url
  home_manager_host      = var.home_manager_host

  proxmox_node_name = var.proxmox_node_name
  storage           = var.storage
  network_bridge    = var.network_bridge
  ssh_public_key    = local.ssh_public_key

  k8s_cluster_join = var.enable_k8s_cluster_join ? {
    bootstrap_kubeconfig = data.external.k8s_credentials[0].result.bootstrap_kubeconfig
    ca_cert              = data.external.k8s_credentials[0].result.ca_cert
    cluster_id           = data.external.k8s_credentials[0].result.cluster_id
    cluster_secret       = data.external.k8s_credentials[0].result.cluster_secret
    node_name            = "k8s-worker-test"
  } : null

  depends_on = [null_resource.nixos_cloud_image]
}
