apiVersion: ENC[AES256_GCM,data:5l4=,iv:rLc/6JyBQcB1A0wzwLZh38iVV+I2V4oWjlzRkqZt794=,tag:3cxI+dZpnwC/v2/D6vC8UQ==,type:str]
kind: ENC[AES256_GCM,data:pVEfTVDL,iv:WRnUIL6T+OzxhR1KXfPynjeRfNfcoCTV34YFELT1kJk=,tag:eWVdGaIU7fzmaFSr2gDI8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P8fhKoOsiito1J+s,iv:cGiUYqs43phXq/EErje1b0/hBWrgLbTPzhpMEGkRJT4=,tag:1+GBhg6ervYoC2nyDm87Zw==,type:str]
    namespace: ENC[AES256_GCM,data:sKNn8c73a7KJiZM=,iv:S3LRzmLjZbJATnWzM3nj3669SzrtffMgF9a5jrcAEbM=,tag:AONkD88ibqYvxTR21TXP5A==,type:str]
    annotations:
        description: ENC[AES256_GCM,data:P/0AWvOs5iAy5Bcy21Kg/mNtyeSN3b4JtTrMJtaEy4plM1cIPw0MIf2ENDkK3A==,iv:qUJPPLKJa2rDBAwWZdlsrLGp/FkrBQNCxHcEIF6FKUo=,tag:kznPwE3lKWF865gDM5H5gQ==,type:str]
type: ENC[AES256_GCM,data:wany+yzB,iv:Wri/P2C+8ZZ/RdJsozqBnISz6FGnOuRLDP7SbFFN5WU=,tag:pXc85GLKGft/IgVXnWaMRg==,type:str]
stringData:
    address: ENC[AES256_GCM,data:llaJLnHKF3mh7QSDUQYuPz1OuU6jgsyhiZ+5l2kdVUsXtdFq0yUGMqtskRvTrA==,iv:VaQjfiDXMblr205PBH1vPSAztKhjof/+MJa/NBAjHSc=,tag:JlXqkaY/QyplQWEGDxTNqA==,type:str]
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaXNtY3hYT0l0Mkk5aGRI
            NEhtL2ZVTXJmZ1ZIYk80WEZCNzd0S2VNK0JFClBicnRJczRHdmR6a2tBcTZVS1NP
            Q0lCUVJETE5kd3ljOGxSUVpSYklySGMKLS0tIEdGNk4yaFRTdHYwdnhyT1VaaW9L
            VjI3TjcvV0hMZHhYL2RrbldCbHpneWsKqM0gcesuvn2Zp8Uw9W5/kU323jKZj+s4
            K4KFsbmbT0vD8jCItBLKPDerPruBAAzADI2USonfh07deVwkys+ztA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb3ZPY0VpUDZtU091RXBX
            SHBCcnNVNE5lQUNpYnFSTzJrTHoxL21jS213CmJYdHpmVHBIYkl6UG1rWlRTaGk3
            aGpieWhnVzhadmlteWZyTlZhRVI0MlUKLS0tIGtRWWRma2w1bmlGNUVjWGhDNkJJ
            bDFlLzlZbllSZ3RVWVlwajJ5YmVJSFUKoHMS/e2v8Z1EP6K0U17Y0iqvwBg5u0cp
            VWj2I598rmHxT6LK/tqQD+CyU7wCGVOw1GgR+g823nJ7W4a78i0ahQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T07:41:37Z"
    mac: ENC[AES256_GCM,data:luSYTS5/Ntq54Qh3anOO1NB8TFxs4/+VmlYyMMk5YhfSEGFL18dvMkYEfWMgMi4DDGKmMLzQPNRltBji0aY86bVjBG4NemKpfKwd8OF2Ip6vuSs3pKJ43DhxAfYfyq1K8lXUcGBbbd83154xh0X5swWyYSQRJQfYB8qyYKKSHzg=,iv:q05ELgntnm5SB4fC9WwxucLTTZZRDAZuAK6HvQ2XJkg=,tag:zSF60FaGbDY7oP77RDFolg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
