/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/stats/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Overview */
    get: operations["get_overview_api_stats_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stats/definitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Definitions
     * @description List all agent definitions, optionally filtered by type.
     */
    get: operations["list_definitions_api_stats_definitions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stats/definitions/{definition_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Definition Detail
     * @description Get detailed stats for a single definition including per-example breakdown.
     */
    get: operations["get_definition_detail_api_stats_definitions__definition_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stats/examples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Example Detail
     * @description Get detailed information about a specific example.
     *
     *     Query parameters:
     *         snapshot_slug: Snapshot identifier (e.g., "ducktape/2025-11-20-00")
     *         example_kind: Example kind (whole_snapshot or file_set)
     *         files_hash: Files hash (required for file_set, must be None for whole_snapshot)
     *
     *     Returns:
     *         Detailed example information including:
     *         - Example metadata (split, recall_denominator)
     *         - File list (for file_set examples)
     *         - Per-definition run statistics
     *         - Aggregate metrics
     */
    get: operations["get_example_detail_api_stats_examples_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Active Runs
     * @description List all active agent runs.
     *
     *     Returns runs from both:
     *     - In-memory registry (currently executing)
     *     - Database (IN_PROGRESS status, for runs that may have started before we connected)
     */
    get: operations["list_active_runs_api_runs_active_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Jobs
     * @description List all validation jobs.
     */
    get: operations["list_jobs_api_runs_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Runs
     * @description List all agent runs with optional filters and pagination.
     *
     *     Query parameters:
     *     - status: Filter by run status
     *     - definition_id: Filter by definition ID
     *     - agent_type: Filter by agent type (critic, grader, etc.)
     *     - split: Filter by data split (train, valid, test)
     *     - example_kind: Filter by example kind (whole_snapshot, file_set)
     *     - offset: Pagination offset (default: 0)
     *     - limit: Pagination limit (default: 100, max: 500)
     */
    get: operations["list_runs_api_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/validation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger Validation Runs
     * @description Trigger validation runs: sample N examples, run 1 critic->grader per example.
     *
     *     Runs are started in the background in parallel. Poll /api/runs/jobs for status.
     *     Registry semaphore limits actual concurrency.
     */
    post: operations["trigger_validation_runs_api_runs_validation_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/run/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run
     * @description Get details of a specific agent run.
     */
    get: operations["get_run_api_runs_run__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/run/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run Events
     * @description Get events for a specific agent run.
     *
     *     Supports pagination via offset/limit. Events are ordered by sequence_num.
     */
    get: operations["get_run_events_api_runs_run__run_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/gt/snapshots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Snapshots
     * @description List all snapshots with issue counts.
     */
    get: operations["list_snapshots_api_gt_snapshots_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/gt/snapshots/{snapshot_slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Snapshot Detail
     * @description Get detailed snapshot info with all TPs and FPs.
     */
    get: operations["get_snapshot_detail_api_gt_snapshots__snapshot_slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/gt/snapshots/{snapshot_slug}/tree": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Snapshot Tree
     * @description Get directory tree with issue occurrence counts.
     */
    get: operations["get_snapshot_tree_api_gt_snapshots__snapshot_slug__tree_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/gt/snapshots/{snapshot_slug}/files/{file_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Snapshot File
     * @description Get file content from snapshot tar archive.
     */
    get: operations["get_snapshot_file_api_gt_snapshots__snapshot_slug__files__file_path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActiveRunInfo */
    ActiveRunInfo: {
      /**
       * Agent Run Id
       * Format: uuid
       */
      agent_run_id: string;
      /** Definition Id */
      definition_id: string;
      /** Model */
      model: string;
      status: components["schemas"]["AgentRunStatus"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ActiveRunsResponse */
    ActiveRunsResponse: {
      /** Runs */
      runs: components["schemas"]["ActiveRunInfo"][];
    };
    /**
     * AgentRunDetail
     * @description Detailed view of an agent run with type-specific details nested.
     */
    AgentRunDetail: {
      /**
       * Agent Run Id
       * Format: uuid
       */
      agent_run_id: string;
      /** Definition Id */
      definition_id: string;
      /** Parent Agent Run Id */
      parent_agent_run_id: string | null;
      /** Model */
      model: string;
      status: components["schemas"]["AgentRunStatus"];
      /** Completion Summary */
      completion_summary: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Type Config */
      type_config:
        | components["schemas"]["CriticTypeConfig"]
        | components["schemas"]["GraderTypeConfig"]
        | components["schemas"]["SnapshotGraderTypeConfig"]
        | components["schemas"]["FreeformTypeConfig"]
        | components["schemas"]["PromptOptimizerTypeConfig"]
        | components["schemas"]["ImprovementTypeConfig"];
      /** Event Count */
      event_count: number;
      /** Child Runs */
      child_runs: components["schemas"]["ChildRunInfo"][];
      /** Details */
      details:
        | components["schemas"]["CriticRunSpecifics"]
        | components["schemas"]["GraderRunSpecifics"]
        | components["schemas"]["OtherRunSpecifics"];
    };
    /**
     * AgentRunStatus
     * @description Agent run status enumeration.
     *
     *     Unified status for all agent types (critic, grader, prompt_optimizer, etc.).
     * @enum {string}
     */
    AgentRunStatus: "in_progress" | "completed" | "max_turns_exceeded" | "context_length_exceeded" | "reported_failure";
    /**
     * AgentType
     * @description Types of agents in the system.
     *
     *     Each agent type has different:
     *     - MCP server class attached via MCP-over-HTTP
     *     - Handler configuration (run-to-completion vs conversational)
     *     - Database access (RLS policies)
     *     - Mount requirements
     * @enum {string}
     */
    AgentType: "critic" | "grader" | "snapshot_grader" | "prompt_optimizer" | "improvement" | "freeform";
    /**
     * ApiRequest
     * @description Full OpenAI API request payload (before sending).
     *
     *     Captures the complete request including fully-evaluated instructions.
     */
    ApiRequest: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "api_request";
      request: components["schemas"]["ResponsesRequest"];
      /** Model */
      model: string;
      /**
       * Request Id
       * Format: uuid
       */
      request_id: string;
      /** Phase Number */
      phase_number: number;
    };
    /** AssistantMessage */
    AssistantMessage: {
      /**
       * Role
       * @default assistant
       * @constant
       */
      role: "assistant";
      /** Content */
      content?: components["schemas"]["OutputTextPart"][] | null;
      /** Id */
      id?: string | null;
    } & {
      [key: string]: unknown;
    };
    /** AssistantText */
    AssistantText: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "assistant_text";
      /** Text */
      text: string;
    };
    /**
     * BaseExecResult
     * @description Standard MCP exec response - basic servers return this directly (output model).
     *
     *     Preserves str | TruncatedStream distinction to encode truncation information.
     */
    BaseExecResult: {
      /** Exit */
      exit: components["schemas"]["TimedOut"] | components["schemas"]["Exited"] | components["schemas"]["Killed"];
      /** Stdout */
      stdout: string | components["schemas"]["TruncatedStream"];
      /** Stderr */
      stderr: string | components["schemas"]["TruncatedStream"];
      /**
       * Duration Ms
       * @description Execution duration in milliseconds
       */
      duration_ms: number;
    };
    /**
     * ChildRunInfo
     * @description Brief info about a child agent run.
     */
    ChildRunInfo: {
      /**
       * Agent Run Id
       * Format: uuid
       */
      agent_run_id: string;
      agent_type: components["schemas"]["AgentType"];
      status: components["schemas"]["AgentRunStatus"];
    };
    /**
     * CriticRunSpecifics
     * @description Critic-specific fields.
     */
    CriticRunSpecifics: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "critic";
      /** Resolved Files */
      resolved_files: string[] | null;
      /** Grader Runs */
      grader_runs: components["schemas"]["GraderRunInfo"][];
      /** Reported Issues */
      reported_issues: components["schemas"]["ReportedIssueInfo"][];
    };
    /**
     * CriticTypeConfig
     * @description Critic-specific configuration.
     *
     *     Critics analyze code snapshots and report issues.
     *     The example specifies which snapshot and scope (whole-snapshot or single-trigger-set) to evaluate.
     */
    CriticTypeConfig: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "critic";
      /** Example */
      example: components["schemas"]["WholeSnapshotExample"] | components["schemas"]["SingleFileSetExample"];
    };
    /** DefinitionDetailResponse */
    DefinitionDetailResponse: {
      /** Definition Id */
      definition_id: string;
      agent_type: components["schemas"]["AgentType"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Stats */
      stats: {
        [key: string]: {
          [key: string]: components["schemas"]["SplitScopeStats"];
        };
      };
      /** Examples */
      examples: components["schemas"]["ExampleStats"][];
    };
    /** DefinitionInfo */
    DefinitionInfo: {
      /** Definition Id */
      definition_id: string;
      agent_type: components["schemas"]["AgentType"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** DefinitionRow */
    DefinitionRow: {
      /** Definition Id */
      definition_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Stats */
      stats: {
        [key: string]: {
          [key: string]: components["schemas"]["SplitScopeStats"];
        };
      };
    };
    /**
     * DefinitionStatsForExample
     * @description Stats for a single definition on this example.
     */
    DefinitionStatsForExample: {
      /** Definition Id */
      definition_id: string;
      /** Model */
      model: string;
      /** N Runs */
      n_runs: number;
      /** Status Counts */
      status_counts: {
        [key: string]: number;
      };
      credit_stats: components["schemas"]["StatsWithCI"] | null;
    };
    /** DefinitionsResponse */
    DefinitionsResponse: {
      /** Definitions */
      definitions: components["schemas"]["DefinitionInfo"][];
    };
    /**
     * DockerExecCallPayload
     * @description Parsed docker_exec tool call.
     */
    DockerExecCallPayload: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "docker_exec_call";
      /** Call Id */
      call_id: string;
      input: components["schemas"]["ExecInput"];
    };
    /**
     * DockerExecOutputPayload
     * @description Parsed docker_exec tool output.
     */
    DockerExecOutputPayload: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "docker_exec_output";
      /** Call Id */
      call_id: string;
      result: components["schemas"]["BaseExecResult"];
    };
    /**
     * EventsResponse
     * @description Response for events endpoint.
     */
    EventsResponse: {
      /**
       * Agent Run Id
       * Format: uuid
       */
      agent_run_id: string;
      /** Events */
      events: components["schemas"]["ParsedEventInfo"][];
      /** Total Count */
      total_count: number;
    };
    /**
     * ExampleDetailResponse
     * @description Detailed view of a single example.
     */
    ExampleDetailResponse: {
      /** Snapshot Slug */
      snapshot_slug: string;
      example_kind: components["schemas"]["ExampleKind"];
      /** Files Hash */
      files_hash: string | null;
      split: components["schemas"]["Split"];
      /** Recall Denominator */
      recall_denominator: number;
      /** Files */
      files: string[] | null;
      /** Definitions */
      definitions: components["schemas"]["DefinitionStatsForExample"][];
      credit_stats: components["schemas"]["StatsWithCI"] | null;
    };
    /**
     * ExampleKind
     * @description Discriminator values for ExampleSpec union.
     *
     *     Matches the PostgreSQL example_kind_enum type values exactly.
     * @enum {string}
     */
    ExampleKind: "whole_snapshot" | "file_set";
    /** ExampleStats */
    ExampleStats: {
      /** Snapshot Slug */
      snapshot_slug: string;
      example_kind: components["schemas"]["ExampleKind"];
      /** Files Hash */
      files_hash: string | null;
      split: components["schemas"]["Split"];
      /** Recall Denominator */
      recall_denominator: number;
      /** N Runs */
      n_runs: number;
      /** Status Counts */
      status_counts: {
        [key: string]: number;
      };
      credit_stats: components["schemas"]["StatsWithCI"] | null;
    };
    /**
     * ExecInput
     * @description Typed payload for container exec tool.
     *
     *     Note: TTY is not allocated for processes to ensure stdout/stderr separation.
     */
    ExecInput: {
      /**
       * Cmd
       * @description Command array passed directly to Docker exec API (no shell). DO NOT include shell quotes around arguments - array elements are passed as-is. WRONG: ['sed', '-n', "'1,10p'", 'file'] (quotes in string). RIGHT: ['sed', '-n', '1,10p', 'file'] (no quotes). For shell features (pipes, globs), use: ['sh', '-c', 'sed -n 1,10p file | head']
       */
      cmd: string[];
      /**
       * Cwd
       * @description Working directory inside container (None = container default)
       */
      cwd: string | null;
      /**
       * Env
       * @description Environment variables as ['NAME=value', ...] (None = inherit container env)
       */
      env: string[] | null;
      /**
       * User
       * @description Username inside container (None = container default)
       */
      user: string | null;
      /**
       * Timeout Ms
       * @description Timeout in milliseconds; sends TERM (exit status becomes TimedOut)
       */
      timeout_ms: number;
    };
    /**
     * Exited
     * @description Process exited normally with an exit code.
     */
    Exited: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "exited";
      /** Exit Code */
      exit_code: number;
    };
    /**
     * FileContentResponse
     * @description File content from snapshot.
     */
    FileContentResponse: {
      /** Path */
      path: string;
      /** Content */
      content: string;
      /** Line Count */
      line_count: number;
    };
    /**
     * FileLocationInfo
     * @description File with optional line ranges.
     */
    FileLocationInfo: {
      /** Path */
      path: string;
      /** Ranges */
      ranges: components["schemas"]["LineRange"][] | null;
    };
    /**
     * FileTreeNode
     * @description Node in file tree (file or directory).
     */
    FileTreeNode: {
      /** Path */
      path: string;
      /** Name */
      name: string;
      /** Is Dir */
      is_dir: boolean;
      /**
       * Tp Count
       * @default 0
       */
      tp_count: number;
      /**
       * Fp Count
       * @default 0
       */
      fp_count: number;
      /** Children */
      children?: components["schemas"]["FileTreeNode"][] | null;
    };
    /**
     * FileTreeResponse
     * @description Directory tree with issue counts.
     */
    FileTreeResponse: {
      /** Tree */
      tree: components["schemas"]["FileTreeNode"][];
    };
    /**
     * FpInfo
     * @description False positive issue info.
     */
    FpInfo: {
      /** Fp Id */
      fp_id: string;
      /** Rationale */
      rationale: string;
      /** Occurrences */
      occurrences: components["schemas"]["OccurrenceInfo"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * FpTarget
     * @description FP match target.
     */
    FpTarget: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "fp";
      /** Fp Id */
      fp_id: string;
      /** Occurrence Id */
      occurrence_id: string;
      /** Credit */
      credit: number;
    };
    /**
     * FreeformTypeConfig
     * @description Freeform sub-agent configuration.
     *
     *     Freeform agents are spawned by other agents (typically critics) for
     *     specialized tasks. They have minimal configuration - just the type marker.
     */
    FreeformTypeConfig: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "freeform";
    };
    /** FunctionCallItem */
    FunctionCallItem: {
      /**
       * Type
       * @default function_call
       * @constant
       */
      type: "function_call";
      /** Name */
      name: string;
      /** Arguments */
      arguments?: string | null;
      /** Call Id */
      call_id: string;
      /** Id */
      id?: string | null;
      /** Status */
      status?: string | null;
    } & {
      [key: string]: unknown;
    };
    /** FunctionCallOutputItem */
    FunctionCallOutputItem: {
      /**
       * Type
       * @default function_call_output
       * @constant
       */
      type: "function_call_output";
      /** Call Id */
      call_id: string;
      /** Output */
      output:
        | string
        | (components["schemas"]["FunctionOutputTextContent"] | components["schemas"]["FunctionOutputImageContent"])[];
    } & {
      [key: string]: unknown;
    };
    /**
     * FunctionOutputImageContent
     * @description Image content in function call output (sent to OpenAI API as input_image).
     */
    FunctionOutputImageContent: {
      /**
       * Type
       * @default input_image
       * @constant
       */
      type: "input_image";
      /** Image Url */
      image_url?: string | null;
      /** File Id */
      file_id?: string | null;
      /** Detail */
      detail?: ("low" | "high" | "auto") | null;
    } & {
      [key: string]: unknown;
    };
    /**
     * FunctionOutputTextContent
     * @description Text content in function call output (sent to OpenAI API as input_text).
     */
    FunctionOutputTextContent: {
      /**
       * Type
       * @default input_text
       * @constant
       */
      type: "input_text";
      /** Text */
      text: string;
    } & {
      [key: string]: unknown;
    };
    /**
     * FunctionToolParam
     * @description Typed mirror of OpenAI Responses function tool schema.
     *
     *     Shape compatible with the Responses API tools list items.
     */
    FunctionToolParam: {
      /**
       * Type
       * @default function
       * @constant
       */
      type: "function";
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Parameters */
      parameters?: {
        [key: string]: unknown;
      };
      /** Strict */
      strict?: boolean | null;
    };
    /**
     * GenericToolCallPayload
     * @description Unparsed tool call (fallback).
     */
    GenericToolCallPayload: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "tool_call";
      /** Name */
      name: string;
      /** Call Id */
      call_id: string;
      /** Args Json */
      args_json: string | null;
    };
    /**
     * GenericToolOutputPayload
     * @description Unparsed tool output (fallback).
     */
    GenericToolOutputPayload: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "tool_output";
      /** Call Id */
      call_id: string;
      /** Content */
      content: unknown[];
    };
    /**
     * GraderRunInfo
     * @description Info about a grader run that graded this critic.
     */
    GraderRunInfo: {
      /**
       * Agent Run Id
       * Format: uuid
       */
      agent_run_id: string;
      status: components["schemas"]["AgentRunStatus"];
      /** Grading Edges */
      grading_edges: components["schemas"]["GradingEdgeInfo"][];
    };
    /**
     * GraderRunSpecifics
     * @description Grader-specific fields.
     */
    GraderRunSpecifics: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "grader";
      /** Grading Edges */
      grading_edges: components["schemas"]["GradingEdgeInfo"][];
    };
    /**
     * GraderTypeConfig
     * @description Grader-specific configuration.
     *
     *     Graders evaluate critic output against ground truth.
     *
     *     The snapshot_slug for RLS is derived at runtime from the graded critic's type_config
     *     via SQL: (SELECT type_config->>'snapshot_slug' FROM agent_runs WHERE agent_run_id = graded_agent_run_id).
     *
     *     The canonical_issues_snapshot is populated at grading time and stores the TPs/FPs
     *     used during grading. This enables detecting stale grader runs after editing issue files.
     */
    GraderTypeConfig: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "grader";
      /**
       * Graded Agent Run Id
       * Format: uuid
       */
      graded_agent_run_id: string;
      /** Canonical Issues Snapshot */
      canonical_issues_snapshot?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * GradingEdgeInfo
     * @description Individual grading edge for API response.
     */
    GradingEdgeInfo: {
      /** Critique Issue Id */
      critique_issue_id: string;
      /** Target */
      target: components["schemas"]["TpTarget"] | components["schemas"]["FpTarget"];
      /** Rationale */
      rationale: string;
    };
    /** GroundTruthUsage */
    GroundTruthUsage: {
      /** Model */
      model: string;
      /** Input Tokens */
      input_tokens?: number | null;
      input_tokens_details?: components["schemas"]["InputTokensDetails"] | null;
      /** Output Tokens */
      output_tokens?: number | null;
      output_tokens_details?: components["schemas"]["OutputTokensDetails"] | null;
      /** Total Tokens */
      total_tokens?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * ImprovementTypeConfig
     * @description Improvement agent configuration.
     *
     *     Improvement agents analyze critic/grader runs and propose improved agent definitions.
     *
     *     RLS policies filter data access based on these fields:
     *     - Can read agent_definitions matching baseline_definition_ids
     *     - Can read agent_runs/events for runs on allowed_examples
     *     - Can create new definitions and run evals on allowed_examples
     */
    ImprovementTypeConfig: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "improvement";
      /**
       * Baseline Definition Ids
       * @description One or more agent definition IDs to study and improve
       */
      baseline_definition_ids: string[];
      /**
       * Allowed Examples
       * @description Training examples this agent can access (snapshot + scope)
       */
      allowed_examples: (
        | components["schemas"]["WholeSnapshotExample"]
        | components["schemas"]["SingleFileSetExample"]
      )[];
      /**
       * Improvement Model
       * @description Model used for the improvement agent itself
       */
      improvement_model: string;
      /**
       * Critic Model
       * @description Model used for critic evaluations
       */
      critic_model: string;
      /**
       * Grader Model
       * @description Model used for grader evaluations
       */
      grader_model: string;
    };
    /** InputTextPart */
    InputTextPart: {
      /**
       * Type
       * @default input_text
       * @constant
       */
      type: "input_text";
      /** Text */
      text: string;
    } & {
      [key: string]: unknown;
    };
    /**
     * InputTokensDetails
     * @description Token usage details for input (wrapped from OpenAI SDK).
     */
    InputTokensDetails: {
      /** Cached Tokens */
      cached_tokens: number;
    } & {
      [key: string]: unknown;
    };
    /**
     * JobInfo
     * @description Information about a validation job.
     */
    JobInfo: {
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /** Definition Id */
      definition_id: string;
      example_kind: components["schemas"]["ExampleKind"];
      /** N Samples */
      n_samples: number;
      status: components["schemas"]["JobStatus"];
      /** Completed */
      completed: number;
      /** Failed */
      failed: number;
    };
    /**
     * JobStatus
     * @description Validation job status.
     * @enum {string}
     */
    JobStatus: "running" | "completed" | "failed";
    /**
     * JobsResponse
     * @description Response for jobs endpoint.
     */
    JobsResponse: {
      /** Jobs */
      jobs: components["schemas"]["JobInfo"][];
    };
    /**
     * Killed
     * @description Process was killed by a signal.
     */
    Killed: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "killed";
      /** Signal */
      signal: number;
    };
    /** LineRange */
    LineRange: {
      /**
       * Start Line
       * @description 1-based start line number
       */
      start_line: number;
      /**
       * End Line
       * @description 1-based end line number (inclusive); None for single-line anchor
       */
      end_line: number | null;
      /**
       * Note
       * @description Optional per-range note explaining why this specific range matters (e.g., 'definition site' vs 'call site' within the same occurrence)
       */
      note?: string | null;
    };
    /**
     * OccurrenceInfo
     * @description Unified occurrence info for both TPs and FPs.
     */
    OccurrenceInfo: {
      /** Occurrence Id */
      occurrence_id: string;
      /** Files */
      files: components["schemas"]["FileLocationInfo"][];
      /** Note */
      note: string | null;
      /** Graders Match Only If Reported On */
      graders_match_only_if_reported_on: string[] | null;
      /** Critic Scopes Expected To Recall */
      critic_scopes_expected_to_recall?: string[][] | null;
      /** Relevant Files */
      relevant_files?: string[] | null;
    };
    /**
     * OtherRunSpecifics
     * @description Other agent types have no specific fields.
     */
    OtherRunSpecifics: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "freeform" | "improvement" | "prompt_optimizer" | "snapshot_grader";
    };
    /**
     * OutputTextPart
     * @description Text content from assistant messages.
     *
     *     When assistant messages appear in the input (multi-turn conversations),
     *     they use type='output_text' not 'input_text'.
     */
    OutputTextPart: {
      /**
       * Type
       * @default output_text
       * @constant
       */
      type: "output_text";
      /** Text */
      text: string;
    } & {
      [key: string]: unknown;
    };
    /**
     * OutputTokensDetails
     * @description Token usage details for output (wrapped from OpenAI SDK).
     */
    OutputTokensDetails: {
      /** Reasoning Tokens */
      reasoning_tokens: number;
    } & {
      [key: string]: unknown;
    };
    /** OverviewResponse */
    OverviewResponse: {
      /** Definitions */
      definitions: components["schemas"]["DefinitionRow"][];
      /** Example Counts */
      example_counts: {
        [key: string]: {
          [key: string]: number;
        };
      };
      /** Total Definitions */
      total_definitions: number;
    };
    /**
     * ParsedEventInfo
     * @description Event with parsed payload for API response.
     */
    ParsedEventInfo: {
      /** Id */
      id: number;
      /** Sequence Num */
      sequence_num: number;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Payload */
      payload:
        | components["schemas"]["DockerExecCallPayload"]
        | components["schemas"]["DockerExecOutputPayload"]
        | components["schemas"]["GenericToolCallPayload"]
        | components["schemas"]["GenericToolOutputPayload"]
        | components["schemas"]["UserText"]
        | components["schemas"]["AssistantText"]
        | components["schemas"]["ApiRequest"]
        | components["schemas"]["Response"]
        | components["schemas"]["ReasoningItem"];
    };
    /**
     * PromptOptimizerTypeConfig
     * @description Prompt optimizer configuration.
     *
     *     The target_metric controls validation split access:
     *     - WHOLE_REPO: TRAIN ground truth only, VALID metrics via SECURITY DEFINER function
     *                   (full-snapshot aggregates only)
     *     - TARGETED: TRAIN ground truth + VALID examples table (filenames only, no ground truth),
     *                 VALID metrics via SECURITY DEFINER function (includes per-file aggregates)
     *
     *     Both modes use SECURITY DEFINER functions for VALID metrics because:
     *     - Ground truth tables have TRAIN-only RLS
     *     - Aggregate views join ground truth tables, so inherit TRAIN-only restriction
     *     - Only SECURITY DEFINER can bypass RLS to compute VALID aggregates
     *
     *     RLS uses current_prompt_optimizer_target_metric() to gate direct data access.
     */
    PromptOptimizerTypeConfig: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "prompt_optimizer";
      target_metric: components["schemas"]["TargetMetric"];
      /**
       * Optimizer Model
       * @description Model used for the optimizer agent itself
       */
      optimizer_model: string;
      /**
       * Critic Model
       * @description Model used for critic evaluations
       */
      critic_model: string;
      /**
       * Grader Model
       * @description Model used for grader evaluations
       */
      grader_model: string;
      /**
       * Budget Limit
       * @description Dollar budget limit for optimization
       */
      budget_limit: number;
    };
    /**
     * ReasoningEffort
     * @enum {string}
     */
    ReasoningEffort: "low" | "medium" | "high";
    /**
     * ReasoningItem
     * @description Our internal reasoning item representation.
     *
     *     Note: status is not included when serializing for input - OpenAI treats it as
     *     output-only metadata even though the Param type allows it.
     */
    ReasoningItem: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "reasoning";
      /** Id */
      id?: string | null;
      /** Summary */
      summary?: components["schemas"]["ReasoningSummaryItem"][];
    } & {
      [key: string]: unknown;
    };
    /** ReasoningParams */
    ReasoningParams: {
      /** Effort */
      effort?: components["schemas"]["ReasoningEffort"] | ("low" | "medium" | "high");
      /** Summary */
      summary?: components["schemas"]["ReasoningSummary"] | ("auto" | "concise" | "detailed");
    } & {
      [key: string]: unknown;
    };
    /**
     * ReasoningSummary
     * @description Canonical values for Responses API reasoning summary selection.
     * @enum {string}
     */
    ReasoningSummary: "auto" | "concise" | "detailed";
    /**
     * ReasoningSummaryItem
     * @description Summary item within a reasoning block.
     */
    ReasoningSummaryItem: {
      /** Text */
      text: string;
      /**
       * Type
       * @default summary_text
       * @constant
       */
      type: "summary_text";
    };
    /**
     * ReportedIssueInfo
     * @description Issue reported by a critic run.
     */
    ReportedIssueInfo: {
      /** Issue Id */
      issue_id: string;
      /** Rationale */
      rationale: string;
      /** Occurrences */
      occurrences: components["schemas"]["ReportedIssueOccurrenceInfo"][];
    };
    /**
     * ReportedIssueOccurrenceInfo
     * @description Occurrence of a reported issue.
     */
    ReportedIssueOccurrenceInfo: {
      /** Occurrence Id */
      occurrence_id: string;
      /** Note */
      note: string | null;
      /** Files */
      files: components["schemas"]["FileLocationInfo"][];
    };
    /**
     * Response
     * @description One OpenAI responses.create result (non-streaming) with usage.
     *
     *     Emitted once per model call to avoid duplicating usage across assistant/tool events.
     */
    Response: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "response";
      /** Response Id */
      response_id: string;
      /** Request Id */
      request_id?: string | null;
      usage: components["schemas"]["GroundTruthUsage"];
      /** Model */
      model: string;
      /** Created At */
      created_at?: string | null;
      /** Idempotency Key */
      idempotency_key?: string | null;
    };
    /**
     * ResponsesRequest
     * @description Thin, tolerant request model for OpenAI Responses API calls we make.
     */
    ResponsesRequest: {
      /** Input */
      input:
        | (
            | components["schemas"]["AssistantMessage"]
            | components["schemas"]["UserMessage"]
            | components["schemas"]["SystemMessage"]
            | components["schemas"]["ReasoningItem"]
            | components["schemas"]["FunctionCallItem"]
            | components["schemas"]["FunctionCallOutputItem"]
          )[]
        | string;
      /** Instructions */
      instructions?: string | null;
      /** Tools */
      tools?: components["schemas"]["FunctionToolParam"][] | null;
      /** Tool Choice */
      tool_choice?: ("auto" | "required" | "none") | components["schemas"]["ToolChoiceFunction"] | null;
      /** Parallel Tool Calls */
      parallel_tool_calls?: boolean | null;
      /**
       * Stream
       * @default false
       */
      stream: boolean;
      /** Store */
      store?: boolean | null;
      reasoning?: components["schemas"]["ReasoningParams"] | null;
      /** Max Output Tokens */
      max_output_tokens?: number | null;
    } & {
      [key: string]: unknown;
    };
    /**
     * RunInfo
     * @description Run information for list view.
     */
    RunInfo: {
      /**
       * Agent Run Id
       * Format: uuid
       */
      agent_run_id: string;
      /** Definition Id */
      definition_id: string;
      /** Type Config */
      type_config:
        | components["schemas"]["CriticTypeConfig"]
        | components["schemas"]["GraderTypeConfig"]
        | components["schemas"]["SnapshotGraderTypeConfig"]
        | components["schemas"]["FreeformTypeConfig"]
        | components["schemas"]["PromptOptimizerTypeConfig"]
        | components["schemas"]["ImprovementTypeConfig"];
      /** Model */
      model: string;
      status: components["schemas"]["AgentRunStatus"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      split?: components["schemas"]["Split"] | null;
    };
    /**
     * RunsListResponse
     * @description Response for paginated runs list.
     */
    RunsListResponse: {
      /** Runs */
      runs: components["schemas"]["RunInfo"][];
      /** Total Count */
      total_count: number;
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
    };
    /**
     * SingleFileSetExample
     * @description Review files from a specific file set.
     *
     *     Files are resolved via files_hash FK join in the database.
     *     Corresponds to per-file training examples.
     */
    SingleFileSetExample: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "file_set";
      /**
       * Snapshot Slug
       * @description Snapshot to evaluate
       */
      snapshot_slug: string;
      /**
       * Files Hash
       * @description File set hash (MD5 of sorted file paths)
       */
      files_hash: string;
    };
    /**
     * SnapshotDetailResponse
     * @description Detailed snapshot info with all issues.
     */
    SnapshotDetailResponse: {
      /** Slug */
      slug: string;
      split: components["schemas"]["Split"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** True Positives */
      true_positives: components["schemas"]["TpInfo"][];
      /** False Positives */
      false_positives: components["schemas"]["FpInfo"][];
    };
    /**
     * SnapshotGraderTypeConfig
     * @description Snapshot grader daemon configuration.
     *
     *     Persistent grader that reconciles all critiques for a snapshot. Unlike per-critique
     *     GraderTypeConfig, this daemon:
     *     - Grades ALL critiques for the snapshot (not just one)
     *     - Sleeps when no drift, wakes on pg_notify
     *     - Maintains GT context for token efficiency
     *
     *     RLS uses current_grader_snapshot_slug() to extract snapshot_slug from type_config.
     */
    SnapshotGraderTypeConfig: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      agent_type: "snapshot_grader";
      /**
       * Snapshot Slug
       * @description Snapshot this daemon is responsible for
       */
      snapshot_slug: string;
    };
    /**
     * SnapshotSummary
     * @description Summary info for a snapshot in list view.
     */
    SnapshotSummary: {
      /** Slug */
      slug: string;
      split: components["schemas"]["Split"];
      /** Tp Count */
      tp_count: number;
      /** Fp Count */
      fp_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * SnapshotsListResponse
     * @description Response for listing snapshots.
     */
    SnapshotsListResponse: {
      /** Snapshots */
      snapshots: components["schemas"]["SnapshotSummary"][];
    };
    /**
     * Split
     * @enum {string}
     */
    Split: "train" | "valid" | "test";
    /** SplitScopeStats */
    SplitScopeStats: {
      recall_stats: components["schemas"]["StatsWithCI"] | null;
      /** N Examples */
      n_examples: number;
      /** Zero Count */
      zero_count: number;
      /** Status Counts */
      status_counts: {
        [key: string]: number;
      };
      /** Total Available */
      total_available: number;
    };
    /**
     * StatsWithCI
     * @description Statistics with 95% confidence interval bounds.
     *
     *     Maps to PostgreSQL composite type stats_with_ci.
     *
     *     Attributes:
     *         n: sample count
     *         mean: sample mean
     *         min: minimum value
     *         max: maximum value
     *         lcb95: lower 95% confidence bound (mean - 1.96 * stddev/sqrt(n)); NULL if n < 2
     *         ucb95: upper 95% confidence bound (mean + 1.96 * stddev/sqrt(n)); NULL if n < 2
     */
    StatsWithCI: {
      /** N */
      n: number;
      /** Mean */
      mean: number;
      /** Min */
      min: number;
      /** Max */
      max: number;
      /** Lcb95 */
      lcb95: number | null;
      /** Ucb95 */
      ucb95: number | null;
    };
    /** SystemMessage */
    SystemMessage: {
      /**
       * Role
       * @default system
       * @constant
       */
      role: "system";
      /** Content */
      content: components["schemas"]["InputTextPart"][];
    } & {
      [key: string]: unknown;
    };
    /**
     * TargetMetric
     * @description Prompt optimizer terminal metric mode.
     *
     *     Determines which validation examples are used for optimization:
     *     - WHOLE_REPO: Only full-snapshot validation examples (black-box validation)
     *     - TARGETED: Both per-file and full-snapshot validation examples (allows iteration)
     * @enum {string}
     */
    TargetMetric: "whole-repo" | "targeted";
    /**
     * TimedOut
     * @description Process was terminated after exceeding the timeout.
     */
    TimedOut: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "timed_out";
    };
    /** ToolChoiceFunction */
    ToolChoiceFunction: {
      /**
       * Type
       * @default function
       * @constant
       */
      type: "function";
      /** Name */
      name: string;
    } & {
      [key: string]: unknown;
    };
    /**
     * TpInfo
     * @description True positive issue info.
     */
    TpInfo: {
      /** Tp Id */
      tp_id: string;
      /** Rationale */
      rationale: string;
      /** Occurrences */
      occurrences: components["schemas"]["OccurrenceInfo"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * TpTarget
     * @description TP match target.
     */
    TpTarget: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "tp";
      /** Tp Id */
      tp_id: string;
      /** Occurrence Id */
      occurrence_id: string;
      /** Credit */
      credit: number;
    };
    /**
     * TruncatedStream
     * @description Truncated stream output with metadata about the original size.
     *
     *     Only used when output exceeds byte limits. Complete output uses plain str instead.
     */
    TruncatedStream: {
      /** Truncated Text */
      truncated_text: string;
      /** Total Bytes */
      total_bytes: number;
    };
    /** UserMessage */
    UserMessage: {
      /**
       * Role
       * @default user
       * @constant
       */
      role: "user";
      /** Content */
      content: components["schemas"]["InputTextPart"][];
    } & {
      [key: string]: unknown;
    };
    /** UserText */
    UserText: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "user_text";
      /** Text */
      text: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** ValidationRunRequest */
    ValidationRunRequest: {
      /** Definition Id */
      definition_id: string;
      example_kind: components["schemas"]["ExampleKind"];
      /** @default valid */
      split: components["schemas"]["Split"];
      /**
       * N Samples
       * @default 5
       */
      n_samples: number;
      /**
       * Critic Model
       * @default gpt-5.1-codex-mini
       */
      critic_model: string;
      /**
       * Grader Model
       * @default gpt-5.1-codex-mini
       */
      grader_model: string;
    };
    /** ValidationRunResponse */
    ValidationRunResponse: {
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      status: components["schemas"]["JobStatus"];
      /** N Examples Sampled */
      n_examples_sampled: number;
      /** Message */
      message: string;
    };
    /**
     * WholeSnapshotExample
     * @description Review all files in the snapshot.
     *
     *     Corresponds to whole-snapshot evaluation examples.
     */
    WholeSnapshotExample: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "whole_snapshot";
      /**
       * Snapshot Slug
       * @description Snapshot to evaluate
       */
      snapshot_slug: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_overview_api_stats_overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OverviewResponse"];
        };
      };
    };
  };
  list_definitions_api_stats_definitions_get: {
    parameters: {
      query?: {
        agent_type?: components["schemas"]["AgentType"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DefinitionsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_definition_detail_api_stats_definitions__definition_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        definition_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DefinitionDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_example_detail_api_stats_examples_get: {
    parameters: {
      query: {
        snapshot_slug: string;
        example_kind: components["schemas"]["ExampleKind"];
        files_hash?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExampleDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_active_runs_api_runs_active_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActiveRunsResponse"];
        };
      };
    };
  };
  list_jobs_api_runs_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobsResponse"];
        };
      };
    };
  };
  list_runs_api_runs_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["AgentRunStatus"] | null;
        definition_id?: string | null;
        agent_type?: components["schemas"]["AgentType"] | null;
        split?: components["schemas"]["Split"] | null;
        example_kind?: components["schemas"]["ExampleKind"] | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunsListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  trigger_validation_runs_api_runs_validation_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidationRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_api_runs_run__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentRunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_events_api_runs_run__run_id__events_get: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_snapshots_api_gt_snapshots_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotsListResponse"];
        };
      };
    };
  };
  get_snapshot_detail_api_gt_snapshots__snapshot_slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snapshot_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snapshot_tree_api_gt_snapshots__snapshot_slug__tree_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snapshot_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileTreeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snapshot_file_api_gt_snapshots__snapshot_slug__files__file_path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snapshot_slug: string;
        file_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileContentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
