apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - role.yaml
  - node-reader.yaml
  - cluster-metadata-reader.yaml
  - extended-diagnostics-reader.yaml
  - cluster-admin-ceiling.yaml
