load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "auth",
    srcs = ["auth.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//authlib",
        "@pypi//fastmcp",
        "@pypi//httpx",
    ],
)

py_test(
    name = "test_auth",
    srcs = ["test_auth.py"],
    deps = [
        ":auth",
        "@pypi//authlib",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)
