apiVersion: v1
kind: Secret
metadata:
    name: aiquota-api-bearer
    namespace: cli-proxy-api
    annotations:
        description: Bearer credential for the internal aiquota read API. All authenticated callers may read normalized quotas and raw provider usage responses.
type: Opaque
stringData:
    bearer-token: ENC[AES256_GCM,data:9Q+oL43jEeSwAG4DuFocyw21g96tutfNJouxlL86j3JPjXrp3WNPjZMW4RHrW+MD,iv:BJKdIuMui8+7BtPeBgc39KipSXO7AJfsJkSAVq1RJk0=,tag:dUeXf1iwIQq9//tl+8XOFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydU9sVWdqZUU3RmFFdTY2
            b01oL2ZXSDRmUi9JdExxcWlNWEQxa0NCU0dvCmJUay9MYUJ0RmI4dUx1UDRHNFZM
            N1ZUb0dyV0l6Und2SlI1OTIvMTM5dzgKLS0tIHJqUFBWL0ZXVWFKc1B3QlJ6UDBO
            YzJ1TVY0a3pHaFlvQjk1V3hZN2U3Rk0KvOfdF2S1ixiPASY40JbdgaAQb12pnHhn
            6MXVzp0YooBLJaOqBaeTRFyv3thKB1stGFe7QPf7vAlEVb/ttvbYKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN3p1K3lFa09Qdzl5RHZL
            TmRaS2dpSDErM0ZxdU5xM1VIUkJ6eUpUZ1hnCmFLRWR5ai9UYXdDNW1sTXFFeCtE
            U05ndHBvSk0zc3NNS0YzNk9ZanlTaWsKLS0tIGpwVzM3YnF6Uy9KbGo1dkV2dk9Y
            clFUd1JESTZWczUrTDAyd25BL3FYVTQKnq6mE0A36yO8FSyQfR/kMZqH3sYxcuuU
            FMpSElcktMTiZG+2QHm3Joh7QPquGrQxV1EHz5jLl/9rPwYukbW8+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T04:49:45Z"
    mac: ENC[AES256_GCM,data:AdhR9mZkbdLkxb2B383+vnT0tLCLGIaC2pgm47yPIfbAW+dL31C6JaIkHYIEZc/VIe1Kde2G1czCpr0FAi3lRvji8b3zYGhUfYStRvpZjoSadm/Uo9F8k7o+1SMmpZMT7KfQmD98XP99NZzN9AXyQg7wkcxuohyyRwavIBQf+i8=,iv:Lx8W44Pj5kbLEhebgHnJvl2ks6jm19lRjTGsre+k27I=,tag:iEPcUci6zB5yYH9CfJp0wA==,type:str]
    version: 3.13.3
