"""Gatelet server migrations."""

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "env",
    srcs = ["env.py"],
    imports = ["../../../.."],
    visibility = ["//x/gatelet:__subpackages__"],
    deps = [
        "//x/gatelet/server:models",
        "@pypi//alembic",
        "@pypi//sqlalchemy",
    ],
)
