version: 1
metadata:
  name: Harbor Registry OIDC
  labels:
    blueprints.goauthentik.io/type: harbor
    blueprints.goauthentik.io/instantiate: "true"
    {{- if .BlueprintChecksum }}
    blueprints.goauthentik.io/revision: {{ .BlueprintChecksum | quote }}
    {{- end }}
entries:
  - model: authentik_core.group
    id: harbor-admin-group
    state: present
    identifiers:
      name: {{ .Values.harbor.adminGroup }}
    attrs:
      name: {{ .Values.harbor.adminGroup }}
      is_superuser: false

  - model: authentik_providers_oauth2.oauth2provider
    id: harbor-provider
    state: present
    identifiers:
      name: harbor-oidc
    attrs:
      name: harbor-oidc
      client_type: confidential
      client_id: harbor
      {{- if .Values.harbor.useExternalSecret }}
      client_secret: !Env HARBOR_CLIENT_SECRET
      {{- end }}
      authorization_grant_type: authorization-code
      redirect_uris:
        - matching_mode: strict
          url: {{ .Values.harbor.externalHost }}/c/oidc/callback
        - matching_mode: strict  
          url: {{ .Values.harbor.externalHost }}/c/oidc/login
      issuer_mode: global
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      sub_mode: hashed_user_id
      include_claims_in_id_token: true

  - model: authentik_core.application
    id: harbor-app
    state: present
    identifiers:
      slug: harbor
    attrs:
      name: Harbor Registry
      slug: harbor
      provider: !KeyOf harbor-provider
      policy_engine_mode: any
      meta_launch_url: {{ .Values.harbor.externalHost | quote }}
      meta_description: Private container registry with vulnerability scanning.
      group: Infrastructure