global:
  exclude:
    - .git
    - .gitattributes
    - .github
    - .gitignore
    - '**/.gitkeep'
    - requirements*.txt
    - .pre-commit-config.yaml
    - 'CODE_OF_CONDUCT.*'
    - 'LICENSE.*'
    - 'CONTRIBUTING.*'

    - '*.jpg'
    - '*.png'
    - '*.woff2'
    - '*.sha256'
    - '**/po/*.po'
    - '**/locale/**/*.mo'
    - '*.egg-info*'
    - '*__pycache__*'
    - '*.mo'
    - '*.po'
    - '*LC_MESSAGES*'
    - '*fonts*'
    - '*.egg'
    - '*.odp'
repos:
  '/home/agentydragon/.google-drive/My Drive/mailrack/boxes':
    exclude:
      - MANIFEST.in
      - README.rst
      - documentation/boxes.1
      - documentation/boxes.xml
      - documentation/boxesserver.1
      - documentation/boxesserver.xml
      - documentation/src/Makefile
      - documentation/src/boxes2rst.py
      - documentation/src/burn.svg
      - documentation/src/burn2.svg
      - documentation/src/conf.py
      - documentation/src/index.html
      - documentation/src/overcuts.svg
      - documentation/src/static
      - examples/README.txt
      - inkex/inkscape.txt
      - po/boxes.py.pot
      - po/readme.txt
      - po/zanata.xml
      - pyproject.toml
      - static/boxes-logo.svg
      - static/favicon.ico
      - static/normalize.css
      - static/self.css
      - static/self.js
      - tests/test_svg.py
      - scripts/boxes2pot
      - scripts/Dockerfile
      - scripts/boxes
      - scripts/boxes2inkscape
      - scripts/boxes_example.ipynb
      - scripts/boxes_proxy.py
      - scripts/boxesserver
      - setup.py
      - build
      - 'setup.py'
      - 'inkex/boxes.py.*.inx'
      - examples/*.svg # TODO: maybe include one or two?
      - scripts/gen_thumbnails.sh
      - documentation/src/make.bat
      - 'boxes/generators/frontpanel_test.json'
      - 'documentation/src/install/log-wsl-win11.txt'
    include:
      - boxes/*.py
      - boxes/generators/*.py
      - documentation/src/*.rst

strip_snippets:
  - type: "literal_top"
    lines: |
      # Copyright (C) 2020 Guillaume Collic
      #
      #   This program is free software: you can redistribute it and/or modify
      #   it under the terms of the GNU General Public License as published by
      #   the Free Software Foundation, either version 3 of the License, or
      #   (at your option) any later version.
      #
      #   This program is distributed in the hope that it will be useful,
      #   but WITHOUT ANY WARRANTY; without even the implied warranty of
      #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      #   GNU General Public License for more details.
      #
      #   You should have received a copy of the GNU General Public License
      #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
  - type: "literal"
    lines: |
      # Copyright (C) 2013-2014 Florian Festi
      #
      #   This program is free software: you can redistribute it and/or modify
      #   it under the terms of the GNU General Public License as published by
      #   the Free Software Foundation, either version 3 of the License, or
      #   (at your option) any later version.
      #
      #   This program is distributed in the hope that it will be useful,
      #   but WITHOUT ANY WARRANTY; without even the implied warranty of
      #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      #   GNU General Public License for more details.
      #
      #   You should have received a copy of the GNU General Public License
      #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #- type: "regex"
  #  pattern: "^# This is some other comment.*$"
  #  flags: "MULTILINE"

