---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    password: AgBQiPNlOAsnaQ4zKqRoCixQBDkZ6eAXkuF3vdafrm6CrE+OXaEGzXzf9EpMATBiqQgztp3UmBxw9eC5RDyqMsMlbHyO4T5BFe6ydzVMT1ofRTyTVpj6RpaWbwMESfc4sCOvXm4vpHOKmBRtZILn0RF1HFpHxsM47aH1BRhf11UjH3Ohd2Sdv7ipYNxkq4IkpVTiKUQsc5SAR7s5/0uzOWPaeIs5wuOpUmJSvbr7o2b2FIvdJGH3caItZeCi1DkXzNuQHVOW3VDcKtzWa//3YunqEGox8legPJ9s9u7lVgJ+PqV0n2V0ANIMxMV/TLonQWm9akAvaqglrASfUB1t7Sg4go9jDEO4BMbX9vJKfnJO1OaaXB9Pslhll/sYdFMbulcRel9ZEAzElvtOMxWAYEr+qbTyjPo3TXbrBL/ejqkXfnG/Rq2QKpM5oB7dUlKyD3ECXh0C9gXcNG7wVdAu91mroGz0A0ut0D06QPAQftcme7CZQl5zVLON/6hOI86FxhF/KUqCKMU2WPQXp2UWzBGlhB/3tAsdt2/zPjcz8Ntr2r/woOJ+D+M4Y6GnYyjHmGQj7aBMjBAY09zLVHIgq5qcEhb6gNvxvoXoQuqSxQwgMzL4rcQ1DXLFbgXNkZ8WcF+WGD7m7NQEBDGpwaf79r+/VTyfZEeIiGR8gxNs0p5jQTIX5ZdspKZnn78xYx0snsbJxYz34g7kq7DvVs6g/taEAwKjEcST91HIIj7kU99lAu7irmmtxQx10MI8
    username: AgBcVUk3A6FHDY91/xohrVln4Z8YAkfadbWejd4UQ+J5s2BESuwLzMBV89CiSfPZojhy4JLYCI4t1SExI3bbQQBjR+j+G4QLBBv/kV3jYbZiU8XOJ4RzCzwu9uUvnsSOYhXXAyTkUSCUTmSQLewLK3ie0cywT8o+3xpA3vHr2qKbDoUCRF9j+SRxQ0YuCK0+44jxbg32cXqg712eKzYImioIfnGOiVd7CBPlUdTCdD5UQOnA/zFjGeJ5M0BfRo4sREMp6cwpKMUx/8udXSjGI5yjrKhGv7pjPnXSQyr6TuktDuT9tIMJg5lUYRuE9MvVzvYs8MfMtnrXIz1h0PxwdJkcIbo1huj8uj6hHGk6N3ryV4PE+fWwryPuaYgx3qTccDieWKDIUQyvzLds2K2lJQD5yxi6XhIcY/cYopCTd445HIV/cQMf02cFFcFGUabU8SVd8kpNTF8gBzq0OAA0di7bWg6i1PXfwsBLHJMAluHWBVt0H2WzltLu9iByxp+j6/W3M58vtzzwPJAG6sDzzicDn1Q+0kVMV5er13mtPeJNJ8MfxkTZ0REwA1PDjWaDCsnI9pY3t/Shh5of0t2oXfoEehf2eyObtptM5LSZsAGOK6LwQagBhunfzZS//iNibzd1nKFRuyAsquTdjDDvUbO5yjaWegi9BWie4e5m8+vwtA2nH0J4DWdNVxC6U9ZUHqhwCZ+TCw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: observability
      name: grafana-admin
      namespace: observability
    type: Opaque
