use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result};
use rayon::prelude::*;
use swc_common::GLOBALS;

use analysis::ChunkId;
use artifact::{
    ArtifactChunkRecord, ArtifactCounts, CANONICAL_CHUNK_ENTRY_FILE, ChunkAnalysisReport,
    ChunkArtifact, ChunkBundle, ChunkMetadata, FileMetadata, FileRole, JsChunk, JsFile, JsFileBody,
    LoadedJsChunks,
};
use js_ast::{ParsedJsModule, parse_js_module_consuming};
use program_analysis::{analyze_program_shallow, build_chunk_manifest_from_analysis};
use spec::TransformSpec;

const CANONICALIZE_HEADER_LINES: &[&str] = &[
    "// Generated by //devinfra/js/debundle:prepare_chunks.",
    "// Executable chunk entry.",
];

pub struct PrepareJsChunksResult {
    pub artifact: ChunkBundle,
    pub counts: ArtifactCounts,
    pub chunk_records: Vec<ArtifactChunkRecord>,
}

pub fn prepare_js_chunks(
    spec: &TransformSpec,
    loaded: LoadedJsChunks,
) -> Result<PrepareJsChunksResult> {
    let LoadedJsChunks {
        chunks,
        chunk_table,
    } = loaded;

    let jobs = chunks
        .into_iter()
        .enumerate()
        .map(|(index, mut chunk)| {
            let chunk_id = ChunkId(index);
            let chunk_name = chunk_table.name(chunk_id).to_string();
            let entry_file = chunk.entry_file.clone();
            let entry_artifact_file = chunk.remove_file(&entry_file).with_context(|| {
                format!(
                    "prepare_js_chunks requires entry file for chunk: {chunk_name}/{entry_file}"
                )
            })?;
            let entry_source = entry_artifact_file.into_source().with_context(|| {
                format!("prepare_js_chunks requires content for chunk: {chunk_name}/{entry_file}")
            })?;
            Ok(PrepareChunkJob {
                chunk_id,
                chunk_name,
                entry_file,
                source_path: chunk.metadata.source_path.clone(),
                entry_source,
            })
        })
        .collect::<Result<Vec<_>>>()?;

    // First pass: parse all chunks and collect shallow manifest/rewrite facts.
    // Source text moves into the SourceMap; no extra copy.
    // Rayon workers don't inherit the caller's `swc_common::GLOBALS` scope
    // (it's `scoped_tls`, per-thread), so we re-set it inside each worker
    // closure to give `Mark::new()` an arena to mint into.
    let parsed_chunks = GLOBALS.with(|globals| {
        jobs.into_par_iter()
            .map(|job| {
                GLOBALS.set(globals, || {
                    let chunk_id = job.chunk_id;
                    let chunk_name = job.chunk_name.clone();
                    let parsed = prepare_chunk(job)?;
                    Ok((chunk_id, chunk_name, parsed))
                })
            })
            .collect::<Result<Vec<_>>>()
    })?;

    // Build set of vendor target chunk ids
    let vendor_target_chunk_ids: BTreeSet<String> = spec
        .vendor
        .keys()
        .filter_map(|chunk_path| {
            // Vendor marks use .js paths, convert to chunk ids
            chunk_path.strip_suffix(".js").map(|s| s.to_string())
        })
        .collect();

    // Second pass: replace ASTs with original source for chunks that don't need them.
    //
    // A chunk needs to keep its AST if any downstream stage will read it. The
    // predicates below cover spec-driven stages (logical modules, residual
    // modules, renames, vendor); on top of those, the pass-through emission
    // rewriter canonicalizes specifiers in every emitted non-module file, so
    // we must also keep the AST whenever it would rewrite anything in this
    // chunk's entry. The `has_rewritable_specifier` fact mirrors the
    // canonicalizer's relative-path gate (`.` or `/` prefix) exactly and is
    // computed during the first-pass `analyze_program_shallow` walk, so this
    // second pass does not need to re-visit the AST.
    let prepared_chunks = parsed_chunks
        .into_iter()
        .map(|(chunk_id, chunk_name, mut prepared)| {
            let needs_ast = needs_ast_for_chunk(&chunk_name, spec, &vendor_target_chunk_ids)
                || prepared.has_rewritable_specifier;

            if !needs_ast
                && let Some(pos) = prepared
                    .files
                    .iter()
                    .position(|f| f.path == CANONICAL_CHUNK_ENTRY_FILE)
            {
                let file = prepared.files.remove(pos);
                if let Some(rendered) = file.into_rendered_source() {
                    prepared.files.insert(pos, rendered);
                }
            }

            Ok((chunk_id, chunk_name, prepared))
        })
        .collect::<Result<Vec<_>>>()?;

    let artifact = ChunkBundle {
        chunks: prepared_chunks
            .into_iter()
            .map(|(chunk_id, _, prepared)| ChunkArtifact {
                chunk_id,
                js: JsChunk {
                    entry_file: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
                    files: prepared.files,
                    metadata: prepared.metadata,
                },
                analysis: prepared.analysis,
            })
            .collect(),
        chunk_table,
    };

    let manifests: Vec<ChunkAnalysisReport> = artifact
        .chunks
        .iter()
        .map(|chunk| chunk.analysis.clone())
        .collect();
    let (counts, chunk_records) = build_prepare_output(&manifests);
    Ok(PrepareJsChunksResult {
        artifact,
        counts,
        chunk_records,
    })
}

struct PrepareChunkJob {
    chunk_id: ChunkId,
    chunk_name: String,
    entry_file: String,
    source_path: String,
    entry_source: String,
}

struct PreparedChunk {
    files: Vec<JsFile>,
    metadata: ChunkMetadata,
    analysis: ChunkAnalysisReport,
    /// Captured from the fused `analyze_program_shallow` walk so the
    /// second pass can decide AST retention without re-visiting the
    /// AST.
    has_rewritable_specifier: bool,
}

fn prepare_chunk(job: PrepareChunkJob) -> Result<PreparedChunk> {
    let parsed = parse_js_module_consuming(
        &format!("{}/{}", job.chunk_name, job.entry_file),
        job.entry_source,
    )?;
    let analysis = analyze_program_shallow(&parsed);
    Ok(PreparedChunk {
        files: vec![canonical_parsed_file(
            &job.chunk_name,
            &job.source_path,
            parsed,
        )],
        analysis: build_chunk_manifest_from_analysis(
            &job.chunk_name,
            CANONICAL_CHUNK_ENTRY_FILE,
            &job.source_path,
            &analysis,
        ),
        has_rewritable_specifier: analysis.has_rewritable_specifier,
        metadata: ChunkMetadata {
            source_path: job.source_path,
        },
    })
}

fn canonical_parsed_file(chunk_id: &str, source_path: &str, parsed: ParsedJsModule) -> JsFile {
    JsFile {
        path: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
        body: JsFileBody::Ast(parsed),
        header_lines: CANONICALIZE_HEADER_LINES
            .iter()
            .map(|line| (*line).to_string())
            .collect(),
        binding_comments: BTreeMap::new(),
        leading_item_comments: BTreeMap::new(),
        metadata: FileMetadata {
            chunk_id: chunk_id.to_string(),
            chunk_file: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
            role: FileRole::Entry,
            source_path: source_path.to_string(),
        },
    }
}

fn build_prepare_output(
    manifests: &[ChunkAnalysisReport],
) -> (ArtifactCounts, Vec<ArtifactChunkRecord>) {
    let counts = ArtifactCounts {
        kept_top_level_declaration_owners: manifests
            .iter()
            .map(|manifest| manifest.counts.kept_top_level_declaration_owners)
            .sum(),
        top_level_side_effects: manifests
            .iter()
            .map(|manifest| manifest.counts.top_level_side_effects)
            .sum(),
        export_aliases: manifests
            .iter()
            .map(|manifest| manifest.counts.export_aliases)
            .sum(),
        unresolved_exports: manifests
            .iter()
            .map(|manifest| manifest.counts.unresolved_exports)
            .sum(),
    };
    let chunk_records = manifests
        .iter()
        .map(|manifest| ArtifactChunkRecord {
            chunk_id: manifest.chunk_id.clone(),
            source_path: manifest.source_path.clone(),
        })
        .collect();
    (counts, chunk_records)
}

/// Spec-driven AST consumers. Neighboring a vendor chunk is not itself work:
/// callers with relative directives retain their AST through the shallow rewrite
/// fact, while a vendor's dependency can pass through as source if it has no work.
fn needs_ast_for_chunk(
    chunk_id: &str,
    spec: &TransformSpec,
    vendor_target_chunk_ids: &BTreeSet<String>,
) -> bool {
    spec.logical_modules.contains_key(chunk_id)
        // Both residual policies materialize modules from the chunk body.
        || spec.unassigned_mode.contains_key(chunk_id)
        || spec.chunk_renames.contains_key(chunk_id)
        || vendor_target_chunk_ids.contains(chunk_id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    // Retention is an internal storage invariant, not observable in emitted JS.
    // Load real source files through the normal loader and fused preparation.
    #[test]
    fn vendor_neighbors_retain_ast_only_for_their_own_work() {
        js_ast::with_swc_globals(|| {
            let root = tempfile::TempDir::new().unwrap();
            for (name, source) in [
                (
                    "vendor.js",
                    "import { helper } from './helper.js'; export const value = helper();",
                ),
                ("helper.js", "export const helper = () => 7;"),
                (
                    "caller.js",
                    "import { value } from './vendor.js'; console.log(value);",
                ),
                ("forward.js", "export { value } from './vendor.js';"),
                (
                    "dynamic.js",
                    "export const load = () => import('./vendor.js');",
                ),
            ] {
                fs::write(root.path().join(name), source).unwrap();
            }
            let list = root.path().join("js-files.txt");
            fs::write(
                &list,
                "vendor.js\nhelper.js\ncaller.js\nforward.js\ndynamic.js\n",
            )
            .unwrap();
            let spec: TransformSpec = serde_yaml::from_str(
                "inputs: {input_root: '.', js_list_path: js-files.txt}\nvendor:\n  vendor.js: {identity: fixture, level: suppress}\n",
            ).unwrap();
            let loaded = artifact::load_js_chunks(root.path(), &list).unwrap();
            let prepared = prepare_js_chunks(&spec, loaded).unwrap();
            for chunk in &prepared.artifact.chunks {
                let name = prepared.artifact.chunk_table.name(chunk.chunk_id);
                let has_ast = chunk
                    .js
                    .get_file(CANONICAL_CHUNK_ENTRY_FILE)
                    .unwrap()
                    .ast()
                    .is_some();
                assert_eq!(has_ast, name != "helper", "{name}");
            }
        });
    }
}
