use std::collections::BTreeMap;
use std::time::Instant;

use anyhow::{Context, Result, bail};
use rayon::prelude::*;
use serde::Serialize;

use artifact::{
    ArtifactChunkRecord, ArtifactCounts, ArtifactManifest, CANONICAL_CHUNK_ENTRY_FILE,
    ChunkArtifact, ChunkManifest, ChunkMetadata, FileMetadata, FileRole, JsChunk, JsFile,
    JsFileBody, JsPipelineArtifact, LoadedJsChunks, ParsedJsFileRecord,
};
use js_ast::{ParsedJsModule, parse_js_module};
use program_analysis::{
    ProgramAnalysis, analyze_program_shallow, build_chunk_manifest_from_analysis,
};

const CANONICALIZE_HEADER_LINES: &[&str] = &[
    "// Generated by //devinfra/js/debundle:prepare_chunks.",
    "// Executable chunk entry.",
];

pub struct PrepareJsChunksResult {
    pub artifact: JsPipelineArtifact,
    pub manifest: ArtifactManifest,
    pub parsed_js_files: ParsedJsFilesManifest,
}

#[derive(Debug, Clone, Serialize)]
pub struct ParsedJsFilesManifest {
    pub counts: ParsedJsFilesCounts,
    pub parsed_files: Vec<ParsedJsFileRecord>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ParsedJsFilesCounts {
    pub parsed: usize,
    pub files: usize,
}

pub fn prepare_js_chunks(mut loaded: LoadedJsChunks) -> Result<PrepareJsChunksResult> {
    let chunk_ids = loaded.list_chunk_ids();
    let jobs = chunk_ids
        .iter()
        .map(|chunk_id| {
            let chunk = loaded
                .chunks
                .remove(chunk_id)
                .with_context(|| format!("prepare_js_chunks missing ordered chunk: {chunk_id}"))?;
            Ok(PrepareChunkJob {
                chunk_id: chunk_id.clone(),
                chunk,
            })
        })
        .collect::<Result<Vec<_>>>()?;
    let file_count = jobs.iter().map(|job| job.chunk.files.len()).sum();

    let prepared_chunks = jobs
        .into_par_iter()
        .map(prepare_chunk)
        .collect::<Result<Vec<_>>>()?;

    let (mut next, manifests, parsed_files) = chunk_ids.into_iter().zip(prepared_chunks).try_fold(
        (
            JsPipelineArtifact::default(),
            Vec::<ChunkManifest>::new(),
            Vec::<ParsedJsFileRecord>::new(),
        ),
        |(mut next, mut manifests, mut parsed_files), (chunk_id, prepared)| {
            if prepared.chunk_id != chunk_id {
                bail!(
                    "prepare_js_chunks reordered prepared chunks: expected {chunk_id}, got {}",
                    prepared.chunk_id
                );
            }
            let manifest = prepared.manifest.clone();
            next.chunks.push(ChunkArtifact {
                chunk_id,
                js: JsChunk {
                    entry_file: prepared.entry_file,
                    files: prepared.files,
                    metadata: prepared.metadata,
                },
                manifest: manifest.clone(),
            });
            parsed_files.extend(prepared.parsed_files);
            manifests.push(manifest);
            Ok::<_, anyhow::Error>((next, manifests, parsed_files))
        },
    )?;

    let manifest = build_artifact_manifest(&manifests);
    next.root_manifest = manifest.clone();
    Ok(PrepareJsChunksResult {
        artifact: next,
        manifest,
        parsed_js_files: ParsedJsFilesManifest {
            counts: ParsedJsFilesCounts {
                parsed: parsed_files.len(),
                files: file_count,
            },
            parsed_files,
        },
    })
}

struct PrepareChunkJob {
    chunk_id: String,
    chunk: JsChunk,
}

struct PreparedChunk {
    chunk_id: String,
    entry_file: String,
    files: BTreeMap<String, JsFile>,
    metadata: ChunkMetadata,
    manifest: ChunkManifest,
    parsed_files: Vec<ParsedJsFileRecord>,
}

fn prepare_chunk(job: PrepareChunkJob) -> Result<PreparedChunk> {
    let PrepareChunkJob {
        chunk_id,
        mut chunk,
    } = job;
    let source_path = chunk
        .metadata
        .source_path
        .clone()
        .unwrap_or_else(|| format!("{chunk_id}.js"));
    let entry_file = chunk.entry_file.clone();
    let entry_artifact_file = chunk.files.remove(&entry_file).with_context(|| {
        format!("prepare_js_chunks requires entry file for chunk: {chunk_id}/{entry_file}")
    })?;
    let (manifest, prepared_file, prepared_entry_file, parsed_files) =
        prepare_parsed_entry(&chunk_id, &entry_file, &source_path, entry_artifact_file)?;
    let mut files = BTreeMap::new();
    files.insert(prepared_entry_file.clone(), prepared_file);
    Ok(PreparedChunk {
        chunk_id,
        entry_file: prepared_entry_file,
        files,
        metadata: ChunkMetadata {
            source_path: Some(source_path),
            module_extraction_state: None,
        },
        manifest,
        parsed_files,
    })
}

fn prepare_parsed_entry(
    chunk_id: &str,
    entry_file: &str,
    source_path: &str,
    entry_artifact_file: JsFile,
) -> Result<(ChunkManifest, JsFile, String, Vec<ParsedJsFileRecord>)> {
    let content = entry_artifact_file.into_source().with_context(|| {
        format!("prepare_js_chunks requires content for parsed chunk: {chunk_id}/{entry_file}")
    })?;
    let source_bytes = content.len();
    let source_name = format!("{chunk_id}/{entry_file}");

    let parse_started = Instant::now();
    let parsed = parse_js_module(&source_name, &content)?;
    let parse_duration = parse_started.elapsed();

    let analysis_started = Instant::now();
    let analysis = analyze_program_shallow(&parsed);
    let analysis_duration = analysis_started.elapsed();

    let manifest = build_parsed_chunk_manifest(chunk_id, source_path, &analysis);
    let file = canonical_parsed_file(chunk_id, source_path, parsed);
    Ok((
        manifest,
        file,
        CANONICAL_CHUNK_ENTRY_FILE.to_string(),
        vec![ParsedJsFileRecord {
            chunk_id: chunk_id.to_string(),
            file: entry_file.to_string(),
            source_bytes,
            parse_duration,
            analysis_duration,
        }],
    ))
}

fn build_parsed_chunk_manifest(
    chunk_id: &str,
    source_path: &str,
    analysis: &ProgramAnalysis,
) -> ChunkManifest {
    build_chunk_manifest_from_analysis(chunk_id, CANONICAL_CHUNK_ENTRY_FILE, source_path, analysis)
}

fn canonical_parsed_file(chunk_id: &str, source_path: &str, parsed: ParsedJsModule) -> JsFile {
    JsFile {
        path: CANONICAL_CHUNK_ENTRY_FILE.to_string(),
        body: JsFileBody::Ast(parsed),
        header_lines: CANONICALIZE_HEADER_LINES
            .iter()
            .map(|line| (*line).to_string())
            .collect(),
        metadata: FileMetadata {
            chunk_id: Some(chunk_id.to_string()),
            chunk_file: Some(CANONICAL_CHUNK_ENTRY_FILE.to_string()),
            role: Some(FileRole::Entry),
            source_path: Some(source_path.to_string()),
            ..Default::default()
        },
    }
}

fn build_artifact_manifest(manifests: &[ChunkManifest]) -> ArtifactManifest {
    ArtifactManifest {
        counts: ArtifactCounts {
            chunks: manifests.len(),
            kept_top_level_declaration_owners: manifests
                .iter()
                .map(|manifest| manifest.counts.kept_top_level_declaration_owners)
                .sum(),
            top_level_side_effects: manifests
                .iter()
                .map(|manifest| manifest.counts.top_level_side_effects)
                .sum(),
            export_aliases: manifests
                .iter()
                .map(|manifest| manifest.counts.export_aliases)
                .sum(),
            unresolved_exports: manifests
                .iter()
                .map(|manifest| manifest.counts.unresolved_exports)
                .sum(),
            selected_module_lowerings: None,
        },
        chunks: manifests
            .iter()
            .map(|manifest| ArtifactChunkRecord {
                chunk_id: manifest.chunk_id.clone(),
                source_path: manifest.source_path.clone(),
            })
            .collect(),
        logical_modules: None,
        selected_module_lowerings: None,
        scrambled_identifier_frequencies: None,
        output_metrics: None,
    }
}
