---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-client-credentials
  namespace: airlock
spec:
  encryptedData:
    client_id: AgBRfOeVgXIoFnIeyt6SBETgGQRmTDulMQUmuKDFVIuY1Z1NZhk4jLEXwl+T5Uevxq8SfxCxUIMUs9YAI+u7RM8Kf/0k5xg8mho0RuzNlJkUAIQhODbuC2XI1CTk2Dz3DSd5ZQmxttq/pVnO5iS9l3sHR3kYwRNvY3vLm0WC8/ifV81o8xYsDPLQm1ahJqK/ORwJl3/g5cKLZVaQ5EwXUYuy9RTvBipf88hp1BnZ0Kerf0PAypZhB1/xkA7XNJ8SjdjOYcLLT0XEoyNUSJVGkGhN65icXzpamm/1aN37/UldbmpZM6updTSRznc2SjQCTUhB29ykXlWr6/zogG1/AQCPRHWRxB7z1JHl5ejTxlG3gYLrFYuHqc2gw8Jz6BXoptuUl/PGxy1+sXIVTYNLtZTWBzz2sdvMwNnI5LnFrshI1hD2JWboj8BBjXi/MGStIw7USGZXODgM8jhhKLC3fXl6Y2MCh3o6ozBzLSI8uZs0C0jfbAHggNrAVJZfAQeYqfmjei3PHdaJQ8MqYKEpbox8z89J/dU3CUDXz8btzyhhBLhsPQHWnV1OlFBrvxwORWEZ7BzLS0eSvMZNkvG4rjtK4/qxoxaik4hQ3tmOj6hWkYP5m4bgF0kBBhliMhbW8VsH9xSBiBpycWq0ngMIitvi5L/4JCTM5aU/AeCdomqCdXSg0B7XE3cNhik4yD7mQQ7NZLevQoTR0a6cVlRb4PfeJmWGD4O+q8afkAPwo/Gpi8ZREa1/M6ggDBDJZcBgIIpEBwlBNsabj51pUvdCQvSz8pA/G0DVcKI=
    client_secret: AgCIAns891bCENu53+YjWCiyd29AwoRwgJztiCnQYqI5E0rRAgXgaQre/a5PlJCmim/XEByk9id/QwYlEE6MgLEV1KASu8KLZCAvKzj8j04K6AVqWkiiICcWq6YbCIdWE5f63mZC/9lESdYu5zK88NWYnXsGlcyAAH7iXi26yV0yYu7od0UAB4KjUk7I4NPiQ5/bxpipL0rpTsQrnx8Ow+Y6v4z3EATmn5PIibC4Ju7rc1vi1cBReXDmxJJzKjxNRCe3s9sWVhfe8Jb98ZMGBXJkqv+SU1+UEQ7PFpVxxxBiuHbeCcGAVoGwPk2DBxwlgl7Wzb60PrrOb2FSh6uY5EiK1ZU/QQIRptfhHrpMtRCzYMzzKILWSV/4S1vnKnwWFtayBaJnBDOeQXODyXflA88WsYI1yU3pWLEPKzmXx3JbCcCBcRwyWX41IWT6QONc+K1j3/JS+Cmg+iY3cZGVFWkeqekAjzgGsem9bhrBHWlIIW++NnUuyL5Is84FQl0JJmcwLuPF8re1T8ZSAUeAYioSs/AGIMi/NmT1fNPwUOpi3V4VegBoXj0fWSSGC026+42i9My5Tgj2JylxRG9gtwGA30NCEoe1y4O04Nu0DTj0l1VyxxtgH6/HbGFTLMMbXTsiUZzDMBPw8vdlZR5EpmZ+8C96ePmm6u55Xh0la3RpPvtFD5n/tfzTomd33TyAFaa0gOpBkkgBv7wvZSTwu8EjD0oVVjeaIpKAu9BPwtj5tWJ1fA==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: google-workspace-mcp
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: google-workspace-mcp
      name: google-client-credentials
      namespace: airlock
