load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//tools/lint:linters.bzl", "ruff_test")

exports_files([
    "devenv.nix",
])

py_library(
    name = "wt",
    srcs = glob(
        ["**/*.py"],
        exclude = [
            ".*/**",
            "tests/**",
        ],
    ),
    data = glob(["shell/*.sh"]),
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//click",
        "@pypi//colorama",
        "@pypi//pluggy",
        "@pypi//psutil",
        "@pypi//punq",
        "@pypi//pydantic",
        "@pypi//pygit2",
        "@pypi//pygithub",
        "@pypi//pyyaml",
        "@pypi//tabulate",
        "@pypi//typer",
        "@pypi//watchdog",
    ],
)

py_binary(
    name = "wt-cli",
    srcs = ["cli.py"],
    main = "cli.py",
    deps = [":wt"],
)

py_binary(
    name = "wt-install",
    srcs = ["shell/install.py"],
    main = "shell/install.py",
    deps = [":wt"],
)

py_test(
    name = "test_wt",
    srcs = glob(["tests/**/*.py"]),
    imports = ["."],
    main = "tests/conftest.py",
    deps = [
        ":wt",
        "@pypi//pyhamcrest",
        "@pypi//pytest",
        "@pypi//pytest_asyncio",
        "@pypi//pytest_mock",
        "@pypi//tenacity",
    ],
)

ruff_test(
    name = "ruff",
    srcs = [":wt"],
)
