filegroup(
    name = "cluster_yaml_files",
    srcs = glob(
        ["**/*.yaml"],
        exclude = ["flux-system/**"],
    ),
    visibility = ["//cluster:__subpackages__"],
)

filegroup(
    name = "cluster_all_files",
    srcs = glob(
        ["**"],
        exclude = ["flux-system/**"],
    ),
    visibility = ["//cluster:__subpackages__"],
)
