apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaweedfs
stringData:
    seaweedfs_s3_config.json: ENC[AES256_GCM,data:OyOZP5mlCpV7BiKeN1iIhDIPW5marxY4uZrcoYjn5WObqWR3IPmVGGNmKbviTyyyMSYNiIfo/5FZyyRfmxouMci6Sd8YOOQ9WybtTy08Jq66zRBSj+X7y+6vX/Zs+ulQtJMFTZU7dPvv42lxXAB9C9YnGEPu3KYYPOR0HMGzvQN63AhRc1qpaignaAnHXiB8SXhD/vzTgvgyxanhmF7oIZ7R76yvHcSTzRbQjAMfOano7vH1THYH+GiErA/5pgFmFTE/KhKY+uIE+0juBFG55W250PVl+f4Zr5LkVPoNSR8QF+V9wulX2FfzaNiQimAFmLphqN/ft3Fpf1y3OzrRnHCdln3yv5l5BfmqGRW5Yl+2N2UurGu8unLv16ny8O85mHoZ7JnesBRcAmRlcrdb2z35Mwz91gNaPIH42OBzOwq1GnxHg+xR2WGrfheZ/bCgRAXWhJifFk/lcoqH4cqcMwc0rZHaJGkK,iv:zLLfStoMIVxQobi1KKNt/hwLEfaTqx68FUqtOFq4InU=,tag:BKbhrg6hIJkQOlVlNBm/mg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNXp4NTZUMlY3dU52RXhS
            TlMyM1ZleEF2MzBsZWNjbXY1OXNucm9mTFFnCk5jYzVJWkdOWkhLbm1waTUyZHZ2
            alFRdHZOTDF0UjNVNmtMck5QWGJvbjQKLS0tIFdVWWJkcWZCREhoRVQ5cDRWZGdT
            ejQyTysyY1hQUmJSVk5saTF6TnpCVzAK7ghQi4KxpA8HZTmbeQGRn6cR+5m68rEK
            zAV7YwD36fQgXfdBv6O+zYd0ndstWuy4+WYkkulAS5J1uV1O8swGmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN2pRWWh4WjVGWUQxR0hj
            UERLa2ZSOFg1RENBeFgrYlVtMyttME5wZ0RvCmhuVEVpTVVxK2g3VWpuWE5SR2Ja
            cVU2OHFQQ3FNVnJxUHFFVGEwZG43N0kKLS0tIEVrSmVuNi9qaXZENy9HckpISTVz
            T29nNGFkYWlUMjZHYThiZ0NHTCtwbWMKg6Eeo8sZFv8egS9uOf4MQtVf7RX96en8
            FiwwvJXc6HUse+L0D6hH1tj5xd2uyQX9xK82IW3iRUGZ+E6ek6bLqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T08:18:37Z"
    mac: ENC[AES256_GCM,data:MHSnNlJJVABEoOu2T5+Lm2Ganl7QgCqv9s9ZfCrzPeCzC8qliTOuxbrYxX1ecJvSmzggpR7nrpVyKQn9Cs7SaVtrMhTP0hDifqj3+vtEbGrXS4+ug36USvye4a+lRKPCiDxMz9hlXFeMGDbUPkWx7nDSI2E7qxJYLzdGMMsU7f4=,iv:PJ+N8lqqhHBtxu7t3TYdBOnO5L/BzOJj4srj0q8uMrA=,tag:OBwVkqB/kD+WGgfwudVywA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
