"""CLI utilities package."""

load("@rules_python//python:defs.bzl", "py_library")

exports_files(["pyproject.toml"])
py_library(
    name = "cli_util",
    srcs = glob(["src/cli_util/**/*.py"]),
    imports = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//structlog",
        "@pypi//typer",
    ],
)
