{{- if and .Values.backup.enabled .Values.backup.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "props.fullname" . }}-backup
  labels:
    {{- include "props.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size }}
  {{- if .Values.backup.persistence.storageClassName }}
  storageClassName: {{ .Values.backup.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
