load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "kubespand_lib",
    srcs = [
        "controller_config.go",
        "controller_discovery.go",
        "controller_identity.go",
        "controller_k8s_node.go",
        "controller_manager.go",
        "main.go",
    ],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand",
    visibility = ["//visibility:private"],
    deps = [
        "//cluster/kubespand/agentconfig",
        "//cluster/kubespand/discovery",
        "//cluster/kubespand/endpoint",
        "//cluster/kubespand/identity",
        "//cluster/kubespand/k8snet",
        "//cluster/kubespand/nftables",
        "//cluster/kubespand/peerspec",
        "//cluster/kubespand/peerstate",
        "//cluster/kubespand/routing",
        "//cluster/kubespand/wireguard",
        "@com_github_cosi_project_runtime//pkg/controller",
        "@com_github_cosi_project_runtime//pkg/controller/runtime",
        "@com_github_cosi_project_runtime//pkg/resource",
        "@com_github_cosi_project_runtime//pkg/safe",
        "@com_github_cosi_project_runtime//pkg/state",
        "@com_github_cosi_project_runtime//pkg/state/impl/inmem",
        "@com_github_cosi_project_runtime//pkg/state/impl/namespaced",
        "@com_github_siderolabs_discovery_api//api/v1alpha1/client/pb",
        "@com_github_siderolabs_discovery_client//pkg/client",
        "@com_github_siderolabs_go_pointer//:go-pointer",
        "@com_github_siderolabs_talos_pkg_machinery//constants",
        "@com_github_siderolabs_talos_pkg_machinery//nethelpers",
        "@com_github_siderolabs_talos_pkg_machinery//resources/cluster",
        "@com_github_siderolabs_talos_pkg_machinery//resources/config",
        "@com_github_siderolabs_talos_pkg_machinery//resources/kubespan",
        "@com_github_siderolabs_talos_pkg_machinery//resources/network",
        "@com_zx2c4_golang_wireguard_wgctrl//wgtypes",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/fields",
        "@io_k8s_client_go//informers",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//rest",
        "@io_k8s_client_go//tools/cache",
        "@io_k8s_client_go//tools/clientcmd",
        "@org_go4_netipx//:netipx",
        "@org_uber_go_zap//:zap",
    ],
)

go_binary(
    name = "kubespand",
    embed = [":kubespand_lib"],
    goarch = "amd64",
    goos = "linux",
    static = "on",
    visibility = ["//visibility:public"],
)
