cli_effective_ansible_user: >-
  {{
    ansible_user_id
      | default(ansible_user, true)
      | default(
          ansible_env.USER
          if (ansible_env is defined and ("USER" in ansible_env))
          else None,
          true)
      | default("root", true)
  }}
cli_effective_user: "{{ cli_user | default(my_user | default(cli_effective_ansible_user)) }}"
cli_effective_home: >-
  {{
    ansible_user_dir
    if (ansible_user_dir is defined and cli_effective_user == cli_effective_ansible_user)
    else "/home/" ~ cli_effective_user
  }}
cli_ducktape_path: "{{ cli_effective_home }}/code/ducktape"
