apiVersion: v1
kind: Secret
metadata:
  name: openclaw-anthropic-api-key
  namespace: openclaw-gateway
  annotations:
    description: Anthropic API key
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:EtIzJEn5ZtQXsQ==,iv:bH5DgZhYdprjjglhh9JG3glY7em9ULSPvkM6Akzf7dM=,tag:ktXX1fcPIYG92RSv+dxs4g==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NlpQV3BFaFVMdVA5ZmRS
        WnRuclBxWjBzajV5cXZpUVVCVXc2Y3dpQ0Z3Cm04cEtqZmRLelVLWWxIdGVNcW5x
        R0JaMEJMOGpNcCtMOWxDcnNSVGZJRlkKLS0tIDhjVFRmREtSS3dadFlSdGFBUm5I
        ZGFpR3RTVi9EcGMvOFd2R0JuQ21rMTAKFQw2xd3fIFsFCBUhKHjpYXEHXtRHj2Fj
        1gPrjtYD7xkytmayyG/SKVV4U6ZlsAEXa5uMMZnI9vsPnf3BP/lzBw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabmUzOGxsakI1dExTS2tF
        c0VPSFN6VUczWmt3SGVCbXdyblExUXY0WFhrClRkcUlCUDRSanFXZUF1cE5CVTEw
        UUNTQUdiV1BoUkIzVkNHeUlvOXZqODAKLS0tIHB3ZWxkUkthLyswVUdaeFRGNWFD
        RlVPMy9YOVBFT2cyVXhZYXdLQ1VUTUEK6pbP1lobFoNdnw0zGV2+VKK9aoJWqeb9
        XYfrv568Mt2il+kUmEiKsQHsqIlCCo/OSxZGLXZKvN00qofVLbS7OQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:16Z"
  mac: ENC[AES256_GCM,data:r32Q/uitHWwa+f6bzhSXZuao2RuatRtr0jpNeyqj+pZGrB0a1tJZeDWKdUXUmReEfB/lg5/4EMsRiAB31o9VQDplcZx0ovPPS/+q4Q9Z7/CCyvdIcMF8Y2jcY+qerG3Jy+IrfB9U7cJ9fu/m8XmRV+AdlHEeZGV6a4TW2Y0JLdU=,iv:+PC35XWn4NAznGaAXx2lENg4s6QQGTm86Xwgx+h9lx8=,tag:aqxp9SgYP3eIliBUDWZlUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
