apiVersion: v1
kind: Secret
metadata:
  name: openclaw-openai-api-key
  namespace: openclaw-gateway
  annotations:
    description: OpenAI API key
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:5UdKqTCOaTboqg==,iv:Wpfos6TTRaFJFN/6D5vi2HbfUayBnGQ7vsdCjXhIYS4=,tag:/C4M2yJwxA1eP9glBr7OOg==,type:str]
sops:
  age:
    - recipient: age1u858fg7wyakvv5tj7dh3e04jc4hvj7l8880m4nhh9djtx8g04gxs8xyjh0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eVpUV0VWOURabThvbEhB
        Q1dUaUh6TTZBT2dyaDh6YWU4d3JzZmJrTGlZCnI1MFFLZ1g0ZTU0TVl4NkFiMFdv
        enhwYWZDVFA4RmhDQUF3K01INkVvT00KLS0tIHpSNVZNbGs0WHdibjg4bTlLRDlS
        emR0QTBTNm5IaWtWTnpHQ3RRcmVtemsKHgxP6OAIqaqo0HvlsZtVMA1B10Me+0+Z
        C6wr1QV7gS4bFlRtRq1DQI9rqiaQOOEb8gbRgveetzR8hJrWPYeAQg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1nywlwepsyfxvyhqwkjquzz02nmus65gf6qewfjju4alym8f7se5qnua8na
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dm1kUTZQc3BkejN4QWZC
        YTNuQnFmcEVTVWpEdE9BMndEcjF0RmVYWXpBCmsreVl5SHdHN3UyUC9rcW9pWThQ
        WkhScXArZkNIb3BNdS9ndzNpdFE4aTAKLS0tIEdZUzY3aHNoSnBKZ0Q0L3V6WkJR
        elpkVTZNQ3RHeUhob29rMmRLZy9sb1EKiVJQMb0/0N8cqFAZ6cdlxGukJ7GsCgah
        eynTWpZ1iZ9wPutH4ceT43U+cWb5g8Uoel3d7SnzMLWov2YKRQsW/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:50:16Z"
  mac: ENC[AES256_GCM,data:qj6APijt4vMJWHCic82OzEP3AvuyEmO2GuouqHVt3f3xy44ei0hKgkdJobEE92MmeSz4RebC26zCMf0XmbnToaD4V+WmCBLK0R05Ce8Uy1IyNS8tfx7JCu7cVexSjvJ6R8MebHs+2qKyYkK+BnZL30jrdqHdXtrAs7QT/Dr3ECA=,iv:jK0YKCNKNVBN9W5FRzQUyQ7eTgdZYhlRp+u4kvZQLbQ=,tag:0m+DrVNK8ejv7Xlo+R8hzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
