load("//devinfra/python:defs.bzl", "py_library", "py_test")

py_library(
    name = "filename_conventions",
    srcs = ["filename_conventions.py"],
    visibility = ["//visibility:public"],
    deps = ["@pypi//pygit2"],
)

py_test(
    name = "test_filename_conventions",
    srcs = ["test_filename_conventions.py"],
    deps = [
        ":filename_conventions",
        "@pypi//pygit2",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "terraform_centralization",
    srcs = ["terraform_centralization.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "test_tag",
    srcs = ["test_tag.py"],
    visibility = ["//visibility:public"],
    deps = ["@pypi//httpx"],
)

py_test(
    name = "test_test_tag",
    srcs = ["test_test_tag.py"],
    deps = [
        ":test_tag",
        "@pypi//httpx",
        "@pypi//pytest",
        "@pypi//pytest_bazel",
    ],
)

py_library(
    name = "ducktape_precommit",
    srcs = ["ducktape_precommit.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":filename_conventions",
        ":terraform_centralization",
        "//cluster/scripts/validate_cluster:main",
        "//devinfra:pytest_main",
        "//devinfra/precommit/enforce_bazel_tests",
        "@pypi//pygit2",
    ],
)
