apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tana-mcp-config-ovh
  namespace: tana-mcp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-ovh
  resources:
    requests:
      storage: 10Gi
