load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "main_lib",
    srcs = ["main.go"],
    importpath = "github.com/agentydragon/ducktape/haku/kube_api_proxy/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//haku/kube_api_proxy",
        "@com_github_caarlos0_env_v11//:env",
    ],
)

go_binary(
    name = "haku-kube-api-proxy",
    embed = [":main_lib"],
    pure = "on",
    visibility = ["//visibility:public"],
)

go_test(
    name = "main_test",
    srcs = ["main_test.go"],
    embed = [":main_lib"],
)
