load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "api",
    srcs = [
        "machine.go",
        "readonly.go",
        "server.go",
    ],
    importpath = "github.com/agentydragon/ducktape/cluster/kubespand/api",
    visibility = ["//cluster/kubespand:__subpackages__"],
    deps = [
        "@com_github_cosi_project_runtime//api/v1alpha1",
        "@com_github_cosi_project_runtime//pkg/state",
        "@com_github_cosi_project_runtime//pkg/state/protobuf/server",
        "@com_github_hashicorp_go_multierror//:go-multierror",
        "@com_github_nberlee_go_netstat//netstat",
        "@com_github_prometheus_procfs//:procfs",
        "@com_github_siderolabs_gen//xslices",
        "@com_github_siderolabs_go_kmsg//:go-kmsg",
        "@com_github_siderolabs_go_pointer//:go-pointer",
        "@com_github_siderolabs_talos_pkg_machinery//api/common",
        "@com_github_siderolabs_talos_pkg_machinery//api/machine",
        "@com_github_siderolabs_talos_pkg_machinery//version",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_x_sys//unix",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "api_test",
    srcs = ["server_test.go"],
    deps = [
        ":api",
        "@com_github_cosi_project_runtime//api/v1alpha1",
        "@com_github_cosi_project_runtime//pkg/resource",
        "@com_github_cosi_project_runtime//pkg/state",
        "@com_github_cosi_project_runtime//pkg/state/impl/inmem",
        "@com_github_cosi_project_runtime//pkg/state/impl/namespaced",
        "@com_github_cosi_project_runtime//pkg/state/protobuf/client",
        "@com_github_siderolabs_talos_pkg_machinery//api/machine",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//status",
        "@org_golang_google_grpc//test/bufconn",
        "@org_golang_google_protobuf//types/known/emptypb",
    ],
)
