apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm-servicemonitor
  namespace: ducktape-flux
spec:
  interval: 10m
  path: ./cluster/k8s/litellm/servicemonitor
  prune: true
  sourceRef:
    kind: GitRepository
    name: ducktape

    namespace: ducktape-flux
  dependsOn:
    - name: litellm
      namespace: flux-system
    - name: monitoring-stack
      namespace: flux-system
